### ISSUE TITLE
invocation.functionName property

### ISSUE THREAD

**Issue by wynntee** [OfficeDev/office-js-docs-reference#1000]
I noticed the invocation object has a property called "functionName", but this isn't documented anywhere. The property is useful in cases where different Excel custom functions are associated with the same underlying JS function for whatever reason.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ce21ecd2-3f41-d3ba-58ea-7ab9bd57c4a7
* Version Independent ID: fcb02eb6-604d-d20f-ba70-bdfbfe2aff4c
* Content: [CustomFunctions.Invocation interface - Office Add-ins](https://docs.microsoft.com/en-us/javascript/api/custom-functions-runtime/customfunctions.invocation?view=excel-js-preview)
* Content Source: [docs/docs-ref-autogen/excel/custom-functions-runtime/customfunctions.invocation.yml](https://github.com/OfficeDev/office-js-docs-reference/blob/live/docs/docs-ref-autogen/excel/custom-functions-runtime/customfunctions.invocation.yml)
* Product: **excel**
* Technology: **add-ins**
* GitHub Login: @o365devx
* Microsoft Alias: **o365devx**

**Comment by AlexJerabek** [comment]
Thanks for reporting this @wynntee.

@alison-mk, could you please investigate?

**Comment by alison-mk** [comment]
Hi @wynntee, thank you for submitting. I'm investigating this issue. Could you send along a sample of the code you're using to access the `functionName` property? 

Thanks, 
Alison

**Comment by wynntee** [comment]
Hi @alison-mk , to send you such a code, I would have to send you my entire Add-in and source code for custom functions. To reproduce, simply console.log(invocation) where invocation is the last argument passed to any custom function you can create yourself. The WebView2 developer's console will show you the invocation object. One of its properties is "functionName", which seems to reference the ID of the custom function from the JSON metadata file.
