### ISSUE TITLE
I need get User role, phone and picture

### ISSUE THREAD

**Issue by mvegaca** [OfficeDev/office-js-docs-reference#1034]
Hi team.

Reading this doc
https://docs.microsoft.com/en-us/javascript/api/outlook/office.emailuser?view=outlook-js-preview

I can get the user display name and email address, how can I get the user role, phone and picture?

Thanks ;)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 32c93fcb-4f18-7892-3bb6-acafad4d7022
* Version Independent ID: e29bffaa-b47d-6c7e-5935-99f9a2b0456f
* Content: [Office.EmailUser interface - Office Add-ins](https://docs.microsoft.com/en-us/javascript/api/outlook/office.emailuser?view=outlook-js-preview#feedback)
* Content Source: [docs/docs-ref-autogen/outlook/outlook/office.emailuser.yml](https://github.com/OfficeDev/office-js-docs-reference/blob/live/docs/docs-ref-autogen/outlook/outlook/office.emailuser.yml)
* Product: **outlook**
* Technology: **add-ins**
* GitHub Login: @o365devx
* Microsoft Alias: **o365devx**

**Comment by AlexJerabek** [comment]
Hi @mvegaca,

Thanks for the question. Let me assign @ElizabethSamuel-MSFT to help out.

**Comment by ElizabethSamuel-MSFT** [comment]
@mvegaca You may need to use Microsoft Graph to get this information. For example, the following may be helpful.

- [Get photo](https://docs.microsoft.com/graph/api/profilephoto-get?view=graph-rest-1.0)
- [Get user](https://docs.microsoft.com/graph/api/user-get?view=graph-rest-1.0&tabs=http)

@exextoc I don't believe info like the user's phone number and photo can be retrieved through the JavaScript API. Can you confirm if that's the case or advise on the appropriate API/objects, etc.?

Thanks.

**Comment by exextoc** [comment]
That is correct. Currently the feature:Getting user role, picture, phone, you requested, is not a part of the product. We track Outlook add-in feature requests on our [Tech Community Page](https://techcommunity.microsoft.com/t5/microsoft-365-developer-platform/idb-p/Microsoft365DeveloperPlatform). Please submit your request there and choose the appropriate label(s). Feature requests on Tech Community are considered, when we go through our planning process.

**Comment by ElizabethSamuel-MSFT** [comment]
@mvegaca It should be noted that the EmailUser object usually represents [entities extracted from the subject and body of an item](https://docs.microsoft.com/office/dev/add-ins/outlook/extract-entity-strings-from-an-item) (e.g., [meeting suggestions](https://docs.microsoft.com/office/dev/add-ins/outlook/extract-entity-strings-from-an-item#extracting-meeting-suggestions), [task suggestions](https://docs.microsoft.com/office/dev/add-ins/outlook/extract-entity-strings-from-an-item#extracting-task-suggestions)).

To get the user's display name and email address, a better object may be [UserProfile](https://docs.microsoft.com/javascript/api/outlook/office.userprofile?view=outlook-js-preview).

**Comment by mvegaca** [comment]
Thank you so much team!
I hope I will need to work with the MS Graph API.
