### ISSUE TITLE
Incorrect object, and non-working examples

### ISSUE THREAD

**Issue by gitcnd** [OfficeDev/office-js-docs-reference#1037]
This object does not exist - and your examples make no sense (they're entirely missing all context for how to access and use this, if it even exists.)

Here's an example of how to write an example:

    var organizerAddress = Office.context.mailbox.item.organizer.emailAddress;

Note how the above includes the entirety of the context needed to access the object.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 32c93fcb-4f18-7892-3bb6-acafad4d7022
* Version Independent ID: e29bffaa-b47d-6c7e-5935-99f9a2b0456f
* Content: [Office.EmailUser interface - Office Add-ins](https://docs.microsoft.com/en-us/javascript/api/outlook/office.emailuser?view=outlook-js-preview)
* Content Source: [docs/docs-ref-autogen/outlook/outlook/office.emailuser.yml](https://github.com/OfficeDev/office-js-docs-reference/blob/live/docs/docs-ref-autogen/outlook/outlook/office.emailuser.yml)
* Product: **outlook**
* Technology: **add-ins**
* GitHub Login: @o365devx
* Microsoft Alias: **o365devx**

**Comment by AlexJerabek** [comment]
Hi @gitcnd,

We'll add an example to the reference documentation EmailUser. In the meantime, please check out the sample shown in [Extract entity strings from an Outlook item - Extracting meeting suggestions](https://docs.microsoft.com/en-us/office/dev/add-ins/outlook/extract-entity-strings-from-an-item#extracting-meeting-suggestions) for an example of how the EmailUser object fits into the Outlook object model.

Assigning to @ElizabethSamuel-MSFT.

**Comment by ElizabethSamuel-MSFT** [comment]
@gitcnd The PRs have been merged and updated documentation should be published soon. Thanks again for raising this issue and let us know if you have any further concerns or questions.

Thanks.
