### ISSUE TITLE
Obtain preview image of slide?

### ISSUE THREAD

**Issue by LukeOwlclaw** [OfficeDev/office-js-docs-reference#1053]
Is it possible to obtain an image of the current slide? Is this feature planned?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4666676e-3918-dafc-4846-efbf7363aabf
* Version Independent ID: eba73286-6426-887e-477a-ed9f641dac0f
* Content: [PowerPoint.Shape class - Office Add-ins](https://docs.microsoft.com/en-us/javascript/api/powerpoint/powerpoint.shape?view=powerpoint-js-preview)
* Content Source: [docs/docs-ref-autogen/powerpoint/powerpoint/powerpoint.shape.yml](https://github.com/OfficeDev/office-js-docs-reference/blob/live/docs/docs-ref-autogen/powerpoint/powerpoint/powerpoint.shape.yml)
* Product: **powerpoint**
* Technology: **add-ins**
* GitHub Login: @o365devx
* Microsoft Alias: **o365devx**

**Comment by ElizabethSamuel-MSFT** [comment]
@LukeOwlclaw Thanks for your interest and for asking about this.

@Rick-Kirkham Can you take a look?

Thanks.

**Comment by Rick-Kirkham** [comment]
This is not possible and is not planned. Sorry. But you can suggest it at [Microsoft Q&A](https://docs.microsoft.com/answers/index.html).
