### ISSUE TITLE
Obtain binary data of slide?

### ISSUE THREAD

**Issue by LukeOwlclaw** [OfficeDev/office-js-docs-reference#1054]
Is it possible to obtain the binary data of a single slide? That is a PPTX file containing only one slide or one shape? Is this feature planned?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4666676e-3918-dafc-4846-efbf7363aabf
* Version Independent ID: eba73286-6426-887e-477a-ed9f641dac0f
* Content: [PowerPoint.Shape class - Office Add-ins](https://docs.microsoft.com/en-us/javascript/api/powerpoint/powerpoint.shape?view=powerpoint-js-preview)
* Content Source: [docs/docs-ref-autogen/powerpoint/powerpoint/powerpoint.shape.yml](https://github.com/OfficeDev/office-js-docs-reference/blob/live/docs/docs-ref-autogen/powerpoint/powerpoint/powerpoint.shape.yml)
* Product: **powerpoint**
* Technology: **add-ins**
* GitHub Login: @o365devx
* Microsoft Alias: **o365devx**

**Comment by ElizabethSamuel-MSFT** [comment]
@LukeOwlclaw Thanks for asking about this.

@Rick-Kirkham Can you take a look?

Thanks.

**Comment by Rick-Kirkham** [comment]
I'm afraid that there is no way to do this currently, and it is not in our plans. Consider making a request for this feature at [Microsoft Q&A](https://docs.microsoft.com/answers/index.html).
