### ISSUE TITLE
Clarify support for Body.paragraphs for paragraphs in tables.

### ISSUE THREAD

**Issue by AbidRahman-MSFT** [OfficeDev/office-js-docs-reference#1076]
For Body.paragraphs, clarify the behavior:

For requirement set 1.1 and 1.2: Paragraphs in tables are not returned.
For requirement set 1.3: Paragraphs in tables are returned.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1585011c-7b37-17cf-1eb3-4306852ccffc
* Version Independent ID: ae9d47cd-be15-d72b-f22d-06c881b63717
* Content: [Word.Body class - Office Add-ins](https://docs.microsoft.com/en-us/javascript/api/word/word.body?view=word-js-1.1#paragraphs)
* Content Source: [docs/docs-ref-autogen/word_1_1/word/word.body.yml](https://github.com/OfficeDev/office-js-docs-reference/blob/live/docs/docs-ref-autogen/word_1_1/word/word.body.yml)
* Product: **word**
* Technology: **add-ins**
* GitHub Login: @o365devx
* Microsoft Alias: **o365devx**

**Comment by ElizabethSamuel-MSFT** [comment]
This update has been published. Thx.
