### ISSUE TITLE
Example for onDelete event of content control

### ISSUE THREAD

**Issue by FedousJahan** [OfficeDev/office-js-docs-reference#1145]
I am having a hard time trying to implement onDelete event fire for content control. Documentation does not provide any sample code snippets to follow. Can someone please provide one sample implementation code snippet?
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 18b63cfd-c1ea-baed-f96f-b14664b384c5
* Version Independent ID: 52aaa0e2-be99-c2e7-3042-fb652420613e
* Content: [Word.ContentControl class - Office Add-ins](https://docs.microsoft.com/en-us/javascript/api/word/word.contentcontrol?view=word-js-preview)
* Content Source: [docs/docs-ref-autogen/word/word/word.contentcontrol.yml](https://github.com/OfficeDev/office-js-docs-reference/blob/live/docs/docs-ref-autogen/word/word/word.contentcontrol.yml)
* Product: **word**
* Technology: **add-ins**
* GitHub Login: @o365devx
* Microsoft Alias: **o365devx**

**Comment by AlexJerabek** [comment]
Hi @FedousJahan,

Thank for raising this need for sample code. @ElizabethSamuel-MSFT, could you plese look into developing a reference doc sample for this scenario?

**Comment by ElizabethSamuel-MSFT** [comment]
@FedousJahan We've added this to our backlog of work and we aim to get to this as soon as possible.

However, it's similar to the pattern for [Excel events](https://docs.microsoft.com/office/dev/add-ins/excel/excel-add-ins-events#register-an-event-handler). Can you see if this unblocks you?

Excel examples using onDeleted:
- [ChartCollection](https://docs.microsoft.com/javascript/api/excel/excel.chartcollection?view=excel-js-preview#excel-excel-chartcollection-ondeleted-member)
- [CommentCollection](https://docs.microsoft.com/javascript/api/excel/excel.commentcollection?view=excel-js-preview#excel-excel-commentcollection-ondeleted-member)

And don't load the content control in your handler code else you lose the content control information (see note in [ContentControl.onDeleted](https://docs.microsoft.com/javascript/api/word/word.contentcontrol?view=word-js-preview#word-word-contentcontrol-ondeleted-member)).

Thanks.

**Comment by ElizabethSamuel-MSFT** [comment]
@FedousJahan We've created a PR that adds a code snippet showing how to register and use the ContentControl.onDeleted event. Let us know if this helps.

Thanks.
