### ISSUE TITLE
Outlook: NotificationMessageAction potentially needs clarity on desktop app specifics

### ISSUE THREAD

**Issue by dimitri-bourreau** [OfficeDev/office-js-docs-reference#1168]
# Feedback

I followed [Office.NotificationMessageAction interface documentation](https://docs.microsoft.com/en-us/javascript/api/outlook/office.notificationmessageaction?view=outlook-js-preview).

It allowed me to use the explained feature on Outlook for web but not properly on Outlook Desktop.

I guess something is missing or could be clarified.

I would be happy to contribute or, at least, help. 👍

##  Details

I am working on an Outlook add-in that worked perfectly on Outlook for web. 

`NotificationMessageAction` worked perfectly, without any error.

On desktop, all the features of the add-in runs smoothly, except `NotificationMessageAction`.

- Web : the info bar appears, with our company's icon and links for a) a specific action and b) to dismiss the info bar.
- Outlook Mac : the info bar appears, not with my icon but a generic _i_, and no links.
- Outlook Windows : the info bar does not appear.

### Tools

- MacOS 12.1
    - Chrome 98.0.4758.102
    - Outlook 16.59
- Windows 11 v.21H2 (22000.493)
    - Chrome 98.0.4758.102
    - Outlook 2201 (14827.20198)
- Node v.16.14.0
- yo 4.3.0

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 742b29d6-6ac5-6c43-a684-b88af36eadca
* Version Independent ID: 4f13bc13-7665-fbb3-5cb8-276ef23342f9
* Content: [Office.NotificationMessageAction interface - Office Add-ins](https://docs.microsoft.com/en-us/javascript/api/outlook/office.notificationmessageaction?view=outlook-js-preview)
* Content Source: [docs/docs-ref-autogen/outlook/outlook/office.notificationmessageaction.yml](https://github.com/OfficeDev/office-js-docs-reference/blob/live/docs/docs-ref-autogen/outlook/outlook/office.notificationmessageaction.yml)
* Product: **outlook**
* Technology: **add-ins**
* GitHub Login: @o365devx
* Microsoft Alias: **o365devx**

**Comment by AlexJerabek** [comment]
Thanks for reporting this issue @dimitri-bourreau.

@exextoc, could you confirm this behavior and investigate? Thank you.

**Comment by exextoc** [comment]
The sample ran and the info bar shows up correctly for me in Win32.  Do you get an error with the API call in the API callback and if so could you include the error here? 
 One thing to keep in mind that commandId needs to be defined in the manifest.  For this example, the msgComposeOpenPaneButton is defined in the manifest as <Control xsi:type="Button" id="msgComposeOpenPaneButton"> under MessageComposeCommandSurface for compose.

**Comment by dimitri-bourreau** [comment]
Since everything is working perfectly on the web and no errors occurs there, I guess the manifest is well made and following your advice I don't see any problem there.

We are going to avoid using the info bar, we are not willing to dedicate more time to this feature.

If following the docs everything's fine on your side, I'd agree closing this issue would be a good idea.
