### ISSUE TITLE
Descriptions for Error.message and Error.name look reversed

### ISSUE THREAD

**Issue by jasonclg** [OfficeDev/office-js-docs-reference#1181]
Makes more sense to me if they were reversed:

message
Gets a detailed description of the error.

name
Gets the name of the error.

#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 19b9d330-11a4-380f-4f44-342771892988
* Version Independent ID: e64fa016-f63f-69c9-2751-a3cacc11b1fe
* Content: [Office.Error interface - Office Add-ins](https://docs.microsoft.com/en-us/javascript/api/office/office.error?view=common-js-preview)
* Content Source: [docs/docs-ref-autogen/office/office/office.error.yml](https://github.com/OfficeDev/office-js-docs-reference/blob/live/docs/docs-ref-autogen/office/office/office.error.yml)
* Product: **non-product-specific**
* Technology: **add-ins**
* GitHub Login: @o365devx
* Microsoft Alias: **o365devx**

**Comment by AlexJerabek** [comment]
Thanks for reporting this @jasonclg. That does look backwards. I'll update it in the upstream type definition file that our documentation uses.

**Comment by AlexJerabek** [comment]
This will be fixed by #1182. I'll close the issue, since the changes are in and the published docs will be updated eventually.

@jasonclg, thank you again for reporting this issue. We appreciate your contribution to make this documentation better.
