### ISSUE TITLE
How to add a section?

### ISSUE THREAD

**Issue by lelsteph** [OfficeDev/office-js-docs-reference#1199]
How should a section be added? There is no method. Can I just push to the items array a new Word.Section?
lelsteph

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 27217244-4f3c-9d99-e373-b541dcd1e3e2
* Version Independent ID: b6cc00e8-265f-6c83-f149-7e739b6f8368
* Content: [Word.SectionCollection class - Office Add-ins](https://docs.microsoft.com/en-us/javascript/api/word/word.sectioncollection?view=word-js-preview)
* Content Source: [docs/docs-ref-autogen/word/word/word.sectioncollection.yml](https://github.com/OfficeDev/office-js-docs-reference/blob/live/docs/docs-ref-autogen/word/word/word.sectioncollection.yml)
* Product: **word**
* Technology: **add-ins**
* GitHub Login: @o365devx
* Microsoft Alias: **o365devx**

**Comment by AlexJerabek** [comment]
Hi @lelsteph,

I believe there isn't currently a way to add sections. The SectionCollection in the Document object is only for accessing Sections. You can edit the Body of a Section and add Paragraphs to that. The Paragraph samples in [Script Lab](https://docs.microsoft.com/en-us/office/dev/add-ins/overview/explore-with-script-lab?view=word-js-preview) demonstrate how to do that.

Is there a particular scenario you're trying to accomplish? @ElizabethSamuel-MSFT can help make sure we have samples in that area.

**Comment by ElizabethSamuel-MSFT** [comment]
See https://github.com/OfficeDev/office-js-docs-reference/issues/1202 for some detail re: scenario

**Comment by ElizabethSamuel-MSFT** [comment]
@lelsteph The API somewhat mimics the user's actions in the Word document UI. To create a section, you need to [insert a section break](https://support.microsoft.com/en-us/office/insert-a-section-break-eef20fd8-e38c-4ba6-a027-e503bdf8375c).

To do this using the API, you'd have to call [Body.insertBreak](https://docs.microsoft.com/en-us/javascript/api/word/word.body?view=word-js-preview#word-word-body-insertbreak-member(1)) or maybe [Range.insertBreak](https://docs.microsoft.com/en-us/javascript/api/word/word.range?view=word-js-preview#word-word-range-getooxml-member(1)) as appropriate for your scenario.

Can you try this and see if it helps?

Thanks.

**Comment by lelsteph** [comment]
Hello

I was thinking about this and had it on my todo list.
But I cannot make it, can you please help to understand the correct structure I should use. Here is one of my tentatives.

```
    //Create the required header and footer types
    //Loop on all sections
    for (let sectionIndex = 0; sectionIndex < reportDoc.sections.items.length; sectionIndex++) {
      let sourceHeaderOoxml: OfficeExtension.ClientResult<string>;
      let destinationHeaderOoxml: OfficeExtension.ClientResult<string>;
      //First Page Header / Footer
      try {
        sourceHeaderOoxml = reportDoc.sections.items[sectionIndex].getHeader(Word.HeaderFooterType.firstPage).getRange('Content').getOoxml(); //Must use Content to get exception
        await context.sync();
        destinationHeaderOoxml = context.document.sections.items[sectionIndex].getHeader(Word.HeaderFooterType.firstPage).getRange('Content').getOoxml(); //Must use Content to get exception
        await context.sync();
      } catch {
        //Create Destination Header if missing
        if (sourceHeaderOoxml && !destinationHeaderOoxml) {
          context.document.sections.items[sectionIndex].getHeader(Word.HeaderFooterType.firstPage).insertBreak(Word.BreakType.sectionNext, Word.InsertLocation.end);
          await context.sync();
        }
      }

      //Even page Header / Footer
      try {
        sourceHeaderOoxml = reportDoc.sections.items[sectionIndex].getHeader(Word.HeaderFooterType.evenPages).getRange('Content').getOoxml(); //Must use Content to get exception
        await context.sync();
        destinationHeaderOoxml = context.document.sections.items[sectionIndex].getHeader(Word.HeaderFooterType.evenPages).getRange('Content').getOoxml(); //Must use Content to get exception
        await context.sync();
      } catch {
        //Create Destination Header if missing
        if (sourceHeaderOoxml && !destinationHeaderOoxml) {
          context.document.sections.items[sectionIndex].getHeader(Word.HeaderFooterType.evenPages).insertBreak(Word.BreakType.sectionEven, Word.InsertLocation.end);
          await context.sync();
        }
      }
    }
```

Stephane.

**Comment by ElizabethSamuel-MSFT** [comment]
Based on our discussion in https://github.com/OfficeDev/office-js-docs-reference/issues/1202, you were able to create new sections using insertBreak.

We'll add an item to the backlog to see if we can include an example to Section and/or SectionCollection that shows this.

**Comment by lelsteph** [comment]
NO I do not think I was able to create sections, I was able to insert breaks in the body of the main document.
Stephane.

**Comment by lelsteph** [comment]
Yes sorry, was too late yesterday. Let me recheck, I guess this is right. Give me some time to double confirm.
Thanks

**Comment by lelsteph** [comment]
Hello, Yes sections can be created by inserting a section break. This is working thank you!
