### ISSUE TITLE
DocCreated and what??

### ISSUE THREAD

**Issue by lelsteph** [OfficeDev/office-js-docs-reference#1200]
How "A DocumentCreated object is a special Document object" can be usefull to anyone??

Once we have a DocumentCreated, how to get the context to be assigned to it and replace the current Word.Document?

lelsteph

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1d1d8c75-ea38-aed8-73ba-fbf27bb6118d
* Version Independent ID: 802e07cc-4610-6184-bed4-5f4ec499cd47
* Content: [Word.DocumentCreated class - Office Add-ins](https://docs.microsoft.com/en-us/javascript/api/word/word.documentcreated?view=word-js-preview)
* Content Source: [docs/docs-ref-autogen/word/word/word.documentcreated.yml](https://github.com/OfficeDev/office-js-docs-reference/blob/live/docs/docs-ref-autogen/word/word/word.documentcreated.yml)
* Product: **word**
* Technology: **add-ins**
* GitHub Login: @o365devx
* Microsoft Alias: **o365devx**

**Comment by AlexJerabek** [comment]
Thanks for raising this issue @lelsteph.

@ElizabethSamuel-MSFT, could you please investigate documentation improvements for this API?

**Comment by lelsteph** [comment]
Would first be needed to understand what is the purpose of DocCreated...
For ex, reading a file
```
    const reportDoc: Word.DocumentCreated = context.application.createDocument(templateFileBase64.dataBase64);
    await context.sync();
```
At this time I can access it using reportDoc, ex:
```
      const ooxml: OfficeExtension.ClientResult<string> = reportDoc.sections.items[sectionIndex].getHeader(Word.HeaderFooterType.evenPages).getRange('Content').getOoxml();
      await context.sync();
```

If I open it then it is no more accessible by any mean...
```
reportDoc.open();
await context.sync();
```

If I want to save the document, there is no "save as" function then I need to use the complex way describe [here](https://docs.microsoft.com/fr-fr/office/dev/add-ins/word/get-the-whole-document-from-an-add-in-for-word)

There is apparently no solution to have "getFileAsync" to access reportDoc DocCreated...

Running in circles like this in multiple areas of the Word APIs.

So can you please explain what is the purpose of DocCreated and why it was "invented" ? Why isn't it a Document which is created which we could re-assign to the context from where the add-in is running?

Thank you

**Comment by ElizabethSamuel-MSFT** [comment]
@lelsteph We've added this item to our backlog to clarify the use case in the documentation.

Thanks.

**Comment by ElizabethSamuel-MSFT** [comment]
> If I open it then it is no more accessible by any mean...
> 
> ```
> reportDoc.open();
> await context.sync();
> ```

My understanding here is that reportDoc would open in a new Word instance (window or tab) and the user would need to interact with it there and no longer in the original Word instance.

**Comment by lelsteph** [comment]
Yes this is apparently what happens, would be good to keep a reference to it... What can we do with a DocCreated? How can we save it? etc... I can create the document which is good but I cannot go to the end of all what I need to do and this leave some manual work to the user which customers do not want!

**Comment by ElizabethSamuel-MSFT** [comment]
@lelsteph @jgmamxmn We've since added code examples along with more DocumentCreated APIs in [WordApiHiddenDocument 1.5](https://learn.microsoft.com/javascript/api/requirement-sets/word/word-api-requirement-sets?view=word-js-preview#requirement-set-availability). I'm going to close this issue now but do create another issue if you have other questions about our APIs.

Thanks once again for your interest in developing Office Add-ins.

**Comment by ltech38g** [comment]
Hello

I just used the save function and it works very well, I can now save directly to the SharePoint! Thanks a lot again.

However, fields are not updated. For ex, I have a table of content that must be updated as I manipulated / created the word file.

How should I do this?

Thank you!
