### ISSUE TITLE
New OfficeJS url scheme returns a 404 for all of the old urls

### ISSUE THREAD

**Issue by gummybuns** [OfficeDev/office-js-docs-reference#1210]
Hi OfficeJS Team,

All of your old links are throwing 404 now

For example:

Old:
https://docs.microsoft.com/en-us/office/dev/add-ins/reference/objectmodel/requirement-set-1.9/office.context.mailbox.item

New:
https://docs.microsoft.com/en-us/javascript/api/requirement-sets/outlook/requirement-set-1.9/office.context.mailbox.item?view=common-js-preview

This is a problem for u guys (and an inconvenience to developers) because all of your top searches on google are now effectively broken

This is a problem for us specifically (and likely others) because all of our internal documentation that references the old links is broken as well

Ideally the old urls can 301 or 302 redirect to the new urls

Thank you
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c4615155-a376-6877-e1fd-a7960b21f751
* Version Independent ID: 916b65e9-5f43-f53b-0d6b-bf08a008a830
* Content: [Office.context.mailbox.item - requirement set 1.9 - Office Add-ins](https://docs.microsoft.com/en-us/javascript/api/requirement-sets/outlook/requirement-set-1.9/office.context.mailbox.item?view=common-js-preview)
* Content Source: [docs/requirement-sets/outlook/requirement-set-1.9/office.context.mailbox.item.md](https://github.com/OfficeDev/office-js-docs-reference/blob/live/docs/requirement-sets/outlook/requirement-set-1.9/office.context.mailbox.item.md)
* Product: **outlook**
* Technology: **add-ins**
* GitHub Login: @o365devx
* Microsoft Alias: **o365devx**

**Comment by AlexJerabek** [comment]
Thanks for reporting this @gummybuns. I'll set up the redirects for this Outlook requirement sets.

**Comment by gummybuns** [comment]
Thank you for the fast response @AlexJerabek !

**Comment by AlexJerabek** [comment]
Hi @gummybuns,

The redirects should now be in place. Please let me know if you're still encountering problems.

Thanks!
