### ISSUE TITLE
bismeidy

### ISSUE THREAD

**Issue by bismeidyfabian** [OfficeDev/office-js-docs-reference#1225]
****
**
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c5d7decb-4a13-03c2-1dd9-ea701f3b46ae
* Version Independent ID: dc2bd021-02d8-0a9a-9951-e38460eea242
* Content: [Excel.Interfaces.LinkedWorkbookLoadOptions interface - Office Add-ins](https://docs.microsoft.com/en-us/javascript/api/excel/excel.interfaces.linkedworkbookloadoptions?view=excel-js-preview)
* Content Source: [docs/docs-ref-autogen/excel/excel/excel.interfaces.linkedworkbookloadoptions.yml](https://github.com/OfficeDev/office-js-docs-reference/blob/live/docs/docs-ref-autogen/excel/excel/excel.interfaces.linkedworkbookloadoptions.yml)
* Product: **excel**
* Technology: **add-ins**
* GitHub Login: @o365devx
* Microsoft Alias: 
* game
* youtube
> **o365devx__

**Comment by AlexJerabek** [comment]
Hi @bismeidyfabian,

I'm unclear what this issue is about, since there is no description. I'm going to assume this was created by accident and close it. If you have a concern with the LinkedWorkbook APIs, please leave a comment on this thread and we'llreopen it.
