### ISSUE TITLE
`DebugInfo.statements` (plural) should be `DebugInfo.statement` (singular)

### ISSUE THREAD

**Issue by jesparaz-vena** [OfficeDev/office-js-docs-reference#1229]
The [`statements` property](https://docs.microsoft.com/en-us/javascript/api/office/officeextension.debuginfo?view=excel-js-preview#office-officeextension-debuginfo-statements-member) on the `DebugInfo` interface should be `statement?: string` (singular) not `statements?: string` (plural).

Example exception created in Script Lab:

```
[ERROR]: Error:
{
    "stack": "RichApi.Error: The requested resource doesn't exist.\n    at new n (https://appsforoffice.microsoft.com/lib/1/hosted/excel-win32-16.01.js:26:240738)\n    at n.i.processRequestExecutorResponseMessage (https://appsforoffice.microsoft.com/lib/1/hosted/excel-win32-16.01.js:26:305072)\n    at https://appsforoffice.microsoft.com/lib/1/hosted/excel-win32-16.01.js:26:303134",
    "message": "The requested resource doesn't exist.",
    "name": "RichApi.Error",
    "code": "ItemNotFound",
    "traceMessages": [],
    "innerError": null,
    "debugInfo": {
        "code": "ItemNotFound",
        "message": "The requested resource doesn't exist.",
        "errorLocation": "WorksheetCollection.getItem",
        "statement": "var worksheet = worksheets.getItem(...);",
        "surroundingStatements": [
            "var workbook = context.workbook;",
            "var worksheets = workbook.worksheets;",
            "// >>>>>",
            "var worksheet = worksheets.getItem(...);",
            "// <<<<<"
        ],
        "fullStatements": [
            "Please enable config.extendedErrorLogging to see full statements."
        ]
    },
    "httpStatusCode": 404
}
```

![image](https://user-images.githubusercontent.com/92549265/166978599-34ed1a4f-48f4-4918-9a0e-d9dadb8379ac.png)

The [type definitions](https://www.npmjs.com/package/@types/office-js) also have the same issue (not sure if the docs and type definitions are generated from the same source).

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7a1d8c0f-8b61-b5d6-14ab-11e947ea271e
* Version Independent ID: a4b62680-cf7c-1426-4a37-2655bac1c771
* Content: [OfficeExtension.DebugInfo interface - Office Add-ins](https://docs.microsoft.com/en-us/javascript/api/office/officeextension.debuginfo?view=excel-js-preview#office-officeextension-debuginfo-statements-member)
* Content Source: [docs/docs-ref-autogen/office/office/officeextension.debuginfo.yml](https://github.com/OfficeDev/office-js-docs-reference/blob/live/docs/docs-ref-autogen/office/office/officeextension.debuginfo.yml)
* Product: **non-product-specific**
* Technology: **add-ins**
* GitHub Login: @o365devx
* Microsoft Alias: **o365devx**

**Comment by AlexJerabek** [comment]
Thanks for reporting this @jesparaz-vena. I'll make the update in the type definitions and that'll refresh these docs as well.

**Comment by AlexJerabek** [comment]
Actually, @jesparaz-vena, changing the name of that property would be a breaking change. Let me confirm with the product team the intention and make sure the type definitions are inaccurate (not just the grammar).

**Comment by jesparaz-vena** [comment]
> Actually, @jesparaz-vena, changing the name of that property would be a breaking change. Let me confirm with the product team the intention and make sure the type definitions are inaccurate (not just the grammar).

@AlexJerabek thanks for the quick responses 😄 

I don't think this is breaking change since the actually property is `statement`.

My team has code that looks like this:

```ts
if ('debugInfo' in exception) {
  const {
    //@ts-ignore
    statement,
    surroundingStatements,
    errorLocation,
    message,
  } = exception.debugInfo;
  ...
}
```

We need to `@ts-ignore` because it's actually `statement`, but the type definitions think it's `statements`.

**Comment by AlexJerabek** [comment]
Ah, understood. Thank you for clarifying and providing that sample.

**Comment by AlexJerabek** [comment]
@jesparaz-vena,

Here is the upstream PR: https://github.com/DefinitelyTyped/DefinitelyTyped/pull/60215

I also verified in my own Script Lab snippet that `statement` is indeed correct. Thank you for catching this.
