### ISSUE TITLE
Word content control title is limited to 64 characters

### ISSUE THREAD

**Issue by nlt2390** [OfficeDev/office-js-docs-reference#1238]
I want to add a long title to content control but Word only shows first 64 characters and the rest is cut off.
Is there a way to display full text ? 
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 18b63cfd-c1ea-baed-f96f-b14664b384c5
* Version Independent ID: 52aaa0e2-be99-c2e7-3042-fb652420613e
* Content: [Word.ContentControl class - Office Add-ins](https://docs.microsoft.com/en-us/javascript/api/word/word.contentcontrol?view=word-js-preview)
* Content Source: [docs/docs-ref-autogen/word/word/word.contentcontrol.yml](https://github.com/OfficeDev/office-js-docs-reference/blob/live/docs/docs-ref-autogen/word/word/word.contentcontrol.yml)
* Product: **word**
* Technology: **add-ins**
* GitHub Login: @o365devx
* Microsoft Alias: **o365devx**

**Comment by AlexJerabek** [comment]
Hi @nlt2390,

Thanks for sharing this. I don't believe this is possible today, but let me tag @ElizabethSamuel-MSFT to confirm. Would it be possible for you to provide a simple Script Lab snippet that recreates this behavior?

**Comment by nlt2390** [comment]
@AlexJerabek  @ElizabethSamuel-MSFT hi this my code snippet
`
async function run() {
  await Word.run(async (context) => {
    const body = context.document.body;
    const selection = context.document.getSelection();
    const range = selection.getRange(Word.RangeLocation.content);
    
    const control = range.insertContentControl();
    control.title = "Long title 123456789 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31"

    await context.sync();
  });
}
`
The title text is cut off
 
![image](https://user-images.githubusercontent.com/4429651/168199123-7844b98d-6eee-41a7-8bdc-37617395a34e.png)

**Comment by ElizabethSamuel-MSFT** [comment]
@nlt2390 Thanks for asking about this and sharing the snippet.

It seems like this is by design of the Word UI. Even if you manually set the title property on the content control, only the first 64 characters are displayed. The API cannot override the UI limit.

Thanks and let us know if you have any further questions.

**Comment by nlt2390** [comment]
@ElizabethSamuel-MSFT  hi, is there another way to show a description for content control ? maybe sth like text hover ?

**Comment by ElizabethSamuel-MSFT** [comment]
@nlt2390 Unfortunately, it doesn't seem like hovering is an option. However, you can get the full title using the API so perhaps you can have the user select a button in your task pane to display the full title in the task pane, for example.
