### ISSUE TITLE
Missing "Attributes" section 

### ISSUE THREAD

**Issue by Rick-Kirkham** [OfficeDev/office-js-docs-reference#1255]
This article is missing the **Attributes** section. It should list the possible values of the type attribute and the meaning of each of them. E.g., ItemRead, ItemWrite. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 19f6f5a0-8d4d-c737-a721-7196a58d46cc
* Version Independent ID: 378f70f6-11c5-830f-c8fd-df0018a15d85
* Content: [Form element in the manifest file - Office Add-ins](https://docs.microsoft.com/en-us/javascript/api/manifest/form?view=common-js-preview)
* Content Source: [docs/manifest/form.md](https://github.com/OfficeDev/office-js-docs-reference/blob/live/docs/manifest/form.md)
* Product: **non-product-specific**
* Technology: **add-ins**
* GitHub Login: @o365devx
* Microsoft Alias: **o365devx**

**Comment by samantharamon** [comment]
Thank you for catching this, @Rick-Kirkham. I'm adding this to my June backlog.
