### ISSUE TITLE
Can't access document model using Word API context

### ISSUE THREAD

**Issue by NicomacheanEudaimonia** [OfficeDev/office-js-docs-reference#1272]
Hi! First, thanks for the great and very helpful documentation and samples! Second, I'm using the Word AddIn with the Word API to access a Word document. I've had some difficulty using the following which comes from [here](https://docs.microsoft.com/en-us/javascript/api/word/word.body?view=word-js-preview#word-word-body-gethtml-member%281%29) and [here](https://docs.microsoft.com/en-us/javascript/api/word/word.document?view=word-js-preview#word-word-document-context-member):

```
Office.onReady(info => {
    const a = document.getElementById("a")
    const b = document.getElementById("b")

    if (info.host === Office.HostType.Word) {
        a.onclick = function (ev) {
           Word.run((context) => {
               var thisDocument = context.document
               // ...
           })
        }
    }
})
```

However, I get the following rather than the object representation itself:

```
{ m_type: 0 }
```

I understand that the Word document model should be similar (in spirit) to the DOM. I also see a note indicating that some methods aren't supported presently. Do you mind clarifying what's missing and/or the best approach to access the document information via the Word API?

To be clear:

1. I'm using the newest version of the Office JS dependency: https://unpkg.com/@microsoft/office-js/dist/office.js
2. I've tried maybe 20 permutations (using `async`, `await`, `context.document`, `context.document.body`, etc.) and have not been able to advance past the object above.
3. Is the documentation out of date or is there something I've missed in the above?

I was able to get access to the document via `Office.context.document.getFileAsync` instead. However, the Word API is preferable.

My thanks!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: bd71647a-75de-038e-536a-7e56dd48ef3c
* Version Independent ID: a8bc56eb-0948-1ae0-0654-6b751ee9435f
* Content: [Word.Document class - Office Add-ins](https://docs.microsoft.com/en-us/javascript/api/word/word.document?view=word-js-preview#word-word-document-context-member)
* Content Source: [docs/docs-ref-autogen/word/word/word.document.yml](https://github.com/OfficeDev/office-js-docs-reference/blob/live/docs/docs-ref-autogen/word/word/word.document.yml)
* Product: **word**
* Technology: **add-ins**
* GitHub Login: @o365devx
* Microsoft Alias: **o365devx**

**Comment by AlexJerabek** [comment]
Hi @NicomacheanEudaimonia,

Have you tried exploring the Word JS object model through [Script Lab](https://docs.microsoft.com/en-us/office/dev/add-ins/overview/explore-with-script-lab)? It's a great way to see the JavaScript code interacting with the Word document. We also have a ["Hello World"](https://github.com/OfficeDev/Office-Add-in-samples/tree/main/Samples/hello-world/word-hello-world) style sample for making a basic Word Add-in.

Please let me know if those resources help. Thanks!

**Comment by NicomacheanEudaimonia** [comment]
Hi @AlexJerabek - Thanks for the helpful resources! I am indeed using the great "Hello World" Add-in example as the basis of my testing. No problems there. 

I am looking through the Script Lab now - I see the `selection()` being called (something that's omitted in the API reference docs). Let me see if that does the trick!

**Comment by AlexJerabek** [comment]
Glad to hear! Let me tag @ElizabethSamuel-MSFT to investigate that reference gap.

**Comment by NicomacheanEudaimonia** [comment]
Thanks! I've explored the https://github.com/OfficeDev/office-js-snippets/blob/main/samples/word/01-basics/basic-api-call.yaml#L13 example a bit more:

1. Copying over the code:

![1](https://user-images.githubusercontent.com/106126054/171916249-be1dfd25-59e3-4553-a93a-fe466fab72d7.PNG)

2. Without the `Office.onReady(info => {})` I now get within Word (within the Word Add-in panel):

![2](https://user-images.githubusercontent.com/106126054/171916252-26b9cd65-0aea-4cb1-8c5d-e04529104d84.PNG)

3. With the wrapping `Office.onReady(info => {})`, I am able to progress to the `console.log()` output but it still doesn't seem to have the document text information or text attributes (font, etc.):

![3](https://user-images.githubusercontent.com/106126054/171916255-5ced4d3e-8a76-47ef-bbab-1d51be0fda21.PNG)

> Upshot: the Add-in example works great.

> I used both the newest Office.js version and the version provided in the sample - looks like the Office-JS version has remained the same at v1.10 for since 2018 :https://github.com/OfficeDev/office-js/tags so not sure if it's a version thing?

**Comment by ElizabethSamuel-MSFT** [comment]
@NicomacheanEudaimonia Thanks for the kudos about the documentation and for your questions.

Depending on the feature, the user may need to take some action. For example, to access info about a selection, the user needs to select text in the document then the selection API will have access to that block of text.

You can work with the objects in the document such as body or paragraphs. For example, if you want to get the font of the document body, you would need to load the font property then run context.async. See [Word.Body.font](https://docs.microsoft.com/javascript/api/word/word.body?view=word-js-preview#word-word-body-font-member) for an example.

To build on your current sample, this would apply to the body of the document instead of a selection.

```js
const body = context.document.body;
body.font.color = "red";
body.load("text");
await context.sync();
console.log(`The body text was "${body.text}".`);
```

Let us know if this helps and if you have further questions.

Thanks.

**Comment by ElizabethSamuel-MSFT** [comment]
@NicomacheanEudaimonia Also, here is an [overview of the Word object model](https://docs.microsoft.com/office/dev/add-ins/word/word-add-ins-core-concepts). Hope it's helpful.

**Comment by NicomacheanEudaimonia** [comment]
@ElizabethSamuel-MSFT - Aha! Thanks for your great help!

Confirming that previous example far above (https://github.com/OfficeDev/office-js-snippets/blob/main/samples/word/01-basics/basic-api-call.yaml#L13) is incorrect although I am now able to access the underlying text by combining it and your answer immediately above.

To be a bit more clear I was having difficulty combining the "Hello World" example: https://github.com/OfficeDev/Office-Add-in-samples/blob/main/Samples/hello-world/word-hello-world/taskpane.html#L24 with the documentation. The "Hello World" example doesn't use **async/await**. I think in this case there must a pair of wrapping **async/await** keywords. The API documentation itself appears to be correct. I think the sample docs are also potentially incorrect: https://github.com/OfficeDev/Office-Add-in-samples/tree/main/Samples/hello-world/word-hello-world! The previous code samples themselves do not appear to be. Although the new ones do! 

Working backwards, I think I mixed and matched two or more code samples with the API reference - perhaps the code samples should be archived? I also assumed that the inner pair or outer pair would resolve without those given the previous example and since that sometimes that's implicitly handled (async will often resolve synchronous if called as such). Should've caught that haha! 

Thanks 🙏 and super helpful answers!!!!
