### ISSUE TITLE
Result.value in getFileAsync examples

### ISSUE THREAD

**Issue by NicomacheanEudaimonia** [OfficeDev/office-js-docs-reference#1273]
Hi! First, Thanks for the great and very helpful documentation! Second, I had a question about the following example below [here](https://docs.microsoft.com/en-us/javascript/api/office/office.document?view=word-js-preview#office-office-document-getfileasync-member(1)) about 1/3 of the way down the page:

```
                // If the getFileAsync call succeeded, then
                // result.value will return a valid File Object.
                var myFile = result.value;

```

I checked several times and was unable to access the _**slices**_ without obtaining some metadata first, then iterating through like so:

```
Office.context.document.getFileAsync(
    Office.FileType.Text, { sliceSize: 65536 }, result => {
        if (result.status == "succeeded") {
            const metaData = result.value
            const slices = metaData.sliceCount

            for (let i = 0; i < slices; i++) {
                result.value.getSliceAsync(i, slice => {
                    //...
                })
            }
        }
    }
)
```

To be clear, I am able to access the slices using the above but wanted to clarify what `result.value` is supposed to be. It appears to contain metadata about the number of slices created via `Office.context.document.getFileAsync`. Is that correct? If so, it's possible the documentation should be updated to reflect that. If not, what's a better way to access the document / document slices?

Also, I'm using the newest Office JS dependency from: https://unpkg.com/@microsoft/office-js/dist/office.js.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a80b0c0b-0647-036d-9193-4be6c67edf21
* Version Independent ID: db81f510-204a-d07b-f02f-6b0e83f1f592
* Content: [Office.Document interface - Office Add-ins](https://docs.microsoft.com/en-us/javascript/api/office/office.document?view=word-js-preview#office-office-document-getfileasync-member(1))
* Content Source: [docs/docs-ref-autogen/office/office/office.document.yml](https://github.com/OfficeDev/office-js-docs-reference/blob/live/docs/docs-ref-autogen/office/office/office.document.yml)
* Product: **non-product-specific**
* Technology: **add-ins**
* GitHub Login: @o365devx
* Microsoft Alias: **o365devx**

**Comment by ElizabethSamuel-MSFT** [comment]
@NicomacheanEudaimonia Thanks for the kudos and your question. Can you include as many relevant details about your environment to help us triage your issue?

## Your Environment

* Platform [PC desktop, Mac, iOS, Office on the web]: ______
* Host [Excel, Word, PowerPoint, etc.]: ______
* Office version number: ______
* Operating System: ______
* Browser (if using Office on the web): ______

Thanks.

**Comment by NicomacheanEudaimonia** [comment]
Hi @ElizabethSamuel-MSFT:

- Platform [PC desktop, Mac, iOS, Office on the web]: PC desktop accessing MS Word in the browser
- Host [Excel, Word, PowerPoint, etc.]: Word
- Office version number: 16.0.15331.41004
- Operating System: Windows 10
- Browser (if using Office on the web): Edge Version 102.0.1245.30 (Official build) (64-bit)

Thanks so much!

(PS - I also tried the above on Brave / Chrome but not as extensively)

**Comment by ElizabethSamuel-MSFT** [comment]
@NicomacheanEudaimonia Thanks for this information.

The documentation seems to be correct. The type of result.value is [Office.File](https://docs.microsoft.com/javascript/api/office/office.file) which is noted in the description of the `callback` parameter. The File object provides the members you're using like size, sliceCount, and getSliceAsync.

You can certainly use your approach of using a for loop or another type of loop. The example provided in the documentation is using recursion which is not necessarily a better way but certainly an alternative.

Since there doesn't seem to be any documentation update needed for this, I'll go ahead and close this. But if you have further questions about this, let us know and we can reopen this issue.

Thanks.

**Comment by NicomacheanEudaimonia** [comment]
Thanks, I appreciate the clarification. You are indeed correct: https://docs.microsoft.com/en-us/javascript/api/office/office.file?view=common-js-preview - I was confusing the `var documentFileData = [];` with the `result.value` fype.  The actual file data is sent in the JSON representation a bit later in the code too: (also named `result.value`).

However, I don't think there's a faster way to access the underlying file data (and particularly in non-text format)? Hmm, that was the primary question I was hoping to answer. (And, consider that answered too!) 

Cheers @ElizabethSamuel-MSFT!
