### ISSUE TITLE
Please write some sample code

### ISSUE THREAD

**Issue by AgainSolutions** [OfficeDev/office-js-docs-reference#1344]
I am new to POwerpoint add-in apis and typescript.
If you can please add some code samples it will help understand better

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: de9f748c-ccbe-c242-07d8-2cc6e91e2658
* Version Independent ID: 8821a017-b462-d76b-3022-8d3ba34e8f32
* Content: [PowerPoint.Presentation class - Office Add-ins](https://docs.microsoft.com/en-us/javascript/api/powerpoint/powerpoint.presentation?view=powerpoint-js-preview#powerpoint-powerpoint-presentation-getselectedshapes-member(1))
* Content Source: [docs/docs-ref-autogen/powerpoint/powerpoint/powerpoint.presentation.yml](https://github.com/OfficeDev/office-js-docs-reference/blob/live/docs/docs-ref-autogen/powerpoint/powerpoint/powerpoint.presentation.yml)
* Product: **powerpoint**
* Technology: **add-ins**
* GitHub Login: @o365devx
* Microsoft Alias: **o365devx**

**Comment by bulgariamitko** [comment]
Please go to openAI and write anything you want there in order to see an example code. For more info check this video - https://www.youtube.com/watch?v=yfqXkkdn7eo&feature=youtu.be

**Comment by ElizabethSamuel-MSFT** [comment]
@AgainSolutions Thanks for your interest in Office Add-ins! We appreciate your request for more code samples. We have articles like [Work with shapes using the PowerPoint JavaScript API](https://docs.microsoft.com/office/dev/add-ins/powerpoint/shapes) that may help you in the meantime.

@Rick-Kirkham Can you take a look?

Thanks.

**Comment by Rick-Kirkham** [comment]
We have code samples in [the Script Lab tool](https://docs.microsoft.com/office/dev/add-ins/overview/explore-with-script-lab). Please install it and open it in PowerPoint to see and use these samples. As ElizabethSamuels mentioned, we have conceptual articles that show code samples as well. 

I'll close this issue, but you can still make comments.
