### ISSUE TITLE
Word.NoteItem class not working for me, getting an error -  NotImplemented

### ISSUE THREAD

**Issue by bulgariamitko** [OfficeDev/office-js-docs-reference#1345]
## Article URL
https://docs.microsoft.com/en-us/javascript/api/word/word.noteitem?view=word-js-preview#word-word-noteitem-body-member

## Issue
I am getting an error when trying to use the example code provided in the documentation.
debugInfo: Object
code: "NotImplemented"
message: "NotImplemented"
toString: function toString()
errorLocation: "Body.footnotes"
statement: "var footnotes = body.footnotes;"

## In summary
When trying to use the example code from Microsoft I get an error Body.footnotes Not Implemented.

This is the code I am using
```
// Link to full sample: https://raw.githubusercontent.com/OfficeDev/office-js-snippets/prod/samples/word/50-document/manage-footnotes.yaml
await Word.run(async (context) => {
  const footnotes = context.document.body.footnotes;
  footnotes.load("items/body");
  await context.sync();

  const referenceNumber = $("#input-reference").val();
  let mark = (referenceNumber as number) - 1;
  let footnoteBody = footnotes.items[mark].body.getRange();
  footnoteBody.load("text");
  await context.sync();

  console.log(`Text of footnote ${referenceNumber}: ${footnoteBody.text}`);
});
```

**Comment by ElizabethSamuel-MSFT** [comment]
@bulgariamitko Sorry to see that you're facing an issue. Can you share some more information about your environment that may help us debug? Thanks.

## Your Environment

* Platform [PC desktop, Mac, iOS, Office on the web]: ______
* Host [Excel, Word, PowerPoint, etc.]: ______
* Office version number: ______
* Operating System: ______
* Browser (if using Office on the web): ______

Note that, at present, this feature is only available in Word on the web through the [WordApiOnline requirement set](https://docs.microsoft.com/javascript/api/requirement-sets/word/word-api-online-requirement-set?view=word-js-online).

Thanks.

**Comment by bulgariamitko** [comment]
After researching I saw that this is available only for Word on the Web and I am trying to run this on Word 365 on a Windows 11, which will not work. But I have another problem. I can't create a new document in Word on the web. Every time I try to create a document I get this error. 

Something is wrong
Unfortunately, the page cannot be displayed at the moment. Try again in a few minutes.

I tried both from office website and from onedrive website :/

**Comment by ElizabethSamuel-MSFT** [comment]
@bulgariamitko Sorry to hear you're facing an issue with Word itself. Unfortunately, my team can't help with that. You may be able to get help with that issue by reporting it on the [Microsoft Q&A site](https://docs.microsoft.com/answers/products/).

As such, I'll go ahead and close this issue. If you have any further questions about Office Add-in and Office.js, do let us know by creating a new issue.

Thanks again for your interest in Office Add-ins.
