### ISSUE TITLE
Identity API requirement sets incomplete for one-time purchase consumer versions

### ISSUE THREAD

**Issue by ChristianGalla** [OfficeDev/office-js-docs-reference#1347]
I have installed Office Professional Plus 2016 downloaded from [my.visualstudio.com](https://my.visualstudio.com/), installed all updates and I am able to use IdentityAPI 1.3 for Single Sign On in an Outlook Add-In.

Also, during updating, for a short time, Outlook was supporting IdentityAPI 1.2, but not IdentityAPI 1.3.

According to the current documentation, IdentityAPI 1.3 should only be supported by Office 2021 or later.

This may be related to https://github.com/OfficeDev/office-js-docs-pr/issues/3551.

![image](https://user-images.githubusercontent.com/7421161/182613403-5909dd84-a335-4e03-92ea-18df1d35d570.png)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: bc7677ca-d45e-6e76-a9f8-583a4420ab6e
* Version Independent ID: 03a3e7d7-fd99-fc1a-f401-9f8905163e01
* Content: [Identity API requirement sets - Office Add-ins](https://docs.microsoft.com/en-us/javascript/api/requirement-sets/common/identity-api-requirement-sets?view=common-js-preview)
* Content Source: [docs/requirement-sets/common/identity-api-requirement-sets.md](https://github.com/OfficeDev/office-js-docs-reference/blob/live/docs/requirement-sets/common/identity-api-requirement-sets.md)
* Product: **non-product-specific**
* Technology: **add-ins**
* GitHub Login: @o365devx
* Microsoft Alias: **o365devx**

**Comment by ElizabethSamuel-MSFT** [comment]
@ChristianGalla Thanks for asking about this.

@exextoc / @samantharamon: Can you take a look?

Thanks.

**Comment by Rick-Kirkham** [comment]
@samantharamon @exextoc I think the customer is right. This has to do with the distinction between Commercial perpetual license and Consumer perpetual license. We've backported some features to Consumer perpetual that were not backported to Commercial perpetual.  think our requirement set docs, not just IdentityApi, are only accurate for Commercial. 

Please consult with @jargil to confirm or refute this theory. 

If the theory is correct, reassign this to me.

**Comment by samantharamon** [comment]
Thank you, @ChristianGalla and @Rick-Kirkham. Based on my research, I'm also under the impression that the license type distinction is why IdentityAPI 1.3 is usable with the consumer perpetual license for Office 2016. I'm still confirming this internally and will share more once I get an update.

**Comment by ElizabethSamuel-MSFT** [comment]
@ChristianGalla We're working on refining this info. Can you take a look at our [prospective updates](https://github.com/OfficeDev/office-js-docs-reference/pull/1360/files#diff-3fcd364736a026e7c4cd9a41b642228d01dc2391a3f7fc97ec0e293b47341476) and let us know your thoughts?

![image](https://user-images.githubusercontent.com/28541963/192599114-0f9498e1-bd1d-410a-8abb-b52e39cd37b7.png)

Thanks.

**Comment by ElizabethSamuel-MSFT** [comment]
@ChristianGalla We've added info re: Android and iOS. The PR should be merged and published today then this issue will be closed.

If you have any other feedback, do let us know by commenting here or in a new issue.

Thanks.
