### ISSUE TITLE
getCallbackTokenAsync 

### ISSUE THREAD

**Issue by agelenava** [OfficeDev/office-js-docs-reference#1365]
On the page it's noted 

> It is recommended that add-ins use the REST APIs instead of Exchange Web Services whenever possible.

At the same time here https://docs.microsoft.com/en-us/previous-versions/office/office-365-api/api/version-2.0/mail-rest-operations it's saying 

> Version 2.0 of the Outlook REST API will be fully decommissioned in November 2022

So,
1) What I should actually use  whenever possible?
2) If I request EWS token in MS Outlook for mobile (iOS, Android), will it return EWS token or it will always return REST token instead, no matter what I requested (isRest = true or false)?

thanks in advance

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0198c212-5e3c-92f4-9f93-96cbe7087ae5
* Version Independent ID: fe7e0914-4be1-1b8c-d173-6a3329caf82e
* Content: [Office.Mailbox interface - Office Add-ins](https://docs.microsoft.com/en-us/javascript/api/outlook/office.mailbox?view=outlook-js-1.5&preserve-view=true#outlook-office-mailbox-getcallbacktokenasync-member(1))
* Content Source: [docs/docs-ref-autogen/outlook_1_5/outlook/office.mailbox.yml](https://github.com/OfficeDev/office-js-docs-reference/blob/live/docs/docs-ref-autogen/outlook_1_5/outlook/office.mailbox.yml)
* Product: **outlook**
* Technology: **add-ins**
* GitHub Login: @o365devx
* Microsoft Alias: **o365devx**

**Comment by AlexJerabek** [comment]
Thanks for raising this issue @agelenava.

@samantharamon, could you please investigate?

**Comment by samantharamon** [comment]
Hi, @agelenava. Thanks for reaching out. Although Outlook REST endpoints will be decommissioned on November 30, 2022, please be advised that all active add-ins that use the REST service will be granted an exemption to keep using the service until extended support ends for Outlook 2019 on October 14, 2025. This includes new add-ins that are developed after the decommission date in November. This update was announced in [this month's Office Add-ins community call](https://www.youtube.com/watch?v=KxaE0SLk-lM) (we're currently updating our guidance in [Use the Outlook REST APIs from an Outlook add-in](https://docs.microsoft.com/office/dev/add-ins/outlook/use-rest-api) with this update). There were some mobile-related questions that were raised during the call that may interest you. Additional questions raised by the community during the call will be answered in a blog post and a link will be posted to [Microsoft Office Add-ins community call](https://docs.microsoft.com/office/dev/add-ins/overview/office-add-ins-community-call?branch=pr-en-us-3588), so watch out for that, too.

For your second question, Outlook on iOS and Android only support REST, so calling `getCallbackTokenAsync` will return a REST token (see [Add-ins for Outlook Mobile](https://docs.microsoft.com/office/dev/add-ins/outlook/outlook-mobile-addins) for additional information).

**Comment by agelenava** [comment]
@samantharamon thank you for you explanation!
