### ISSUE TITLE
<FunctionFile /> missing explanation of resid parameter

### ISSUE THREAD

**Issue by timothyhoffmann** [OfficeDev/office-js-docs-reference#1372]
[Enter feedback here]
 \<FunctionFile resid="residDesktopFuncUrl" /\>

What are the legal values for 'residDesktopFuncUrl'?  Is it a \<url/\> tag?
e.g.
```
<bt:Url id="residDesktopFuncUrl" DefaultValue="https://localhost:3000/test.js" />
```

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5dd4a1bc-131e-f0ae-1824-0f8b8dc66adc
* Version Independent ID: 47159292-a2de-eb39-349a-c917d87762bf
* Content: [FunctionFile element in the manifest file - Office Add-ins](https://docs.microsoft.com/en-us/javascript/api/manifest/functionfile?view=excel-js-preview)
* Content Source: [docs/manifest/functionfile.md](https://github.com/OfficeDev/office-js-docs-reference/blob/live/docs/manifest/functionfile.md)
* Product: **non-product-specific**
* Technology: **add-ins**
* GitHub Login: @o365devx
* Microsoft Alias: **o365devx**

**Comment by AlexJerabek** [comment]
HI @timothyhoffmann,

Thank you for raising this question. @samantharamon, could you please investigate?

**Comment by samantharamon** [comment]
Hi @timothyhoffmann,

The `resid` attribute in the FunctionFile element (in this case, `residDesktopFuncUrl`) must be the value provided in the `id` attribute of a \<Url\> element, which is located in the \<Resources\> element. Expounding your example:

```xml
<DesktopFormFactor>
  <FunctionFile resid="residDesktopFuncUrl" />
  <ExtensionPoint xsi:type="PrimaryCommandSurface">
    <!-- information about this extension point -->
  </ExtensionPoint>
</DesktopFormFactor>

...

<Resources>
   <bt: Urls>
     <bt:Url id="residDesktopFuncUrl" DefaultValue="https://localhost:3000/test.js" />
  </bt: Urls>
</Resources>
```

The `resid` value must be no more than 32 characters. The value of the \<Url\> element must be an HTTPS URL location with a maximum of 2048 characters (see [Resources element](https://docs.microsoft.com/javascript/api/manifest/resources)).

We'll update our [FunctionFile element page](https://docs.microsoft.com/javascript/api/manifest/functionfile) to clarify this.

**Comment by timothyhoffmann** [comment]
Thank you :-)
