### ISSUE TITLE
Code sample is wrong, confusion between use cases/APIs should be avoided.

### ISSUE THREAD

**Issue by art-ist** [OfficeDev/office-js-docs-reference#1382]
- the only complete code sample is obsolete
- the only complete code sample is wring

There are two use cases called SSO with Office add-ins:
- add-In calls Microsoft Graph
- add-In calls middle tier API calling Microsoft Graph

Because of that and due to the fact, that both scenarios require a a different access token to be acquired and passed on, can cause quite some confusion. 

It would be extremely useful to cross reference code samples and documentation for those two things. And a code sample for the call that is NOT deprecated would be helpful.

I suggest adding something like 

```js
let onBehalfOfAccessoken = await Office.auth.getAccessToken({
          allowSignInPrompt: true,
          allowConsentPrompt: true,
          forMSGraphAccess: true,
      });
```
of
```js
let onBehalfOfAccessoken = await Office.auth.getAccessToken();
```

Unfortunately the only code sample provided is wrong and just adding to the confusion between `Office.auth.getAccessToken` and `Office.context.mailbox.getCallbackTokenAsync`.
Please change (delete the wrong "context")
```js
Office.context.auth.getAccessTokenAsync(function(result) {
    if (result.status === "succeeded") {
        const token = result.value;
        // ...
    } else {
        console.log("Error obtaining token", result.error);
    }
});
```
to
```js
Office.auth.getAccessTokenAsync(function(result) {
    if (result.status === "succeeded") {
        const token = result.value;
        // ...
    } else {
        console.log("Error obtaining token", result.error);
    }
});
``` 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 346ab1b7-cc66-fbcf-fba4-8c4099e8906b
* Version Independent ID: b55c4769-cba0-3760-78a5-0fe2e8b968bb
* Content: [Office.Auth interface - Office Add-ins](https://docs.microsoft.com/en-us/javascript/api/office/office.auth?view=outlook-js-1.11)
* Content Source: [docs/docs-ref-autogen/office_release/office/office.auth.yml](https://github.com/OfficeDev/office-js-docs-reference/blob/live/docs/docs-ref-autogen/office_release/office/office.auth.yml)
* Product: **non-product-specific**
* Technology: **add-ins**
* GitHub Login: @o365devx
* Microsoft Alias: **o365devx**

**Comment by AlexJerabek** [comment]
Thanks for raising this issue @art-ist.

@davidchesnut, could you please take a look?

**Comment by davidchesnut** [comment]
Thanks @art-ist! I'm submitting a PR to update this article as you have suggested.

**Comment by davidchesnut** [comment]
PR merged.
