### ISSUE TITLE
Powerpoint API - table Class

### ISSUE THREAD

**Issue by schneiderben** [OfficeDev/office-js-docs-reference#1403]
Hey, 
I have a project where I need to do text replacements in tables in powerpoint.
The table class is not yet surported in the Powerpoint API 1.4. 
is there a timeline by when the table class will be included?
Is there a another way to do text replacements in tabels?

Thanks for your feedback.

Regards, Benedikt

---
#### Dokumentdetails

⚠ *Bearbeiten Sie diesen Abschnitt nicht. Er ist für die Verknüpfung von docs.microsoft.com zum GitHub-Artikel erforderlich.*

* ID: 32001c00-4a17-7ead-a1f2-e0eb7fa41946
* Version Independent ID: 1833f228-7f42-0ad7-d2fc-c917826881be
* Content: [PowerPoint JavaScript preview APIs - Office Add-ins](https://learn.microsoft.com/de-de/javascript/api/requirement-sets/powerpoint/powerpoint-preview-apis?view=excel-js-preview)
* Content Source: [docs/requirement-sets/powerpoint/powerpoint-preview-apis.md](https://github.com/OfficeDev/office-js-docs-reference/blob/live/docs/requirement-sets/powerpoint/powerpoint-preview-apis.md)
* Product: **powerpoint**
* Technology: **add-ins**
* GitHub Login: @o365devx
* Microsoft Alias: **o365devx**

**Comment by AlexJerabek** [comment]
Hi @schneiderben,

Thanks for raising this issue. There is currently no timeline for table support in the PowerPoint APIs. Please submit or feature request (or upvote an existing request) over on our [Tech Community page](https://techcommunity.microsoft.com/t5/microsoft-365-developer-platform/idb-p/Microsoft365DeveloperPlatform).

As for your question if there's an alternative way to achieve this result, let me tag @Rick-Kirkham.

**Comment by Rick-Kirkham** [comment]
I can't think of any way of doing this currently. There's no programmatic support for searching in PowerPoint at this time and there's no way to get a reference to a cell of a table.

**Comment by schneiderben** [comment]
Okay, thanks a lot for your feedback!
