### ISSUE TITLE
 Boolean;

### ISSUE THREAD

**Issue by alshunaef** [OfficeDev/office-js-docs-reference#1484]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 4600bac1-6b0e-ad5c-cfdf-766447015e13
* Version Independent ID: 4cea3b4f-86ef-fafa-319c-a648c6078e95
* Content: [PowerPoint.Interfaces.BulletFormatData interface - Office Add-ins](https://learn.microsoft.com/en-us/javascript/api/powerpoint/powerpoint.interfaces.bulletformatdata?view=powerpoint-js-preview)
* Content Source: [docs/docs-ref-autogen/powerpoint/powerpoint/powerpoint.interfaces.bulletformatdata.yml](https://github.com/OfficeDev/office-js-docs-reference/blob/live/docs/docs-ref-autogen/powerpoint/powerpoint/powerpoint.interfaces.bulletformatdata.yml)
* Product: **powerpoint**
* Technology: **add-ins**
* GitHub Login: @o365devx
* Microsoft Alias: **o365devx**

**Comment by AlexJerabek** [comment]
Hi @alshunaef,

It's unclear the issue you're trying to raise here without a description. Please reopen the thread with some details and we can help you.
