### ISSUE TITLE
getItem by key is not case insensitive

### ISSUE THREAD

**Issue by theboyknowsclass** [OfficeDev/office-js-docs-reference#1510]
feels like they should all be case insensitive, or this should be noted

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 04587160-8623-2572-971e-8c1f1def920b
* Version Independent ID: 531809cf-a2db-9560-9a71-259993e8d8c0
* Content: [PowerPoint.TagCollection class - Office Add-ins](https://learn.microsoft.com/en-us/javascript/api/powerpoint/powerpoint.tagcollection?view=powerpoint-js-preview)
* Content Source: [docs/docs-ref-autogen/powerpoint/powerpoint/powerpoint.tagcollection.yml](https://github.com/OfficeDev/office-js-docs-reference/blob/live/docs/docs-ref-autogen/powerpoint/powerpoint/powerpoint.tagcollection.yml)
* Product: **powerpoint**
* Technology: **add-ins**
* GitHub Login: @o365devx
* Microsoft Alias: **o365devx**

**Comment by ElizabethSamuel-MSFT** [comment]
@theboyknowsclass Thanks for raising this.

@alison-mk Are you the right person to take a look at this?

Thanks.

**Comment by alison-mk** [comment]
Yes! @theboyknowsclass Thanks for the feedback. I'll document this nuance. I'll leave this issue open until I update the documentation, and alert you when I do. 

Cheers, 
Alison

**Comment by theboyknowsclass** [comment]
it might be better for this to be raised as a change to the actual functionality, so this is automatically raised to Upper Case... as that is how the Add function works

**Comment by alison-mk** [comment]
Hi @theboyknowsclass, thank you for the feedback. I've incorporated the documentation update into a PR. It will appear in the reference documentation after going through review and our docs generation process. We'll close this issue after the PR is merged.

Changing the functionality will require a feature request, which we don't track in GitHub. If you'd like to make a feature request, we recommend submitting via [UserVoice](https://officespdev.uservoice.com/). We use UserVoice to prioritize community requests for addition to the product. If the community also needs the feature and upvotes your request, it'll be more likely to be added to the add-ins platform.

Thanks again, 
Alison

**Comment by alison-mk** [comment]
DefinitelyTyped and [reference docs](https://github.com/OfficeDev/office-js-docs-reference/pull/1539) PRs have been merged. Update will be live soon.
