### ISSUE TITLE
CustomProperties vs CustomXmlPart vs Settings

### ISSUE THREAD

**Issue by theboyknowsclass** [OfficeDev/office-js-docs-reference#1511]
Is there any guidance on the differences between these items?  and when and how each should be used?

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 67a00cb7-fcdc-92e3-f9b7-7a05ba129c3f
* Version Independent ID: 2940d860-4dec-0f90-80b8-55d1b7a2e3e1
* Content: [Word.CustomProperty class - Office Add-ins](https://learn.microsoft.com/en-us/javascript/api/word/word.customproperty?view=word-js-preview)
* Content Source: [docs/docs-ref-autogen/word/word/word.customproperty.yml](https://github.com/OfficeDev/office-js-docs-reference/blob/live/docs/docs-ref-autogen/word/word/word.customproperty.yml)
* Product: **word**
* Technology: **add-ins**
* GitHub Login: @o365devx
* Microsoft Alias: **o365devx**

**Comment by ElizabethSamuel-MSFT** [comment]
@theboyknowsclass Thanks for asking about this.

Can you take a look at the following article and see if that helps?

- [Persist add-in state and settings](https://learn.microsoft.com/office/dev/add-ins/develop/persisting-add-in-state-and-settings?view=word-js-preview)

It looks like we'll need to update the article to include information about the Word-specific CustomXmlPart and CustomProperty objects so I'll add that to the backlog.

Thanks.

**Comment by theboyknowsclass** [comment]
also under customXml parts (excel) it states "There is an additional storage option when you need to store information that exceeds the size limits of the document Settings " - i can't find the size limits documented anywhere?

**Comment by ElizabethSamuel-MSFT** [comment]
@theboyknowsclass Thanks for pointing that out too.

> also under customXml parts (excel) it states "There is an additional storage option when you need to store information that exceeds the size limits of the document Settings " - i can't find the size limits documented anywhere?

@alison-mk Do you know if this Excel info @theboyknowsclass asks about is documented somewhere?

Thanks.

**Comment by ElizabethSamuel-MSFT** [comment]
@theboyknowsclass The following article provides an idea of general limits, payload sizes, etc. Perhaps @alison-mk can provide more specific info.

[Resource limits and performance optimization](https://learn.microsoft.com/en-us/office/dev/add-ins/concepts/resource-limits-and-performance-optimization)

Thanks.

**Comment by ElizabethSamuel-MSFT** [comment]
@theboyknowsclass We're noting some of the newer objects in the "Persist..." article (see PR https://github.com/OfficeDev/office-js-docs-pr/pull/3977). We welcome your feedback about that update and do let us know if you have any further questions about this.

Thanks.

**Comment by theboyknowsclass** [comment]
thanks @ElizabethSamuel-MSFT i think it would be useful to have more info about *why* you might use customXML parts vs the Settings object.

again, guidelines on any size or performance limitations would be welcome - the general link for "[Resource limits and performance optimization](https://learn.microsoft.com/en-us/office/dev/add-ins/concepts/resource-limits-and-performance-optimization)" you sent above does not contain anything about settings

**Comment by ElizabethSamuel-MSFT** [comment]
@theboyknowsclass Thanks for your feedback.

As for why you would use one or the other, it comes down to the add-in type you're using and which Office applications you want to support as not all the settings/property options are supported everywhere. All things being equal, either option should work as long as you're not looking to store passwords or other sensitive information. We aimed to explain a bit more about how each works in the respective sections about [Settings data](https://learn.microsoft.com/en-us/office/dev/add-ins/develop/persisting-add-in-state-and-settings#settings-data-is-managed-in-memory-at-runtime) and [Custom XML Parts](https://learn.microsoft.com/en-us/office/dev/add-ins/develop/persisting-add-in-state-and-settings#how-to-save-custom-xml-to-the-document). As you noted earlier, the article mentions, "There is an additional storage option when you need to store information that exceeds the size limits of the document Settings or which has a structured character." regarding the Custom XML Parts option. We'll reach out to the product team about the Settings size limits so readers can make a more informed decision in that regard.

**Comment by ElizabethSamuel-MSFT** [comment]
@theboyknowsclass There's also a difference in access. For Settings, only the add-in that created a setting on the document can access it. For Custom XML parts, any add-in can access existing parts found in the document.

We're still working on getting the size limits information.

Thanks.

**Comment by ElizabethSamuel-MSFT** [comment]
@theboyknowsclass The team has expressed that there are no Settings size limits. Therefore, we updated the article to remove any such reference. I'll go ahead and close this issue.

If you have any further questions about this or any other issue, let us know.

Thanks.
