### ISSUE TITLE
How best to implement SSO on Mobile Outlook?

### ISSUE THREAD

**Issue by glr0221** [OfficeDev/office-js-docs-reference#1606]
As per your documentation, Mobile Outlook does not support Identity API v1.3. How then can we best implement the SSO On-Behalf-Of (for GRAPH APIs) on mobile?

Thanks.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: bc7677ca-d45e-6e76-a9f8-583a4420ab6e
* Version Independent ID: 03a3e7d7-fd99-fc1a-f401-9f8905163e01
* Content: [Identity API requirement sets - Office Add-ins](https://learn.microsoft.com/en-us/javascript/api/requirement-sets/common/identity-api-requirement-sets?view=powerpoint-js-preview)
* Content Source: [docs/requirement-sets/common/identity-api-requirement-sets.md](https://github.com/OfficeDev/office-js-docs-reference/blob/live/docs/requirement-sets/common/identity-api-requirement-sets.md)
* Service: **microsoft-365**
* Sub-service: **add-ins**
* GitHub Login: @o365devx
* Microsoft Alias: **o365devx**

**Comment by Rick-Kirkham** [comment]
@glr0221 We use the Issues in this repo to track problems with the documentation. Programming "how to" questions like this are best raised on StackOverflow or https://learn.microsoft.com/en-us/answers/questions/. I'll close this issue for now, but you can still make comments and we'll see them.
