### ISSUE TITLE
Missing documentation for the Bibliography

### ISSUE THREAD

**Issue by Asguho** [OfficeDev/office-js-docs-reference#1607]
how can i add a source just like https://learn.microsoft.com/en-us/dotnet/api/microsoft.office.tools.word.documentbase.bibliography but in js?

**Comment by Rick-Kirkham** [comment]
@ElizabethSamuel-MSFT  Can you please take a look. (I suspect we don't have a JS API equivalent yet.)

**Comment by ElizabethSamuel-MSFT** [comment]
@Asguho, as @Rick-Kirkham noted, there isn't a JS equivalent. So far, the Bibliography field type is supported (see the [FieldType enum](https://learn.microsoft.com/javascript/api/word/word.fieldtype?view=word-js-1.5)).

Closing this as an associated Bibliography object isn't yet available through Word JS API.
