### ISSUE TITLE
OfficeTab element to be used with a custom tab defined by add-ins

### ISSUE THREAD

**Issue by macabacus-as** [OfficeDev/office-js-docs-reference#1646]
[This page](https://learn.microsoft.com/en-us/javascript/api/manifest/officetab?view=excel-js-preview) says that the OfficeTab element can be used to define the ribbon tab on which the add-in commands appear. 
> This can either be a built-in Office tab or a custom tab defined by the add-in. 

It looks like a mistype because there is a CustomTab element to define a custom tab for add-in controls. But I'm looking to see if there is a way to put the Office.js add-in ribbon controls into the tab defined by another add-in version, so if this is not a mistype it would be great to hear how to use OfficeTab element with _a custom tab_ (CustomTab element always creates a new ribbon tab, even if `id` attribute matches other ribbon tab id).

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: a06c4877-0426-de8d-32fc-624ce6e9ef7a
* Version Independent ID: d55a735b-affe-7806-6c72-14dc4404dfc5
* Content: [OfficeTab element in the manifest file - Office Add-ins](https://learn.microsoft.com/en-us/javascript/api/manifest/officetab?view=excel-js-preview)
* Content Source: [docs/manifest/officetab.md](https://github.com/OfficeDev/office-js-docs-reference/blob/live/docs/manifest/officetab.md)
* Service: **microsoft-365**
* Sub-service: **add-ins**
* GitHub Login: @o365devx
* Microsoft Alias: **o365devx**

**Comment by Rick-Kirkham** [comment]
@macabacus-as The documentation has an error. The first paragraph should read:

Defines the built-in Office ribbon tab on which your add-in command appears. If you want the add-in command to appear on a custom tab of your own, use the CustomTab element.

I will get the article corrected.
