### ISSUE TITLE
 Clarify Word API 1.1 Compatibility for Central Deployment

### ISSUE THREAD

**Issue by SAgnihotri200895** [OfficeDev/office-js-docs-reference#1655]
## Article URL
https://learn.microsoft.com/en-us/javascript/api/requirement-sets/word/word-api-requirement-sets?view=word-js-preview#requirement-set-availability 

## Issue

The article says Word App 1.1 is supported on iPad with word app 1.18 but it doesn't tell about what type of deployment is supported for word add-ins to work on iPad . As per below issue raised, the centrally deployed add-ins aren't supported for iPad, it should be clearly mentioned, so that users can make informed decisions about which path to go forward.

[Link to git hub issue](https://github.com/OfficeDev/office-js/issues/3559#event-10006926554)

**Comment by AlexJerabek** [comment]
Hi @SAgnihotri200895,
 
Thanks for raising this issue. We can investigate how to make this limitation clearer in the [publishing documentation](https://learn.microsoft.com/en-us/office/dev/add-ins/publish/publish). @ElizabethSamuel-MSFT, could you please look into that?

**Comment by ElizabethSamuel-MSFT** [comment]
@SAgnihotri200895 Thanks for letting us know. We're making some updates to indicate that readers should look at the available deployment options since the selected method could affect add-in availability. This update should be published this week.

Thanks again for your interest in Office Add-ins!
