### ISSUE TITLE
Colors in the docs don't match

### ISSUE THREAD

**Issue by sebammon** [OfficeDev/office-js-docs-reference#1656]
The colors in the docs don't match the colors actually used in Outlook.

For example: in the docs green is said to be `Preset4`, however the actual preset for the color green in outlook is `Preset24`.
See the screenshot below. The categories are the default categories specified by Outlook.

I'm running Outlook for mac OS version: 16.75.2.

Screenshot:
![image (1)](https://github.com/OfficeDev/office-js-docs-reference/assets/50615191/09411e19-84b5-4348-a4de-b24b139c5540)
---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: eb5a711e-6684-2a5b-cfd9-3e1f0b67408a
* Version Independent ID: a75e26b7-ce18-07b2-2c47-6cd82d49bc15
* Content: [Office.MailboxEnums.CategoryColor enum - Office Add-ins](https://learn.microsoft.com/en-us/javascript/api/outlook/office.mailboxenums.categorycolor?view=outlook-js-preview)
* Content Source: [docs/docs-ref-autogen/outlook/outlook/office.mailboxenums.categorycolor.yml](https://github.com/OfficeDev/office-js-docs-reference/blob/live/docs/docs-ref-autogen/outlook/outlook/office.mailboxenums.categorycolor.yml)
* Service: **outlook**
* Sub-service: **add-ins**
* GitHub Login: @o365devx
* Microsoft Alias: **o365devx**

**Comment by AlexJerabek** [comment]
Hi @sebammon,

Thanks for creating this issue. There is a note at the top of the page that says, 
> Note: The actual color depends on how the Outlook client renders it. In this case, the colors noted on each preset are for the Outlook desktop client.

Let me assign this to @samantharamon to see if we could make that clearer.

**Comment by sebammon** [comment]
Thanks for the response @AlexJerabek, I most certainly missed that.

Is there any way to set the colors of the categories such that they are consistent between clients? Our CI colors require a green (ideally custom) but a general green will do. It seems a bit nonsensical to have the enums if it is inconsistent between clients.

Do you know to what degree the color presets are consistent between clients?

**Comment by AlexJerabek** [comment]
@exextoc, could you please answer these implementation questions?

**Comment by samantharamon** [comment]
Hi @sebammon,

Thanks for reaching out. I'm following up with the team on category color values in Outlook on Mac. I can confirm that the list we currently have documented applies to Outlook on Windows and on the web.

**Comment by samantharamon** [comment]
Thanks for your patience, @sebammon. The team has now fixed this bug. The colors listed in [Office.MailboxEnums.CategoryColor](https://learn.microsoft.com/javascript/api/outlook/office.mailboxenums.categorycolor) will apply to Outlook on Mac starting in Version 16.78. The PR for the doc update is currently in review. This issue will automatically close once the PR is closed, however, please don't hesitate to reach out if you need additional assistance.
