### ISSUE TITLE
Missing information about using Visio JS API with "any external web page"

### ISSUE THREAD

**Issue by MichaelPolla** [OfficeDev/office-js-docs-reference#168]
Hi,

At the end of the [Visio JavaScript APIs announcement](https://developer.microsoft.com/en-us/office/blogs/visio-javascript-apis-preview/) it states: 

> Custom solutions that you implement via the Visio JavaScript APIs will work against embedded Visio diagrams in SharePoint Online **or any external web page**.

However all the documentation I've found is only about embedding Visio diagrams into a SharePoint website.

So : 
- Was the functionality of working with any external web page never implemented ?
or
- The corresponding information is missing ?
or 
- I've misunderstood the blog post and "any external web page" refers to some SharePoint external web page or something (I don't know SharePoint well) ?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 42852bf8-54dd-c45f-9a20-4c4cbbb7d8ce
* Version Independent ID: 6ad96000-9527-b58b-c6ae-1ccababa2ec7
* Content: [Visio JavaScript API overview](https://docs.microsoft.com/en-us/javascript/office/overview/visio-javascript-reference-overview?view=office-js)
* Content Source: [docs/docs-ref-conceptual/overview/visio-javascript-reference-overview.md](https://github.com/OfficeDev/office-js-docs-reference/blob/live/docs/docs-ref-conceptual/overview/visio-javascript-reference-overview.md)
* Product: **office 365**
* GitHub Login: @o365devx
* Microsoft Alias: **o365devx**

**Comment by Rick-Kirkham** [comment]
@MichaelPolla  Not yet. I just gave them another poke.

**Comment by lindalu-MSFT** [comment]
Hi, I'm pretty sure this should read "Custom solutions that you implement via the Visio JavaScript APIs will work against embedded Visio diagrams in SharePoint Online or any external **SharePoint modern** web page." This is more clear in this more recent article from support.microsoft.com: [Visio Services in SharePoint Online](https://support.office.com/en-us/article/visio-services-in-sharepoint-online-roadmap-cecad64e-e0c4-49d0-93e0-acdd3709c57c)

**Comment by Rick-Kirkham** [comment]
Pinged Komal Sachdeva.

**Comment by Rick-Kirkham** [comment]
@MichaelPolla I finally got this information. The blog post that you linked to is misleading. You should ignore the phrase "or any external web page". We hope someday to support this, but it is not supported at this time. I have set things in motion to correct the blog post (which is on _developer_.microsoft.com). Since this issues in this repo are for errors in the main Office developer documentation on _docs_.microsoft.com, I will close this issue.

**Comment by MichaelPolla** [comment]
@Rick-Kirkham , thanks for keeping me information even after all this time. I really appreciate it. Best regards.
