### ISSUE TITLE
Grouping shapes from the PowerPoint API

### ISSUE THREAD

**Issue by CaptainTammy** [OfficeDev/office-js-docs-reference#1680]
Hi, we are doing a project where we create a lot of shapes on a slide using the API, and would need to group these so the created object could be seen as one. This would also make it easier to move around for the user.
Is there any plan on supporting grouping from the API?

Is there any good place to see what's coming in the API? 
Currently the PowerPoint preview API is empty and has been for a very long time. 

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 32001c00-4a17-7ead-a1f2-e0eb7fa41946
* Version Independent ID: 1833f228-7f42-0ad7-d2fc-c917826881be
* Content: [PowerPoint JavaScript preview APIs - Office Add-ins](https://learn.microsoft.com/en-gb/javascript/api/requirement-sets/powerpoint/powerpoint-preview-apis?view=powerpoint-js-preview)
* Content Source: [docs/requirement-sets/powerpoint/powerpoint-preview-apis.md](https://github.com/OfficeDev/office-js-docs-reference/blob/live/docs/requirement-sets/powerpoint/powerpoint-preview-apis.md)
* Service: **powerpoint**
* Sub-service: **add-ins**
* GitHub Login: @o365devx
* Microsoft Alias: **o365devx**

**Comment by AlexJerabek** [comment]
Hi @CaptainTammy,

I've forwarded your questions along internally to our PowerPoint API team. In general, the best place for feature requests is the [M365 Developer Platform Tech Community](https://techcommunity.microsoft.com/t5/microsoft-365-developer-platform/idb-p/Microsoft365DeveloperPlatform). There, other developers can upvote features and we can prioritize accordingly.

As for the release of the current wave preview APIs, we avoid committing to specific release dates for preview APIs until we have high certainty they'll make those dates. The [Office Add-ins Community Call](https://learn.microsoft.com/en-us/office/dev/add-ins/overview/office-add-ins-community-call) is a good place to hear about those updates and ask questions of the developers.

**Comment by EsterBergen** [comment]
Hi @CaptainTammy - We've opened an item in the backlog for this (834224) and will update this thread when more information is available.
Thanks!

**Comment by EsterBergen** [comment]
Hi @CaptainTammy - We've released the ability to group shapes in preview recently. Please check here and try it out. Thanks for your patience! https://learn.microsoft.com/en-us/javascript/api/requirement-sets/powerpoint/powerpoint-preview-apis?view=common-js-preview
