### ISSUE TITLE
Word.LineWidth enum

### ISSUE THREAD

**Issue by junaid042** [OfficeDev/office-js-docs-reference#1731]
**Please provide examples**

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 85bf8b54-55bb-4c82-d615-05b6e2dac4fb
* Version Independent ID: e74df0b7-424d-2205-ffbf-42a1c535b9cc
* Content: [Word.BorderWidth enum - Office Add-ins](https://learn.microsoft.com/en-us/javascript/api/word/word.borderwidth?view=word-js-preview)
* Content Source: [docs/docs-ref-autogen/word/word/word.borderwidth.yml](https://github.com/OfficeDev/office-js-docs-reference/blob/live/docs/docs-ref-autogen/word/word/word.borderwidth.yml)
* Service: **word**
* Sub-service: **add-ins**
* GitHub Login: @o365devx
* Microsoft Alias: **o365devx**

**Comment by ElizabethSamuel-MSFT** [comment]
@junaid042 Thanks for raising this. We've put this on our backlog.

Thanks.

**Comment by junaid042** [comment]
@ElizabethSamuel-MSFT can you please provide an example of ([BorderWidth enum](https://learn.microsoft.com/en-us/javascript/api/word/word.borderwidth?view=word-js-preview).)

**Comment by ElizabethSamuel-MSFT** [comment]
@junaid042 BorderWidth is currently being used to set a [Word.Style](https://learn.microsoft.com/javascript/api/word/word.style?view=word-js-preview)'s borders.

For more about setting up and managing a custom style, see the [manage-styles Script Lab code snippet](https://github.com/OfficeDev/office-js-snippets/blob/main/samples/word/50-document/manage-styles.yaml).

The outline could look something like:
1. Create a custom style using [Word.Document.addStyle](https://learn.microsoft.com/javascript/api/word/word.document?view=word-js-preview#word-word-document-addstyle-member(1)) - see addStyle function in manage-styles snippet.
2. Get the style object representing your custom style using [Word.Document.getStyles](https://learn.microsoft.com/javascript/api/word/word.document?view=word-js-preview#word-word-document-getstyles-member(1)).[getByNameOrNullObject](https://learn.microsoft.com/javascript/api/word/word.stylecollection?view=word-js-preview#word-word-stylecollection-getbynameornullobject-member(1)) then apply the style - see applyStyle function in manage-styles snippet.
3. Update the style's border properties using something like:
    ```js
    async function setBorderProperties() {
      // Updates border properties (e.g., type, width, color) of the specified style.
      await Word.run(async (context) => {
        const styleName = $("#style-name").val() as string;
        if (styleName == "") {
          console.warn("Enter a style name to update border properties.");
          return;
        }

        const style = context.document.getStyles().getByNameOrNullObject(styleName);
        style.load();
        await context.sync();

        if (style.isNullObject) {
          console.warn(`There's no existing style with the name '${styleName}'.`);
        } else {
          const borders = style.borders;
          borders.load("items");
          await context.sync();

          console.log(borders);

          borders.outsideBorderType = Word.BorderType.dashed;
          borders.outsideBorderWidth = Word.BorderWidth.pt025;
          borders.outsideBorderColor = "red";
          console.log("Updated outside borders");
        }
      });
    }
    ```

You can also update a border for a specific applicable/available location (e.g., top) by using [Word.BorderCollection.getByLocation](https://learn.microsoft.com/javascript/api/word/word.bordercollection?view=word-js-preview#word-word-bordercollection-getbylocation-member(1)) to get the Border object to update.

Initial borders object:
```json
{
    "insideBorderColor": "#000000",
    "insideBorderType": "None",
    "insideBorderWidth": "None",
    "outsideBorderColor": "#000000",
    "outsideBorderType": "None",
    "outsideBorderWidth": "None",
    "items": [
        {
            "color": "#000000",
            "location": "Top",
            "type": "None",
            "visible": false,
            "width": "None"
        },
        {
            "color": "#000000",
            "location": "Left",
            "type": "None",
            "visible": false,
            "width": "None"
        },
        {
            "color": "#000000",
            "location": "Bottom",
            "type": "None",
            "visible": false,
            "width": "None"
        },
        {
            "color": "#000000",
            "location": "Right",
            "type": "None",
            "visible": false,
            "width": "None"
        },
        {
            "color": "#000000",
            "location": "InsideHorizontal",
            "type": "None",
            "visible": false,
            "width": "None"
        }
    ]
}
```

After updating outside border properties (notice that the color, type, and width properties of the items with location Top, Bottom, Left, and Right have changed):

```json
{
    "insideBorderColor": "#000000",
    "insideBorderType": "None",
    "insideBorderWidth": "None",
    "outsideBorderColor": "red",
    "outsideBorderType": "Dashed",
    "outsideBorderWidth": "Pt025",
    "items": [
        {
            "color": "#FF0000",
            "location": "Top",
            "type": "Dashed",
            "visible": true,
            "width": "Pt025"
        },
        {
            "color": "#FF0000",
            "location": "Left",
            "type": "Dashed",
            "visible": true,
            "width": "Pt025"
        },
        {
            "color": "#FF0000",
            "location": "Bottom",
            "type": "Dashed",
            "visible": true,
            "width": "Pt025"
        },
        {
            "color": "#FF0000",
            "location": "Right",
            "type": "Dashed",
            "visible": true,
            "width": "Pt025"
        },
        {
            "color": "#000000",
            "location": "InsideHorizontal",
            "type": "None",
            "visible": false,
            "width": "None"
        }
    ]
}
```

Hope this helps. I'll go ahead and close this issue but if you need further help with this, just let us know by commenting here so we can reopen it.

Thanks.

**Comment by ElizabethSamuel-MSFT** [comment]
Reopened since we still need to update the manage-styles snippet and include BorderWidth example.
