### ISSUE TITLE
how to remove ListBullet 

### ISSUE THREAD

**Issue by junaid042** [OfficeDev/office-js-docs-reference#1732]
**I want to remove ListBullet if ListBullet already added. but not succeed please help me **  @alison-mk 

`       

    
        async function bullet() {
            await Word.run(async (context) => {
                const Nrange = context.document.getSelection();
                const paragraphs = Nrange.paragraphs;
                paragraphs.load("$none");
                await context.sync();
                // Use the first paragraph to start a new list.
                const list = paragraphs.items[0].startNewList();

                list.setLevelBullet(0, Word.ListBullet.solid);

               list.load("levelTypes");

                await context.sync();
            });
        }
 `

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 7d9bb2e0-38aa-f0ba-f983-6007ead49bcb
* Version Independent ID: 6563aede-8521-fbfb-ac13-77226eed0637
* Content: [Word.ListBullet enum - Office Add-ins](https://learn.microsoft.com/en-us/javascript/api/word/word.listbullet?view=word-js-preview)
* Content Source: [docs/docs-ref-autogen/word/word/word.listbullet.yml](https://github.com/OfficeDev/office-js-docs-reference/blob/live/docs/docs-ref-autogen/word/word/word.listbullet.yml)
* Service: **word**
* Sub-service: **add-ins**
* GitHub Login: @o365devx
* Microsoft Alias: **o365devx**

**Comment by junaid042** [comment]
@alison-mk

**Comment by alison-mk** [comment]
Hi @junaid042, thank you for submitting this issue. I've assigned it to @ElizabethSamuel-MSFT. Elizabeth covers our Word add-ins and should be able to provide more information about your question.

Cheers,
Alison

**Comment by junaid042** [comment]
thanks you @alison-mk .

**Comment by junaid042** [comment]
@ElizabethSamuel-MSFT please help if are available.
I want toogle  ListBullet like word functionality from my add-in.

**Comment by ElizabethSamuel-MSFT** [comment]
@junaid042 To remove the bullet/number without deleting the paragraph, you should be able to use [Word.Paragraph.detachFromList()](https://learn.microsoft.com/javascript/api/word/word.paragraph?view=word-js-preview#word-word-paragraph-detachfromlist-member(1)). It should keep the same level of indentation.

Hope this helps. I'll go ahead and close this issue. However, if it isn't quite what you're looking for, let us know so we can reopen and investigate further.

Thanks.

**Comment by junaid042** [comment]
Thanks @ElizabethSamuel-MSFT and @alison-mk .
