### ISSUE TITLE
Delete the entire row of table in word

### ISSUE THREAD

**Issue by junaid042** [OfficeDev/office-js-docs-reference#1742]
Please provide an example of Deletes the entire row in JS. I mean how can I delete a table row where my cursor is clicked. **I Want if my cursor is clicked in a table row cell delete that row.**

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 2be06481-cf1c-5756-3dc6-9e50a7a66080
* Version Independent ID: 307d39d0-4707-4a7d-ce62-e10dffc213ea
* Content: [Word.TableRow class - Office Add-ins](https://learn.microsoft.com/en-us/javascript/api/word/word.tablerow?view=word-js-preview)
* Content Source: [docs/docs-ref-autogen/word/word/word.tablerow.yml](https://github.com/OfficeDev/office-js-docs-reference/blob/live/docs/docs-ref-autogen/word/word/word.tablerow.yml)
* Service: **word**
* Sub-service: **add-ins**
* GitHub Login: @o365devx
* Microsoft Alias: **o365devx**

**Comment by ElizabethSamuel-MSFT** [comment]
@junaid042 Thanks for asking about this.

You may need to do some chaining here.

[Word.Document.getSelection()](https://learn.microsoft.com/javascript/api/word/word.document?view=word-js-preview#word-word-document-getselection-member(1)) gives you a Range object. You can then use [Range.parentTableCellOrNullObject](https://learn.microsoft.com/javascript/api/word/word.range?view=word-js-preview#word-word-range-parenttablecellornullobject-member) to get the table cell. From that you can get the parent row using [TableCell.parentRow](https://learn.microsoft.com/javascript/api/word/word.tablecell?view=word-js-preview#word-word-tablecell-parentrow-member). Now you have the table row and should be able to use [TableRow.delete()](https://learn.microsoft.com/javascript/api/word/word.tablerow?view=word-js-preview#word-word-tablerow-delete-member(1)). Something like the following:

```js
const selection = context.document.getSelection();
const parentCell = selection.parentTableCellOrNullObject;
const parentRow = parentCell.parentRow;
parentRow.delete();
```

Make sure to include any appropriate `await context.sync();` statements.

Let us know if this helps.

Thanks.

**Comment by junaid042** [comment]
thanks @ElizabethSamuel-MSFT 🤞

**Comment by junaid042** [comment]
can you @ElizabethSamuel-MSFT  help me I want to delete `entire row` and its bottom side all row in table. **I mean delete entire row and after entire row all rows.**

**Comment by junaid042** [comment]
`   
         
       await Word.run(async (context) => {
         const selection = context.document.getSelection();
         selection.load('parentTableCellOrNullObject');
         await context.sync();

       if (!selection.isNull && !selection.parentTableCellOrNullObject.isNull) {
           const parentCell = selection.parentTableCellOrNullObject;
           const parentTable = parentCell.parentTable;
           const rows = parentTable.rows;

           rows.load('items');
           await context.sync();
           //var rowIndex = 1;
           var rowIndex = deleterowindex;
           if (rows.items.length > rowIndex) {
               for (let i = rows.items.length - 1; i >= rowIndex; i--) {
                   const row = rows.items[i];
                   row.delete();
               }

               await context.sync();
               console.log(`Rows from index ${rowIndex} onwards deleted successfully.`);
           } else {
               console.log('Row index is out of range.');
           }
       } else {
           console.log('Selection is not inside a table cell.');
       }
     });
    `
