### ISSUE TITLE
how to check my table is inside a table cell

### ISSUE THREAD

**Issue by junaid042** [OfficeDev/office-js-docs-reference#1747]
I want to check my cursor is inside a table cell and this table is inside another table or not

using this I am only checking my cursor is inside a table or not
`

      await Word.run(async (context) => {
         const range = context.document.getSelection();
         range.load('parentTableOrNullObject');

         await context.sync();

        if (!range.parentTableOrNullObject.isNullObject) {
         console.log('Cursor is inside a table.');
        } else {
          console.log('Cursor is not inside a table.');
       }
    }); 
`

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: f89f09d9-80a1-a9b1-e2f5-8f4d38038954
* Version Independent ID: 3f08e1cb-3d91-e8d6-7fc7-ffc887bdaf4e
* Content: [Word.Table class - Office Add-ins](https://learn.microsoft.com/en-us/javascript/api/word/word.table?view=word-js-preview)
* Content Source: [docs/docs-ref-autogen/word/word/word.table.yml](https://github.com/OfficeDev/office-js-docs-reference/blob/live/docs/docs-ref-autogen/word/word/word.table.yml)
* Service: **word**
* Sub-service: **add-ins**
* GitHub Login: @o365devx
* Microsoft Alias: **o365devx**

**Comment by ElizabethSamuel-MSFT** [comment]
@junaid042 Thanks for asking about this. I'll take a look.

**Comment by ElizabethSamuel-MSFT** [comment]
@junaid042 Thanks for your patience.

Word.Table has a [parentTableCellOrNullObject](https://learn.microsoft.com/javascript/api/word/word.table#word-word-table-parenttablecellornullobject-member) property that you should be able to load and check. So, in your sample, you've checked if the selected range is within a table. Now you can check if that table is in a table cell.

Hope that helps.

I'll go ahead and close this. But if this doesn't quite solve your issue, let us know so we can reopen it.

Thanks.

**Comment by junaid042** [comment]
thanks @ElizabethSamuel-MSFT

**Comment by ElizabethSamuel-MSFT** [comment]
Similarly, you can get the parent table of the current location. Then get the parentTable of that table. In both cases, you should be able to use [Word.Table.parentTableOrNullObject](https://learn.microsoft.com/javascript/api/word/word.table?view=word-js-preview#word-word-table-parenttableornullobject-member) to get that info.
