### ISSUE TITLE
Office.context.mailbox.addHandlerAsync usage?

### ISSUE THREAD

**Issue by butchmarshall** [OfficeDev/office-js-docs-reference#176]
I wish for my add-in to be notified when a message being composed in the outlook web app changes (recipients, message body, subject etc.).

I am unable to get events from `Office.context.mailbox.addHandlerAsync`.  Am I using it correctly?

None of these seem to work.

```
Office.context.mailbox.addHandlerAsync(Office.EventType.ItemChanged, function(result) {
	console.log(result);
});
```
```
Office.context.mailbox.addHandlerAsync(Office.EventType.ItemChanged, function(result) {
	console.log(result);
}, { asyncContext: true },function(result) {
	console.log(result);
});
```
```
Office.context.mailbox.addHandlerAsync(Office.EventType.ItemChanged,
	function (eventArgs) {
		console.log(eventArgs);
	},
	function (result) {
		console.log(result);
	}
);
```
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: afd9eea6-32de-c10a-f0fc-ac6a2e234da5
* Version Independent ID: 8dca85eb-1a29-527b-c82f-7a05b293193f
* Content: [mailbox](https://docs.microsoft.com/en-us/javascript/office/objectmodel/requirement-set-1.6/office.context.mailbox?view=office-js)
* Content Source: [docs/docs-ref-conceptual/objectmodel/requirement-set-1.6/office.context.mailbox.md](https://github.com/OfficeDev/office-js-docs-reference/blob/live/docs/docs-ref-conceptual/objectmodel/requirement-set-1.6/office.context.mailbox.md)
* Product: **office 365**
* GitHub Login: @o365devx
* Microsoft Alias: **o365devx**

**Comment by ElizabethSamuel-MSFT** [comment]
@butchmarshall: Thanks for asking about this. `ItemChanged` is triggered when you pin the add-in task pane then switch from viewing one mailbox item to another. I'll try to clarify that point in the documentation. However, unfortunately, we don't have an event that would let you know if *anything* changed on the specific item. There's an [Office.context.mailbox.item.addHandlerAsync](https://docs.microsoft.com/office/dev/add-ins/reference/objectmodel/requirement-set-1.7/office.context.mailbox.item?view=office-js#addhandlerasynceventtype-handler-options-callback) (introduced in req. set 1.7) which accepts events like `RecipientsChanged` and `AppointmentTimeChanged`.

If you would like to see this feature implemented, please suggest it on our [UserVoice](https://officespdev.uservoice.com/forums/224641-feature-requests-and-feedback?category_id=163572) site for consideration.
