### ISSUE TITLE
ออฟฟิศเดฟ

### ISSUE THREAD

**Issue by CIFTum** [OfficeDev/office-js-docs-reference#1760]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: f2a2838b-04e7-78d1-9b3b-7a349639ba98
* Version Independent ID: 1578d31d-6c88-6071-a043-3c85ba0fe6e7
* Content: [Office.MailboxEnums.AttachmentStatus enum - Office Add-ins](https://learn.microsoft.com/en-us/javascript/api/outlook/office.mailboxenums.attachmentstatus?view=outlook-js-preview)
* Content Source: [docs/docs-ref-autogen/outlook/outlook/office.mailboxenums.attachmentstatus.yml](https://github.com/OfficeDev/office-js-docs-reference/blob/live/docs/docs-ref-autogen/outlook/outlook/office.mailboxenums.attachmentstatus.yml)
* Service: **outlook**
* Sub-service: **add-ins**
* GitHub Login: @o365devx
* Microsoft Alias: **o365devx**

**Comment by samantharamon** [comment]
Hi @CIFTum. How can we help you with the documentation you referenced?
