### ISSUE TITLE
how can i check my selection is in side any Bookmark?

### ISSUE THREAD

**Issue by junaid042** [OfficeDev/office-js-docs-reference#1765]
Is there are any way to check my selection is inside any Bookmark [parentContentControlOrNullObject](https://learn.microsoft.com/en-us/javascript/api/word/word.range?view=word-js-preview#word-word-range-parentcontentcontrolornullobject-member) 

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 578c5e3f-8dd7-2e92-3cdc-21c5a378fba7
* Version Independent ID: 366375be-7700-ecc4-0718-9ef9fbd4871b
* Content: [Word.Range class - Office Add-ins](https://learn.microsoft.com/en-us/javascript/api/word/word.range?view=word-js-preview)
* Content Source: [docs/docs-ref-autogen/word/word/word.range.yml](https://github.com/OfficeDev/office-js-docs-reference/blob/live/docs/docs-ref-autogen/word/word/word.range.yml)
* Service: **word**
* Sub-service: **add-ins**
* GitHub Login: @o365devx
* Microsoft Alias: **o365devx**

**Comment by ElizabethSamuel-MSFT** [comment]
@junaid042 Thanks for asking about this.

Can you check if [Range.getBookmarks](https://learn.microsoft.com/javascript/api/word/word.range?view=word-js-preview#word-word-range-getbookmarks-member(1)) works for your scenario?

I'll go ahead and close this issue. But if it doesn't help, let us know so we can reopen the issue and investigate further.

Thanks.

**Comment by junaid042** [comment]
it works thankyou @ElizabethSamuel-MSFT
