### ISSUE TITLE
set method?

### ISSUE THREAD

**Issue by ChemMitch** [OfficeDev/office-js-docs-reference#1779]
More detail for the set() method would be very useful.
What's in the 'properties' parameter?  
A few examples would help.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 3b951fe5-0985-ff2d-d5e5-cb8523c84840
* Version Independent ID: 6cc5351c-a26b-5d83-5b8b-df1b92ff3e3a
* Content: [Excel.Worksheet class - Office Add-ins](https://learn.microsoft.com/en-us/javascript/api/excel/excel.worksheet?view=excel-js-preview#excel-excel-worksheet-set-member(2))
* Content Source: [docs/docs-ref-autogen/excel/excel/excel.worksheet.yml](https://github.com/OfficeDev/office-js-docs-reference/blob/live/docs/docs-ref-autogen/excel/excel/excel.worksheet.yml)
* Service: **excel**
* Sub-service: **add-ins**
* GitHub Login: @o365devx
* Microsoft Alias: **o365devx**

**Comment by AlexJerabek** [comment]
Hi @ChemMitch,

Thank you for requesting a sample. I'll add this to my backlog.

As far as using `set`, all application specific interfaces have `load` and `set` methods to adjust properties of that interface. Each Excel object has a `*UpdateData` object used with `set` ([here's `WorksheetUpdateData`](https://learn.microsoft.com/en-us/javascript/api/excel/excel.interfaces.worksheetupdatedata?view=excel-js-preview), which is what the type of `properties` is). Documentation on using the `set` method can be found here: https://learn.microsoft.com/office/dev/add-ins/develop/application-specific-api-model?view=excel-js-preview#set.

Basically, `set` is a convenience API you can use to set multiple properties, instead of setting them one by one. These two code snippets have the save behavior:

```
  await Excel.run(async (context) => {
    const activeSheet = context.workbook.worksheets.getActiveWorksheet();
    activeSheet.tabColor = "yellow";
    activeSheet.name = "MySheet";

    await context.sync();
  });
```
```
  await Excel.run(async (context) => {
    const activeSheet = context.workbook.worksheets.getActiveWorksheet();
    activeSheet.set({
      tabColor: "yellow",
      name: "MySheet"
    });

    await context.sync();
  });
``` 

Please let me know if you have any other questions.

**Comment by ChemMitch** [comment]
That is a very useful example!  Thank you.

**Comment by ChemMitch** [comment]
@AlexJerabek another question about the Office JS object model.
I'm converting a VSTO add-in to JS.  In the VSTO model, we create cell comments that are intended as _documentation_, showing the user the purpose of a column within a spreadsheet.  This appears to differ from the philosophy of comments with Office JS - as a dialog between users.
The following comment from a sheet created by the VSTO add-in shows what I mean:
![comment_vsto](https://github.com/OfficeDev/office-js-docs-reference/assets/3246349/f12cf975-3be1-46d0-aa83-d517fb323fc7)

In JS
![comment_js](https://github.com/OfficeDev/office-js-docs-reference/assets/3246349/a22464fe-6443-493c-8186-2b6ebf431bef)
the comment 1) includes the user's name which is not relevant here 2) invites replies, which we don't want here.
(I've figured out how to mark a comment as resolved but it still does not look as nice.)

One more thing: in VSTO, we add images to comments.  This is very useful when communicating chemistry within an Excel sheet -- the chemical structure conveys lots information but can be obtrusive.  In a comment, the structure appears when the user hovers over the cell.

Is there a way to do the above within Office JS?

**Comment by AlexJerabek** [comment]
Hi @ChemMitch,

Sadly, I don't believe either scenario you are asking about is supported in the Excel JS APIs today. The cell comments you're looking for are now called "notes". Additionally, images in comments are not supported in the client, as well as the APIs.

I'd recommend two actions to try and add these features to the product. First, create a new issue in the [office-js repo](https://github.com/OfficeDev/office-js) asking for note support. Please describe your scenario, as you have here. Second, give feedback from within Excel about the comment image support (go to **Help > Feedback**). That's the best way funnel feature requests to the main Excel team.

Sorry that this is not the answer you were probably hoping for.

**Comment by ChemMitch** [comment]
Thank you very much, Alex! 
It's useful confirmation that I didn't miss an existing capability.
The request has been created.  (The page mentions the web site https://techcommunity.microsoft.com/ but I assumed you have the latest info.)

**Comment by AlexJerabek** [comment]
You're welcome. Happy to help however I can.

There are a few places to make feature requests and provide feedback. Tech Community works too, but I know how often the Excel API team checks GitHub.

I'll close this PR when the `Worksheet.set` sample gets checked in. If you have any other questions, please let me know.
