### ISSUE TITLE
how can I get all hyperlinks from my word document?

### ISSUE THREAD

**Issue by junaid042** [OfficeDev/office-js-docs-reference#1783]
I need all hyperlinks from my document how can I get ? 
I am trying to hyperlink s from `Range` of full body but got only first one 

this is my code

`     

            async function run() {
             await Word.run(async (context) => {
             const body = context.document.body;
             const bodyRange = context.document.body.getRange();
             bodyRange.load("hyperlink");
            await context.sync();
            console.log(bodyRange.hyperlink)
           });

`

I need all hyperlinks from my word document.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 578c5e3f-8dd7-2e92-3cdc-21c5a378fba7
* Version Independent ID: 366375be-7700-ecc4-0718-9ef9fbd4871b
* Content: [Word.Range class - Office Add-ins](https://learn.microsoft.com/en-us/javascript/api/word/word.range?view=word-js-preview)
* Content Source: [docs/docs-ref-autogen/word/word/word.range.yml](https://github.com/OfficeDev/office-js-docs-reference/blob/live/docs/docs-ref-autogen/word/word/word.range.yml)
* Service: **word**
* Sub-service: **add-ins**
* GitHub Login: @o365devx
* Microsoft Alias: **o365devx**

**Comment by AlexJerabek** [comment]
Hi @junaid042,

The `hyperlink` property on a Range only returns the first hyperlink. Use the `Range.getHyperlinkRanges` method to get the subranges for every hyperlink. Here's a sample that shows how to use that method and log every link in the Word document's body.

```
await Word.run(async (context) => {
    const bodyRange = context.document.body.getRange(Word.RangeLocation.whole);
    const hyperLinks = bodyRange.getHyperlinkRanges();
    hyperLinks.load("hyperlink");
    await context.sync();
    hyperLinks.items.forEach((linkRange) => {
      console.log(linkRange.hyperlink);
    });
  });
``` 

I'm going to add this sample to the reference documentation. I'll close the PR when that happens, unless you have further questions.

**Comment by junaid042** [comment]
@AlexJerabek thanks You very much, I have not further question.
