### ISSUE TITLE
Office.Auth is broken link

### ISSUE THREAD

**Issue by mafut** [OfficeDev/office-js-docs-reference#179]
In IdentityAPI 1.1 "Office.Auth" link is broken

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4e8708f6-d57e-a17f-7665-b791d66af97e
* Version Independent ID: cafbd543-dc87-43b8-421e-0d044e3cc713
* Content: [Identity API requirement sets](https://docs.microsoft.com/en-us/javascript/office/requirement-sets/identity-api-requirement-sets?view=office-js#feedback)
* Content Source: [docs/docs-ref-conceptual/requirement-sets/identity-api-requirement-sets.md](https://github.com/OfficeDev/office-js-docs-reference/blob/live/docs/docs-ref-conceptual/requirement-sets/identity-api-requirement-sets.md)
* Product: **office 365**
* GitHub Login: @o365devx
* Microsoft Alias: **o365devx**

**Comment by AlexJerabek** [comment]
Hi @mafut,
Thank you for reporting this issue. I've checked in a fix with PR #193. That should merge to the live branch soon.
