### ISSUE TITLE
setSignatureAsync description incorrect?

### ISSUE THREAD

**Issue by jlara005** [OfficeDev/office-js-docs-reference#1797]
The documentation for setSignatureAsync says "_Adds_ or replaces the signature of the item body". There is no option to add/append to the signature. Calling this function simply replaces the entire content.
---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 0498adf2-3f86-3520-82c2-df88e6ea4b95
* Version Independent ID: 347c34b6-0586-9ce5-2c84-ae010c27b276
* Content: [Office.Body interface - Office Add-ins](https://learn.microsoft.com/en-us/javascript/api/outlook/office.body?view=outlook-js-preview#outlook-office-body-setsignatureasync-member(1))
* Content Source: [docs/docs-ref-autogen/outlook/outlook/office.body.yml](https://github.com/OfficeDev/office-js-docs-reference/blob/live/docs/docs-ref-autogen/outlook/outlook/office.body.yml)
* Service: **outlook**
* Sub-service: **add-ins**
* GitHub Login: @o365devx
* Microsoft Alias: **o365devx**

**Comment by AlexJerabek** [comment]
Hi @jlara005,

Thank you for reporting this. @samantharamon, could you please investigate?

**Comment by samantharamon** [comment]
Thanks for the feedback, @jlara005. The `setSignatureAsync` method adds a signature to a mail item that doesn't have a signature, but replaces the existing signature if present. You're correct that you can't append a signature to an existing one. Let me update the description based on your feedback.

**Comment by jlara005** [comment]
ah that makes sense. Thank you for the clarification!

**Comment by samantharamon** [comment]
No worries, @jlara005! I created [PR #68302](https://github.com/DefinitelyTyped/DefinitelyTyped/pull/68302) to clarify the method description. I'll go ahead and close this issue, but if you have additional questions or feedback, please don't hesitate to create a new GitHub issue.
