### ISSUE TITLE
Requirement set for Dialog API is incorrect.

### ISSUE THREAD

**Issue by praveenbengeri** [OfficeDev/office-js-docs-reference#181]
The documentation says the requirement set for Dialog API is "Dialog", whereas it should be "DialogAPI".

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a98e72c2-bc8c-5664-f6b8-5317f2ff4b51
* Version Independent ID: a84b77c8-9835-d59e-669d-9a5e4e1480f9
* Content: [Office common API requirement sets](https://docs.microsoft.com/en-us/javascript/office/requirement-sets/office-add-in-requirement-sets?view=office-js)
* Content Source: [docs/docs-ref-conceptual/requirement-sets/office-add-in-requirement-sets.md](https://github.com/OfficeDev/office-js-docs-reference/blob/live/docs/docs-ref-conceptual/requirement-sets/office-add-in-requirement-sets.md)
* Product: **office 365**
* GitHub Login: @o365devx
* Microsoft Alias: **o365devx**

**Comment by Rick-Kirkham** [comment]
This is fixed in the source and should be published by late tomorrow.
