### ISSUE TITLE
Word shared runtime add-in giving Error in commands add-in

### ISSUE THREAD

**Issue by junaid042** [OfficeDev/office-js-docs-reference#1825]
when I added Requirements and Runtimes in my manifest.xml my add-in is not working gives error. when I comment it or remove it then it is working. 

![image](https://github.com/OfficeDev/office-js-docs-reference/assets/134502135/165d41ec-3b77-4cc1-8fd0-10b65f3b4289)

![error](https://github.com/OfficeDev/office-js-docs-reference/assets/134502135/00bfef83-e33d-4574-9999-c0be0ccb001c)

**Comment by AlexJerabek** [comment]
Thanks for reporting this @junaid042. Just to confirm, did you [configure the webpack](https://learn.microsoft.com/en-us/office/dev/add-ins/develop/configure-your-add-in-to-use-a-shared-runtime#configure-the-webpackconfigjs-file)?

Let me assign @davidchesnut to follow-up.

**Comment by junaid042** [comment]
Hi @AlexJerabek I have followed all the office documentation but when I added Requirements Sets in my manifest my add-in giving error. I have tried it a lot of new add-ins in word but not working. could you please create a new add-in and run shared runtime and gave me I am very very thankful if you help

**Comment by junaid042** [comment]
@AlexJerabek  this is my new test word test add-in repository [Word-Sharerd-runtime](https://github.com/junaid042/Word-Sharerd-runtime-/tree/main/FSPro) and this is my online [manifest file ](https://drive.google.com/file/d/1y0PpLmqqvAjMCx46bhGonowo-uvjhFEw/view?usp=sharing) one more thing when I add shared runtime requirement sets in my manifest I am facing this in shared folder "no add-in currently available"

![image](https://github.com/OfficeDev/office-js-docs-reference/assets/134502135/3ad046b2-0e61-47f4-b33e-097bd00d91e4)

**Comment by junaid042** [comment]
@AlexJerabek any update?

**Comment by davidchesnut** [comment]
Hi @junaid042 I ran your project and it sideloads into Word correctly. Which version of Word are you using? Thanks!

**Comment by junaid042** [comment]
@davidchesnut  first I am using office 2021 Now I am using office 365 and I got success Thanks for your time
