### ISSUE TITLE
delete if found

### ISSUE THREAD

**Issue by edlgg** [OfficeDev/office-js-docs-reference#184]
I would appreciate if in the example of delete() you also showed the proper way to delete a sheet if i'm not sure it exists. Thanks!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ecc449d8-02af-e5c1-9e6e-74fc9067ca62
* Version Independent ID: 6cc5351c-a26b-5d83-5b8b-df1b92ff3e3a
* Content: [Excel.Worksheet class](https://docs.microsoft.com/en-us/javascript/api/excel/excel.worksheet?view=office-js)
* Content Source: [docs/docs-ref-autogen/excel/excel.worksheet.yml](https://github.com/OfficeDev/office-js-docs-reference/blob/live/docs/docs-ref-autogen/excel/excel.worksheet.yml)
* Product: **office 365**
* GitHub Login: @o365devx
* Microsoft Alias: **o365devx**

**Comment by Rick-Kirkham** [comment]
@edlgg This same question was raised on StackOverflow and I answered it there: https://stackoverflow.com/questions/52453057/in-an-office-js-add-in-how-can-i-delete-a-sheet-that-im-not-sure-its-there/52454373#52454373
