### ISSUE TITLE
Incorrect Example For Office Menu

### ISSUE THREAD

**Issue by nickamckenna** [OfficeDev/office-js-docs-reference#1860]
The Example XML on the page https://learn.microsoft.com/en-us/javascript/api/manifest/officemenu?view=common-js-preview is incorrect. The first line of the example is:

`<OfficeMenu id="ContextMenuCell">`

but should be:

`<OfficeMenu xsi:type="ContextMenuCell">`

to match the documentation above.

**Comment by Rick-Kirkham** [comment]
This is fixed in the source. The updated page will be public late about 5 PM March 7th, 2024, in the Pacific time zone, USA.
