### ISSUE TITLE
how can I set the font family 

### ISSUE THREAD

**Issue by qingfusheng** [OfficeDev/office-js-docs-reference#1867]
如何设置font的字体（such as Heiti）,我没有找到对应的属性

**Comment by AlexJerabek** [comment]
Hi @qingfusheng,

Thank you for your question. Which application are you working with (Excel, Word, etc.)?

In Word, use the [Word.Font.name](https://learn.microsoft.com/en-us/javascript/api/word/word.font?view=word-js-preview#word-word-font-name-member) property.

```
  await Word.run(async (context) => {
    const selection = context.document.getSelection();
    selection.font.name = "Impact";
    await context.sync();
  });
```

In Excel, use the [Excel.RangeFont.name](https://learn.microsoft.com/en-us/javascript/api/excel/excel.rangefont?view=excel-js-preview#excel-excel-rangefont-name-member) property.

```
  await Excel.run(async (context) => {
    const selection = context.workbook.getSelectedRange();
    selection.format.font.name = "Impact";
    await context.sync();
  });
```

Please let me know if this answers your question. Thank you.

**Comment by qingfusheng** [comment]
Thank you for your assistance. Your response was helpful, and I was able to locate the attribute in the document as well. Perhaps it's because the description in the document was a bit confusing, that's why I couldn't find it.

**Comment by qingfusheng** [comment]
I have another question. Is there an interface in the Word API for setting the font for text, specifically for both Chinese and English fonts separately?
