### ISSUE TITLE
VBA cannot delete unused styles from a document

### ISSUE THREAD

**Issue by embedRich** [OfficeDev/office-js-docs-reference#1883]
In word VBA can't delete styles that aren't built-in and aren't used in a document。

13276605335@163.com

**Comment by AlexJerabek** [comment]
Hi @embedRich,

I'm sorry to hear about your issue. However, this repo is for the Office JavaScript APIs. To report an issue with VBA, please use the **Help** > **Feedback** control in Word. That will route the issue to the product team.
