### ISSUE TITLE
Office Add-ins manifest Outlook

### ISSUE THREAD

**Issue by CodeCube0** [OfficeDev/office-js-docs-reference#1924]
![image](https://github.com/OfficeDev/office-js-docs-reference/assets/59050532/6bf02c7e-b192-4e63-a254-3e5a9f39dabd)

How can I obtain all "Control" in large sizes?

How can I set "Separators" like in the old VSTO COM addin manifest

**Comment by AlexJerabek** [comment]
@samantharamon, could you please investigate?

**Comment by samantharamon** [comment]
Hi @CodeCube0,

Apologies for the delayed response. Unfortunately, you can't control the size of the `Control` element in the ribbon. The appearance of the `Control` elements depend on the number of items in the ribbon and the current size of the Outlook window. Regarding separators, you can't have multiple [groups](https://learn.microsoft.com/javascript/api/manifest/group) in a built-in tab on the ribbon. As a workaround, you can implement a [CustomTab](https://learn.microsoft.com/javascript/api/manifest/customtab) element in your manifest, then create multiple groups of controls.

**Comment by CodeCube0** [comment]
thanks so much for the reply I think I'll use the CastomTab for now
