### ISSUE TITLE
Help in Manifest.xml

### ISSUE THREAD

**Issue by CodeCube0** [OfficeDev/office-js-docs-reference#1927]
![Ribbon](https://github.com/OfficeDev/office-js-docs-reference/assets/59050532/464a7274-e2cd-41c3-b9de-620636dffa1c)

How could I replicate this ribbon with the manifest.xml?

**Comment by AlexJerabek** [comment]
Hi @CodeCube0,

Thanks for reaching out. Have you attempted do to this with an Office Add-in yet? Are there specific issues you're encountering? 

The article [Add-in commands](https://learn.microsoft.com/en-us/office/dev/add-ins/design/add-in-commands) should help you get started.

**Comment by CodeCube0** [comment]
I should do the add-in for outlook.

I can't make this Ribbon. Because the manifest.xml doesn't allow me to add more than 6 buttons per group and if I add 5 it shows me three large ones and two small ones. I would also like some actions to integrate into the contextual menus that open with a right click on an email in Outlook but from the documentation I see that there is no way to do it.

**Comment by EsterBergen** [comment]
@CodeCube0 - Thanks for submitting this. Unfortunately you can't control the button layout for any application in Office (Word, Excel, Power point, or Outlook). There is a set heuristic for certain numbers of buttons. Three buttons are big, and then if you have 4 there is another layout, and then 5 or 6 has a different layout, and 6+ has small controls.

As Alex mentioned, this is a great thing to support as a feature request along with the request for contextual right click menus in [M365 Developer Platform Tech Community site](https://techcommunity.microsoft.com/t5/microsoft-365-developer-platform/idb-p/Microsoft365DeveloperPlatform).  Hope that helps!

**Comment by AlexJerabek** [comment]
I'll close this issue, since there's nothing actionable to be done in the docs.
