### ISSUE TITLE
Request for Information on Upcoming Feature Releases for Mailbox

### ISSUE THREAD

**Issue by CodeCube0** [OfficeDev/office-js-docs-reference#1936]
Hi, I would like to know if there will be more additional feature releases for Mailbox this year. Could you provide an approximate timeline for these releases?

**Comment by samantharamon** [comment]
Hi @CodeCube0,

Thanks for reaching out. We recently announced [Mailbox requirement set 1.14](https://devblogs.microsoft.com/microsoft365dev/whats-new-for-office-add-ins-at-build-2024) at Build last week. We don't have a timeline to share about future Mailbox releases at this time. However, please check the [Microsoft 365 Developer blog](https://devblogs.microsoft.com/microsoft365dev) periodically for the latest news. We also encourage you to join the monthly [Office Add-ins community call](https://learn.microsoft.com/office/dev/add-ins/overview/office-add-ins-community-call) as we share feature updates there, too. Additionally, if you want to test features currently in preview, see [Outlook add-in API preview requirement set](https://learn.microsoft.com/javascript/api/requirement-sets/outlook/preview-requirement-set/outlook-requirement-set-preview).

**Comment by Rick-Kirkham** [comment]
[like]  Ricky Kirkham reacted to your message:
________________________________
