### ISSUE TITLE
How to set CustomProperty and recognize emails generated with displayNewMessageFormAsync in an Outlook add-in?

### ISSUE THREAD

**Issue by CodeCube0** [OfficeDev/office-js-docs-reference#1943]
Hi,

I have a question regarding the use of the **displayNewMessageFormAsync** function to generate new emails in an Outlook add-in. How can I set **CustomProperty** for an email generated with this function? Additionally, is there a way to recognize if an email was generated using displayNewMessageFormAsync?

Thanks in advance for your help!

**Comment by AlexJerabek** [comment]
Hi @CodeCube0,

Thank you for the question. Let me assign @samantharamon to take a look.

**Comment by samantharamon** [comment]
Hi @CodeCube0,

To set custom properties in the newly created message, in the callback function of `displayNewMessageFormAsync`, call [Office.context.mailbox.item.loadCustomPropertiesAsync](https://learn.microsoft.com/javascript/api/outlook/office.messagecompose#outlook-office-messagecompose-loadcustompropertiesasync-member(1)). You can then use the `set` method on the returned `CustomProperties` object. For further guidance, see [Get and set add-in metadata for an Outlook add-in](https://learn.microsoft.com/office/dev/add-ins/outlook/metadata-for-an-outlook-add-in#custom-data-per-item-in-a-mailbox-custom-properties).

There isn't a way to identify whether a message was generated using the `displayNewMessageFormAsync` method. If this is a functionality you'd like to see in the product, we recommend requesting it on the [Microsoft 365 Developer Platform Ideas Forum](https://aka.ms/m365dev-suggestions).

**Comment by CodeCube0** [comment]
Okay thank you. I will definitely write in the forum to add features
