### ISSUE TITLE
Property 'isAllDayEvent' does not exist on type 'AppointmentCompose'.ts(2339)

### ISSUE THREAD

**Issue by junaid042** [OfficeDev/office-js-docs-reference#1945]
I tried same code that is in documentation but getting this error
>Property 'isAllDayEvent' does not exist on type 'AppointmentCompose' 

![image](https://github.com/OfficeDev/office-js-docs-reference/assets/134502135/9e24e13e-35c7-47c5-bdfd-33364f04de90)

in script Lab

![image](https://github.com/OfficeDev/office-js-docs-reference/assets/134502135/9d7f9bc8-558f-4855-9c3d-6847250ba218)

**Comment by AlexJerabek** [comment]
Hi @junaid042,

It looks like `isAllDayEvent` is in preview for `AppointmentCompose`. You'll have to switch Script Lab to use the preview type definitions and JS library. The instructions on how to do that can be found [here](https://learn.microsoft.com/en-us/office/dev/add-ins/overview/explore-with-script-lab?view=outlook-js-preview#preview-apis).

Please let me know if that unblocks you. Thanks!

**Comment by junaid042** [comment]
thanks @AlexJerabek it's worked
