### ISSUE TITLE
Information on "addHandlerAsync" for "onMessageSend" in Office.js

### ISSUE THREAD

**Issue by CodeCube0** [OfficeDev/office-js-docs-reference#1951]
Hi, i would like to know if Office.js allows adding a handler for the onMessageSend event using the addHandlerAsync function.

Thank you!

**Comment by skunath** [comment]
@AlexJerabek @samantharamon  Can you confirm that the linked article actually works? I've been trying to get the onMessageSend examples to work for the past few days with no success. I've even started from scratch following the article and have not been able to get any message send alerts to work.

**Comment by CodeCube0** [comment]
@AlexJerabek @samantharamon because I would like my add-on to capture the send event only under certain conditions

**Comment by CodeCube0** [comment]
ok thanks I will implement a solution based on your advice @samantharamon @AlexJerabek
