### ISSUE TITLE
Detect New Emails with Office.js in Outlook Add-ins

### ISSUE THREAD

**Issue by CodeCube0** [OfficeDev/office-js-docs-reference#1960]
How do I know if a new email has been received with officejs? Or how can I find out if a new email has been added to the sent folder?

**Comment by AlexJerabek** [comment]
Hi @CodeCube0,

Let me tag @samantharamon to confirm this, but there currently aren't any events that trigger when messages are received. I'd recommend that you submit a feature request that explains the scenario you're trying to accomplish. Feature requests are submitted to the [Microsoft 365 Developer Platform Tech Community](https://aka.ms/m365dev-suggestions).

**Comment by samantharamon** [comment]
Hi @CodeCube0, 

As Alex mentioned, we currently don't have an event for this scenario. There is already a feature request for this in the [Microsoft 365 Developer Platform Tech Community](https://techcommunity.microsoft.com/t5/microsoft-365-developer-platform/outlook-add-ins-can-we-have-a-new-event-that-trigger-if-any-new/idi-p/3854095) forum, which we recommend you upvote.
