### ISSUE TITLE
Reporting Issues or Bugs with OfficeJS

### ISSUE THREAD

**Issue by CodeCube0** [OfficeDev/office-js-docs-reference#1964]
Hello,

I have encountered some issues and bugs while using OfficeJS. Could you please let me know where I can report these problems to receive assistance or contribute to their resolution?

Thank you!

**Comment by Rick-Kirkham** [comment]
If you're sure you have a bug, create an issue in the [office-js](https://github.com/OfficeDev/office-js/issues) repo.
