### ISSUE TITLE
Example not relevant anymore

### ISSUE THREAD

**Issue by nicolenco-eugeniu-eukles** [OfficeDev/office-js-docs-reference#1976]
In this section
https://learn.microsoft.com/en-us/javascript/api/outlook/office.attachmentcontent?view=outlook-js-preview#outlook-office-attachmentcontent-format-member

There is an example which does not work anymore
the `item.getAttachmentsAsync(options, callback);` method does not exist on mail item

**Comment by AlexJerabek** [comment]
Hi @nicolenco-eugeniu-eukles,

Thank you for reporting this. @samantharamon, could you please investigate?

**Comment by samantharamon** [comment]
Hi @nicolenco-eugeniu-eukles,

Are you calling `item.getAttachmentsAsync` from the compose or read surface? Please note that it's only supported on the compose surface.
