### ISSUE TITLE
Positioning Your Add-In in the Same Location as "Viva Insights" in Microsoft Outlook

### ISSUE THREAD

**Issue by CodeCube0** [OfficeDev/office-js-docs-reference#1978]
![image](https://github.com/OfficeDev/office-js-docs-reference/assets/59050532/ebd3068b-83bb-4a8c-87fa-f12b448231bc)

How can I put my add-in in the same location as "Viva Insights"?

**Comment by AlexJerabek** [comment]
Hi @CodeCube0,

There currently isn't a way to specifically place your add-in icon next to the Viva Insights icon. There is some ribbon control for where at the end of the ribbon your icon shows, though that is currently limited by platform. Could you please share which platform you're on (web, Windows classic, New Outlook for Windows, or Mac)?

Assigning @JuaneloJuanelo to follow-up.
