### ISSUE TITLE
How can i see the key/value into custom properties so that both host and attendee's event have the same

### ISSUE THREAD

**Issue by HappyK68** [OfficeDev/office-js-docs-reference#2020]
How can i set the key/value into custom properties so that both host and attendee's event are the same

Outlook backend api support to do that, but office add-in js api seems not support~

**Comment by AlexJerabek** [comment]
Hi @HappyK68,

Thanks for raising this question. @samantharamon, could you please investigate?

**Comment by samantharamon** [comment]
Hi @HappyK68,

You can only set custom properties that are preserved on both the sender and receiver's ends on messages using the [internet headers API](https://learn.microsoft.com/office/dev/add-ins/outlook/internet-headers). Unfortunately, this functionality isn't currently available on appointments. The team has a feature request for this in the backlog. We're unable to provide a timeline at this time, but please keep an eye out for this feature in the future. If you haven't already, I encourage you to upvote the [feature request](https://techcommunity.microsoft.com/t5/microsoft-365-developer-platform/add-the-internetheaders-property-to-the-office/idi-p/3660816) to help the team prioritize it.
