### ISSUE TITLE
How to add a shape to our desired coordinates position rather than at the pre-defined position?

### ISSUE THREAD

**Issue by vrishab-singh** [OfficeDev/office-js-docs-reference#2041]
As I am trying to build an add-in, I'm facing an issue. How can I add a shape to our desired coordinates position rather than at the pre-defined position in MS PowerPoint?

**Comment by ElizabethSamuel-MSFT** [comment]
@vrishab-singh You may be able to use something like [PowerPoint.ShapeCollection.addGeometricShape(geometricShapeType, options)](https://learn.microsoft.com/en-us/javascript/api/powerpoint/powerpoint.shapecollection?view=powerpoint-js-preview#powerpoint-powerpoint-shapecollection-addgeometricshape-member(1)). In the options parameter (of type [PowerPoint.ShapeAddOptions](https://learn.microsoft.com/en-us/javascript/api/powerpoint/powerpoint.shapeaddoptions?view=powerpoint-js-preview)), use the top and left properties to set your desired distances in points from the top and left edges of the slide. See the Examples section of the addGeometricShape API's documentation for a code sample.

Can you try this and let us know if this helps?

Thanks.
