### ISSUE TITLE
Wrong Add-in Types

### ISSUE THREAD

**Issue by MK-MASTER** [OfficeDev/office-js-docs-reference#205]
PhoneSettings only applies to Mail Add-ins so can you please correct the documentation above

"Add-in type: Content, Task pane, Mail"

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 036a61a1-66ce-79a4-848f-08974cf56021
* Version Independent ID: 7278a717-d121-19da-6bc6-9164f3477a06
* Content: [PhoneSettings element](https://docs.microsoft.com/en-us/javascript/office/manifest/phonesettings?view=office-js)
* Content Source: [docs/docs-ref-conceptual/manifest/phonesettings.md](https://github.com/OfficeDev/office-js-docs-reference/blob/live/docs/docs-ref-conceptual/manifest/phonesettings.md)
* Product: **office 365**
* GitHub Login: @o365devx
* Microsoft Alias: **o365devx**

**Comment by Rick-Kirkham** [comment]
Thanks. We're looking into this.

**Comment by ElizabethSamuel-MSFT** [comment]
@MK-MASTER: The documentation has been updated (PR: https://github.com/OfficeDev/office-js-docs-pr/pull/464) and should be published soon. Thanks again.
