### ISSUE TITLE
setting both chinese and English font type by api

### ISSUE THREAD

**Issue by zeratul1215** [OfficeDev/office-js-docs-reference#2056]
Is there any way that I can setting the chinese and english font separately for a paragraph using the Office.js api?

**Comment by AlexJerabek** [comment]
Hi @zeratul1215,

I don't believe this is possible today. Let me tag @wangyun-microsoft to confirm.

**Comment by AlexJerabek** [comment]
@ElizabethSamuel-MSFT, could you please follow-up with a confirmation here? Thank you!

**Comment by ElizabethSamuel-MSFT** [comment]
@zeratul1215 Thanks for asking about this. I've confirmed with the feature crew that this isn't supported. You can only set one font at a time using the API. See the first item and related responses in issue https://github.com/OfficeDev/office-js/issues/4430.

Please create or upvote the feature request at https://techcommunity.microsoft.com/t5/microsoft-365-developer-platform/idb-p/Microsoft365DeveloperPlatform.

I'll go ahead and close this issue.

Thanks again for your interest in Office Add-ins.
