### ISSUE TITLE
Possibility to launch the Outlook add-in with PIN already pinned

### ISSUE THREAD

**Issue by CodeCube0** [OfficeDev/office-js-docs-reference#2066]
I would like to know if it is possible to configure the Outlook add-in to start with the PIN already locked. Currently, I have to manually pin every time I start the add-in for the first time. It would be very helpful to allow the add-in to start directly with the PIN already pinned.

**Comment by AlexJerabek** [comment]
Hi @CodeCube0,

I don't think this is possible today. I'll tag @samantharamon to verify, but if it's not, please file a feature request on our [Tech Community page](https://techcommunity.microsoft.com/t5/microsoft-365-developer-platform/idb-p/Microsoft365DeveloperPlatform).

**Comment by samantharamon** [comment]
Hi @CodeCube0,

As @AlexJerabek mentioned, an add-in can't currently start with its task pane already pinned. You'll have to manually pin it first. It looks like this feature has already been requested on our Tech Community page (see [Pin Outlook add-in automatically based on screen size](https://techcommunity.microsoft.com/t5/microsoft-365-developer-platform/pin-outlook-add-in-automatically-based-on-screen-size/idi-p/3845415)). If this request reflects your requirements, we recommend upvoting it.

I'll go ahead and close this issue, but should you require further assistance, please don't hesitate to create a new one.
