### ISSUE TITLE
How to join google login

### ISSUE THREAD

**Issue by jh-9527** [OfficeDev/office-js-docs-reference#2078]
In my word add-in, I need to join google Login. Please tell me how to join google Login. Thank you.

**Comment by Rick-Kirkham** [comment]
Please see if this article meets your needs. 
[Authorization with non-Microsoft identity providers](https://learn.microsoft.com/en-us/office/dev/add-ins/develop/auth-external-add-ins)

I'll close this issue. Please let us know if you have further questions.
