### ISSUE TITLE
Some conditional format classes are now marked as deprecated

### ISSUE THREAD

**Issue by sndurkin** [OfficeDev/office-js-docs-reference#2083]
**Article URL**

- https://learn.microsoft.com/en-us/javascript/api/excel/excel.conditionalcellvaluerule?view=excel-js-preview
- https://learn.microsoft.com/en-us/javascript/api/excel/excel.colorscaleconditionalformat?view=excel-js-preview

**Describe the problem**

These classes are now marked as deprecated, but there is no additional information provided. Is this a mistake? If it's intentional, what classes are replacing them?

**Screenshots**

![image](https://github.com/user-attachments/assets/3529920d-1972-4b9d-9d22-f295966a0494)

**Comment by EsterBergen** [comment]
@alison-mk - Can you please look into this?

**Comment by ElizabethSamuel-MSFT** [comment]
@sndurkin Thanks for bringing this to our attention. These APIs have NOT been deprecated. Our apologies for this confusion. The docs should no longer be showing these deprecated warnings.

Thanks.

**Comment by ElizabethSamuel-MSFT** [comment]
@sndurkin You may notice other Excel APIs being reported as deprecated. At present, there should be none. We're following up with another internal team about this issue but there's no action we can take in the docs at this point.
