### ISSUE TITLE
getFileAsync(fileType, callback) has confusing Remarks -> Requirements sets-> File item

### ISSUE THREAD

**Issue by thekingofspain** [OfficeDev/office-js-docs-reference#2087]
The [office.document getFileAsync documentation](https://learn.microsoft.com/en-us/javascript/api/office/office.document?view=common-js#office-office-document-getfileasync-member(2)) in the _Remarks_ section and _Requirement set_ sub section, there is a bullet item that is named as and points to [File](https://learn.microsoft.com/en-us/javascript/api/requirement-sets/common/office-add-in-requirement-sets#file).  It is unclear clear to me if this is telling me something that I need to know and if so what, or if the term File is an error and the item should for a PDF item.

**Comment by Rick-Kirkham** [comment]
All of the items in the **Requirement set** subsection are identifying the API requirement sets that must be supported on an Office application in order for an add-in that uses `getFileAsync` to be installable on a that Office application. What you see at the [File](https://learn.microsoft.com/en-us/javascript/api/requirement-sets/common/office-add-in-requirement-sets?view=common-js-preview#file) link is a list of all the Office applications that support the **File 1.1** requirement set.  For more about requirement sets and what they are used for, see [Specify Office applications and API requirements](https://learn.microsoft.com/en-us/office/dev/add-ins/develop/specify-office-hosts-and-api-requirements?view=common-js-preview). 

I'll close this issue for now, but you can still add comments to it.
