### ISSUE TITLE
what function in office.js is maped to the "define multilevel list" function in the wordUI 

### ISSUE THREAD

**Issue by XWANG0224** [OfficeDev/office-js-docs-reference#2091]
![image](https://github.com/user-attachments/assets/19af669b-1f59-4a76-afce-47cd3ef048fd)

as you can see there is a function called "define multilevel list" in the wordUI, is there any function in the office.js mapped to it?

If yes, how can I set the properties of the multilevel list I define using the office.js

**Comment by zeratul1215** [comment]
thank you for answering, but I notice that, in a multilevel list I define, I can link each level to a style, is there any api support this function?

**Comment by zeratul1215** [comment]
I understand that I can insert a new list throught the office.js api, but thing I actually want to do is that I want to define a 9-level list format first, and link each level to a specified style to this list format, in the word UI, I can do this as shown in the screenshot below, is it possible to do this through office.js?
![image](https://github.com/user-attachments/assets/11134fcd-461f-4ae8-9f6f-7b873550a223)
![image](https://github.com/user-attachments/assets/98e5bc52-1fd0-48b9-8448-adfcf7784bde)

**Comment by ElizabethSamuel-MSFT** [comment]
@zeratul1215 I'll reactivate issue https://github.com/OfficeDev/office-js-docs-reference/issues/2062 and respond to you there.

**Comment by zeratul1215** [comment]
thank you so much
