### ISSUE TITLE
javascript window.location.href

### ISSUE THREAD

**Issue by CodeCube0** [OfficeDev/office-js-docs-reference#2106]
why if I do "window.location.href" from old outlook inside the plugin it opens the browser instead of following the redirect? Is there any solution to allow to follow the redirect with "window.location.href"

**Comment by samantharamon** [comment]
Hi @CodeCube0,

Thanks for reaching out.

Does `window.location.href` point to a domain other than the domain that hosts your add-in? If so, you'll need to specify it in the \<AppDomains> section of your manifest. Here are a few references that might help:

- [Links and JS redirects, cause opening a new window in Office JS add-ins](https://stackoverflow.com/questions/39261394/links-and-js-redirects-cause-openning-a-new-window-in-office-js-add-ins)
- [AppDomains element](https://learn.microsoft.com/javascript/api/manifest/appdomains)
