### ISSUE TITLE
TypeError: context.document.insertFileFromBase64 is not a function

### ISSUE THREAD

**Issue by MeeGooBoo** [OfficeDev/office-js-docs-reference#2137]
`context.document.body.insertFileFromBase64(templateBase64, "Replace");//This is fine, but information like headers is not preserved`

`context.document.insertFileFromBase64(templateBase64, "Replace");//TypeError: context.document.insertFileFromBase64 is not a function |npm> "name": "@microsoft/office-js","version": "1.1.95"`

Please let us know which version I support context. Document.InsertFileFromBase64？Or is there another way to preserve the headers and all styles of the template file??
![image](https://github.com/user-attachments/assets/1a105eca-713f-446d-a969-27cca331ad3e)

**Comment by MJSQ** [comment]
> 您好 ，
> 
> `Document.insertFileFromBase64`是要求集 WordApi 1.5 的一部分。您可以在下表中查看哪些版本的 Word 支持此 API：https://learn.microsoft.com/javascript/api/requirement-sets/word/word-api-requirement-sets?view=word-js-preview#requirement-set-availability。您在哪个版本的 Word 中看到此错误？如果根据文件覆盖，我们可以将此问题转给产品组。
> 
> 此外，您应该通过我们的 CDN：[https://learn.microsoft.com/en-us/office/dev/add-ins/develop/referencing-the-javascript-api-for-office-library-from-its-cdn?view=word-js-preview 引用office.js](https://learn.microsoft.com/en-us/office/dev/add-ins/develop/referencing-the-javascript-api-for-office-library-from-its-cdn?view=word-js-preview)。这可确保您的外接程序始终具有最新版本的 office.js。

Thanks for your reply. It has been fixed in word-win32-16.01.js version.

**Comment by MJSQ** [comment]
> @MJSQ Also note that the office-js NPM package isn't the recommended path for Office.js (see the "Support" section of the [@microsoft/office-js](https://www.npmjs.com/package/@microsoft/office-js) package readme).

Download via NPM package in the use of the context. The document. The insertFileFromBase64 causes problems, by replacing the word - win32-16.01. Js and office. Js to fix the problem.

**Comment by ElizabethSamuel-MSFT** [comment]
@MeeGooBoo Seems like you've resolved your issue so I'll go ahead and close this.

However, if it's still an issue, let us know and we'll reopen it.

Thanks.
