### ISSUE TITLE
RequestedWidth?

### ISSUE THREAD

**Issue by ChemMitch** [OfficeDev/office-js-docs-reference#2167]
This page
https://learn.microsoft.com/en-us/javascript/api/manifest/requestedwidth?view=common-js-preview#contained-in
suggests that I can add a `<RequestedWidth>integer</RequestedWidth>` to my manifest.xml
but when I add this section
```
<DefaultSettings>
    <SourceLocation DefaultValue="https://localhost:3000/taskpane.html"/>
    <RequestedWidth>500</RequestedWidth>
  </DefaultSettings>
```
and run 
`npm run validate`
This error is returned:
Error  1:
XML Schema Validation Error: Error found during XML Schema validation.
  - Details: The element 'DefaultSettings' in namespace 'http://schemas.microsoft.com/office/appforoffice/1.1' has invalid child element 'RequestedWidth' in namespace 'http://schemas.microsoft.com/office/appforoffice/1.1'.
  - Line: 24
  - Column: 6
Can you explain this apparent discrepancy?

**Comment by Rick-Kirkham** [comment]
This article seems to imply, by the indentations in the sample, that the `<RequestedWidth>` and `<RequestedHeight>` elements are _peers_ of `<DefaultSettings>`:

[Basic content element ordering](https://learn.microsoft.com/en-us/office/dev/add-ins/develop/manifest-element-ordering#basic-content-add-in-element-ordering)

So, there is an inconsistency in the documentation. Based on the actual schema at [http://schemas.microsoft.com/office/appforoffice/1.0 Schema](https://learn.microsoft.com/en-us/openspecs/office_file_formats/ms-owemxml/4e112d0a-c8ab-46a6-8a6c-2a1c1d1299e3), I think the "ordering" article is wrong and the reference article that you linked to is correct. 

But it looks like you are trying to use the `<RequestWidth>` in a _task pane_ add-in. This element is only valid when the topmost element in the manifest is type ContentApp. E.g.,

```
<OfficeApp xsi:type="ContentApp">
```

You cannot request sizes for a task pane. 

Note the part of the article circled in red: 
<img width="409" alt="image" src="https://github.com/user-attachments/assets/7dcfd190-819c-4f82-aa93-fe15d0760b15" />

Please get back to us to confirm or refute that you are making a task pane add-in. In the meantime, I'll make a work item for my self to fix the "ordering" article.

**Comment by ChemMitch** [comment]
Thank you for the clarification!
