### ISSUE TITLE
Example code - instruction not required

### ISSUE THREAD

**Issue by joelfmrodrigues** [OfficeDev/office-js-docs-reference#220]
[Enter feedback here]

---
#### Document Details

Retrieving the page is not required as it's not being used on the sample code

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 211bf382-30fa-d9dc-f3e3-f4705f637fc9
* Version Independent ID: 6e96ba12-0995-2aac-050a-48b7c62a4cbf
* Content: [Visio.PageLoadCompleteEventArgs interface](https://docs.microsoft.com/en-us/javascript/api/visio/visio.pageloadcompleteeventargs?view=office-js)
* Content Source: [docs/docs-ref-autogen/visio/visio.pageloadcompleteeventargs.yml](https://github.com/OfficeDev/office-js-docs-reference/blob/live/docs/docs-ref-autogen/visio/visio.pageloadcompleteeventargs.yml)
* Product: **office 365**
* GitHub Login: @o365devx
* Microsoft Alias: **o365devx**

**Comment by AlexJerabek** [comment]
Hi @joelfmrodrigues, 
I'm not sure I understand the issue. The sample code is showing how to register a PageLoadComplete event and access the args in a simple scenario. Is something missing that you feel should be there?

**Comment by joelfmrodrigues** [comment]
Hi @AlexJerabek 

I actually submitted a PR to remove the unnecessary code some time ago. Just forgot to reference and close the issue.
Closing now.
Thanks for replying back
