### ISSUE TITLE
getAsync() have a wrong callback datatype

### ISSUE THREAD

**Issue by sebastianmattar** [OfficeDev/office-js-docs-reference#229]
GetAsync() returns a string, not the object it was called on.

```callback?: (result: AsyncResult&lt;Office.Body&gt;)```
Should be:
``callback?: (result: AsyncResult&lt;string&gt;)````
for all getAsync() methods

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 076f70b1-5d37-89d9-b6d1-a249b85506ee
* Version Independent ID: 347c34b6-0586-9ce5-2c84-ae010c27b276
* Content: [Office.Body interface](https://docs.microsoft.com/en-us/javascript/api/outlook/office.body?view=office-js#getasync-coerciontype--options--callback-)
* Content Source: [docs/docs-ref-autogen/outlook/office.body.yml](https://github.com/OfficeDev/office-js-docs-reference/blob/live/docs/docs-ref-autogen/outlook/office.body.yml)
* Product: **office 365**
* GitHub Login: @o365devx
* Microsoft Alias: **o365devx**

**Comment by ElizabethSamuel-MSFT** [comment]
@sebastianmattar Thanks for your contribution in PR https://github.com/DefinitelyTyped/DefinitelyTyped/pull/30050. Once the final changes are merged to master, this documentation should be updated soon after that.
