### ISSUE TITLE
Image filetype option

### ISSUE THREAD

**Issue by brambooo** [OfficeDev/office-js-docs-reference#230]
Would love to see an option to export individual or more PowerPoint slides to images (for example base64 or png).

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4bf6ede3-db30-be96-0de6-d4e429d83bd1
* Version Independent ID: 62cb7f3a-1e7b-064e-93eb-09a3f57f0e81
* Content: [Office.FileType enum](https://docs.microsoft.com/en-us/javascript/api/office/office.filetype?view=office-js)
* Content Source: [docs/docs-ref-autogen/office/office.filetype.yml](https://github.com/OfficeDev/office-js-docs-reference/blob/live/docs/docs-ref-autogen/office/office.filetype.yml)
* Product: **office 365**
* GitHub Login: @o365devx
* Microsoft Alias: **o365devx**

**Comment by AlexJerabek** [comment]
Hi @brambooo,

Thank you for the feedback. This repo is for issues with the API reference docs. For functionality requests, please visit [User Voice](https://officespdev.uservoice.com/) and suggest the feature. There, it can be upvoted by the community and properly triaged by our engineers.

I'll close the issue, but please open another if you find anything erroneous or missing from the documentation.
