### ISSUE TITLE
CoercionType.Matrix will not bypass "calculated columns" feature as suggested by the docs

### ISSUE THREAD

**Issue by sameera** [OfficeDev/office-js-docs-reference#252]
Article:
Document.setSelectedDataAsync method

Issue: 
Following text does not reflect the actual behavior of the API/Excel

> NOTE: In Excel, if you specify formulas in the TableData object you pass for the data parameter, you might not get the results you expect due to the "calculated columns" feature of Excel, which automatically duplicates formulas within a column. To work around this when you want to write data that contains formulas to a selected table, try specifying the data as an array of arrays (instead of a TableData object), and specify the coercionType as Microsoft.Office.Matrix or "matrix".

This doesn't actually work: Calculated Columns feature applies when matrix or table coercionTypes are used. Only way to workaround this seems to be to write the cells individually with "text" coercionType.

**Comment by Rick-Kirkham** [comment]
The documentation has been fixed in the source. It should be in the public docs in a few days.
