### ISSUE TITLE
Is the description of the color property wrong

### ISSUE THREAD

**Issue by changchengqin** [OfficeDev/office-js-docs-reference#276]
Not the color of the border line.
It's the background color.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9091b50e-16b8-50b1-f1b3-b6768504a77d
* Version Independent ID: 2d71a29a-195e-6b85-ae11-25ebe2e09e70
* Content: [Excel.RangeFill class - Office Add-ins](https://docs.microsoft.com/en-us/javascript/api/excel/excel.rangefill?view=office-js#feedback)
* Content Source: [docs/docs-ref-autogen/excel/excel.rangefill.yml](https://github.com/OfficeDev/office-js-docs-reference/blob/live/docs/docs-ref-autogen/excel/excel.rangefill.yml)
* Product: **office 365**
* GitHub Login: @o365devx
* Microsoft Alias: **o365devx**

**Comment by AlexJerabek** [comment]
Hi @changchengqin, 
Thanks for reporting this. I'll change the upstream files from which these reference docs are generated. I'll report back to this thread when those updates propagate through.

**Comment by AlexJerabek** [comment]
The text correction has been checked into master with [this PR](https://github.com/OfficeDev/office-js-docs-reference/pull/278). This will be pushed to live later this week. I'll close the issue now, but please let us know if anything is still incorrect.
