### ISSUE TITLE
Property description typo

### ISSUE THREAD

**Issue by danielgwilson** [OfficeDev/office-js-docs-reference#342]
Property description for controlForegroundColor reads "Gets the Office theme body control color as a hexadecimal color triplet (e.g. "FFA500")" where it should read "...control foreground color..." striking "body."

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 57500af6-fb91-7a89-58aa-4c604b412bed
* Version Independent ID: f356c836-0840-558e-121e-4b68d7b3d741
* Content: [Office.OfficeTheme interface - Office Add-ins](https://docs.microsoft.com/en-us/javascript/api/office/office.officetheme?view=office-js)
* Content Source: [docs/docs-ref-autogen/office/office.officetheme.yml](https://github.com/OfficeDev/office-js-docs-reference/blob/live/docs/docs-ref-autogen/office/office.officetheme.yml)
* Product: **non-product-specific**
* GitHub Login: @o365devx
* Microsoft Alias: **o365devx**

**Comment by AlexJerabek** [comment]
Hi @danielgwilson, 
I have the fix upstream with [this PR](https://github.com/DefinitelyTyped/DefinitelyTyped/pull/33594).

**Comment by AlexJerabek** [comment]
And it'll be checked in to this repo with [this PR](https://github.com/OfficeDev/office-js-docs-reference/pull/343).
