### ISSUE TITLE
Not enough detail

### ISSUE THREAD

**Issue by jhamilton68** [OfficeDev/office-js-docs-reference#348]
I would love to use the JavaScript API for Office but there just isn't enough detail in these docs. I have to do too much guessing and hacking. I've used a lot of APIs. Microsoft has some good API documentation but this isn't it.  Python.org has some excellent documentation. cppreference.com is some excellent documentation. The old Windows APIs are very well documented.  JavaScript API for Office, not so much.    The explanation of the property or method should tell me more than I could guess from the property name. Some of your tutorials are okay we just need more.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6baf89b8-8d3a-b788-90b9-3514924e25e3
* Version Independent ID: 2b4a7f35-242d-64a3-e412-0313401dfc3a
* Content: [Office JavaScript API reference - Office Add-ins](https://docs.microsoft.com/en-us/javascript/api/overview/office?view=office-js#feedback)
* Content Source: [docs/docs-ref-autogen/overview/office.md](https://github.com/OfficeDev/office-js-docs-reference/blob/live/docs/docs-ref-autogen/overview/office.md)
* Product: **non-product-specific**
* GitHub Login: @o365devx
* Microsoft Alias: **o365devx**

**Comment by Rick-Kirkham** [comment]
@jhamilton68 Thanks for the suggestion for more tutorials. Do you have other suggestions for what more we could add in the way of details? Also, could you tell us what host (Excel, Word, etc.) you are working with and what you are trying to do? Finally, if case you haven't already, please note that we have extensive conceptual documentation that includes many "how to"s for working with the JavaScript APIs.
