### ISSUE TITLE
Office.context.mailbox.item.location object not recognized correctly

### ISSUE THREAD

**Issue by rodrigoguariento** [OfficeDev/office-js-docs-reference#362]
Resource/room selected with Office.context.mailbox.item.location.setAsync is being treated differently of Outlook web and Microsoft Office Outlook selection. Using this code a simple text is being written at Office.context.mailbox.item.location, without references to resource (room) created in Admin Center 365. The outcome is that we can't see the scheduling of this resource/room. See: https://github.com/OfficeDev/office-js/issues/453

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 105ede86-e114-9103-d7f9-10dad0529eee
* Version Independent ID: 8f8f336e-f74d-9bda-cef6-e4c191de80e7
* Content: [Office.Location interface - Office Add-ins](https://docs.microsoft.com/en-us/javascript/api/outlook_1_6/office.location?view=office-js)
* Content Source: [docs/docs-ref-autogen/outlook_1_6/office.location.yml](https://github.com/OfficeDev/office-js-docs-reference/blob/live/docs/docs-ref-autogen/outlook_1_6/office.location.yml)
* Product: **outlook**
* Technology: **add-ins**
* GitHub Login: @o365devx
* Microsoft Alias: **o365devx**

**Comment by ElizabethSamuel-MSFT** [comment]
Thanks for raising this. Depending on what the investigation reveals, we'll update the docs accordingly.

**Comment by exextoc** [comment]
Please see comments on the linked issue.
