### ISSUE TITLE
missing a semicolon in the example

### ISSUE THREAD

**Issue by tong-1324** [OfficeDev/office-js-docs-reference#372]
missing a semicolon after this line var controlBackgroundColor = Office.context.officeTheme.controlBackgroundColor in the example

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 57500af6-fb91-7a89-58aa-4c604b412bed
* Version Independent ID: f356c836-0840-558e-121e-4b68d7b3d741
* Content: [Office.OfficeTheme interface - Office Add-ins](https://docs.microsoft.com/en-us/javascript/api/office/office.officetheme?view=office-js#feedback)
* Content Source: [docs/docs-ref-autogen/office/office.officetheme.yml](https://github.com/OfficeDev/office-js-docs-reference/blob/live/docs/docs-ref-autogen/office/office.officetheme.yml)
* Product: **non-product-specific**
* Technology: **add-ins**
* GitHub Login: @o365devx
* Microsoft Alias: **o365devx**

**Comment by AlexJerabek** [comment]
This is fixed with PR #374, which will be merged to the live branch soon.
