### ISSUE TITLE
Arguments for add(content, cellAddress, contentType)

### ISSUE THREAD

**Issue by vaquierm** [OfficeDev/office-js-docs-reference#403]
The argument cellAddress can be an excel range. Maybe it could be nice to specify that the range object must be a singular cell. Cheers

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8de5a350-77d5-9694-63a0-e5e1160b171a
* Version Independent ID: bb8eaed0-6d9c-b1ef-2607-7bcea4211681
* Content: [Excel.CommentCollection class - Office Add-ins](https://docs.microsoft.com/en-us/javascript/api/excel/excel.commentcollection?view=office-js#feedback)
* Content Source: [docs/docs-ref-autogen/excel/excel.commentcollection.yml](https://github.com/OfficeDev/office-js-docs-reference/blob/live/docs/docs-ref-autogen/excel/excel.commentcollection.yml)
* Product: **excel**
* Technology: **add-ins**
* GitHub Login: @o365devx
* Microsoft Alias: **o365devx**

**Comment by AlexJerabek** [comment]
Hi @vaquierm, 

Thanks for the feedback. The function description does mention the single-cell scenario, but that information should also be in the parameter description. I'll get that in the docs soon.

**Comment by AlexJerabek** [comment]
Hi @vaquierm, 
The suggested changes have been checked into the master branch of this repo (with [this PR](https://github.com/OfficeDev/office-js-docs-reference/pull/408)). They should be live soon.
I'll close this PR. Please respond to the thread if there are any other issues. Thanks!
