### ISSUE TITLE
Is "complete" defined somewhere?

### ISSUE THREAD

**Issue by fds-ssg** [OfficeDev/office-js-docs-reference#404]
In just reading this page, it's not clear to what qualifies as a "complete" or "partial" match.  e.g., Does "complete" mean that the search string must match the entire cell contents?  Or is it more akin to a "whole word" requirement, in which case it would be helpful to know which characters constitute word components vs. word separators.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 61b7d244-ee86-561c-853a-b289b8184c01
* Version Independent ID: 208ba922-39f7-21ac-9481-646216edec6e
* Content: [Excel.WorksheetSearchCriteria interface - Office Add-ins](https://docs.microsoft.com/en-us/javascript/api/excel/excel.worksheetsearchcriteria?view=office-js#feedback)
* Content Source: [docs/docs-ref-autogen/excel/excel.worksheetsearchcriteria.yml](https://github.com/OfficeDev/office-js-docs-reference/blob/live/docs/docs-ref-autogen/excel/excel.worksheetsearchcriteria.yml)
* Product: **excel**
* Technology: **add-ins**
* GitHub Login: @o365devx
* Microsoft Alias: **o365devx**

**Comment by ElizabethSamuel-MSFT** [comment]
@AlexJerabek: Can you take a look. Thanks.

**Comment by AlexJerabek** [comment]
Hi @fds-ssg,

Thanks for your question. "Complete" does mean entire cell content, not whole word. We have a [Script Lab snippet](https://github.com/OfficeDev/office-js-snippets/blob/master/samples/excel/54-worksheet/worksheet-find-all.yaml) showcasing this behavior (we also have one for [Range.findText](https://github.com/OfficeDev/office-js-snippets/blob/master/samples/excel/42-range/range-find.yaml)).

I'll update the docs to make this clearer.

**Comment by AlexJerabek** [comment]
Hi @fds-ssg 
The suggested changes have been checked into the master branch of this repo (with [this PR](https://github.com/OfficeDev/office-js-docs-reference/pull/408)). They should be live soon.
I'll close this PR. Please respond to the thread if there are any other issues. Thanks!
