### ISSUE TITLE
Double-Click Event Tracking How-to vs. WorksheetSingleClickedEventArgs

### ISSUE THREAD

**Issue by aicglabs** [OfficeDev/office-js-docs-reference#406]
How would one determine if a cell has been double-clicked?
Also, How would one be able to detect a right-click event?

These seems to be missing from the API for Excel.  

Is there a coding solution for the above handling of user actions that you could share?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 75f3cb21-a7f5-6816-5915-0a9750b64b91
* Version Independent ID: 625c1438-56e6-c911-d32c-6ccf7bf135d0
* Content: [Excel.WorksheetSingleClickedEventArgs interface - Office Add-ins](https://docs.microsoft.com/en-us/javascript/api/excel/excel.worksheetsingleclickedeventargs?view=office-js#feedback)
* Content Source: [docs/docs-ref-autogen/excel/excel.worksheetsingleclickedeventargs.yml](https://github.com/OfficeDev/office-js-docs-reference/blob/live/docs/docs-ref-autogen/excel/excel.worksheetsingleclickedeventargs.yml)
* Product: **excel**
* Technology: **add-ins**
* GitHub Login: @o365devx
* Microsoft Alias: **o365devx**

**Comment by AlexJerabek** [comment]
Hi @aicglabs, 

Thanks for your question. This API is still under development, so these scenarios are still being considered. I'll pass your question on to the PMs and have them respond soon.

**Comment by AlexJerabek** [comment]
Hi @aicglabs, 
One of our Excel PMs will be following up with you soon. In the meantime, could you share more of your scenario with us? We're curious what your add-in needs to support.
Thanks!

**Comment by lumine2008** [comment]
Thanks @aicglabs, Would you please share us your scenario for double click, we would like to learn more about it. 
So far we don't have double click event, the main reason is when user double click on a cell, it will enter the cell edit mode, our API will stop working when in cell edit mode. double click event will be trigger after it exit the cell edit mode. 
for right click event, could you please share us your scenario as well?

**Comment by aicglabs** [comment]
@lumine2008 / @AlexJerabek ,
We are looking to have this event to capture some user actionability on data points that would allow for subsequent programmatic actions such as retrieving more data (detail data), or creating a chart or extra data, etc.

This double-clicking functionality was first noticed in this product which has an excel add-in, as described in some high-level detail with these links:
- https://docs.oracle.com/cd/E57185_01/SMVUG/ch06s05s05.html
- https://docs.oracle.com/cd/E38445_01/doc.11122/esb_ss_user/frameset.htm?idh_essbase_toolbar.html

Any thoughts on how this could be done with the new fabric/office365 add-on functionality?

Right-clicking in this add-in also reduces the context menu so that when in section of data, where this add-in is used, the context menu is minimized to only show a short list of default excel menu items, then mainly this add-ins context menu list.  Thoughts there?

**Comment by AlexJerabek** [comment]
Hi @aicglabs,
Just to clarify, are you looking for the double-click listener in the Excel worksheet or in the add-in's task pane?
Thanks!

**Comment by aicglabs** [comment]
@AlexJerabek ,
left click double-click listener in the excel worksheet.

**Comment by AlexJerabek** [comment]
Thanks @aicglabs. @lumine2008 will investigate this scenario's needs with regards to the next API release and reply back to this thread.

**Comment by AlexJerabek** [comment]
Hi @aicglabs 

@lumine2008 and I discussed the possibility of a double click listener. It's not currently on the roadmap, as there are some technical hurdles to clear (like the aforementioned cell-edit mode context switch). It certainly could be a feature in the future with enough community demand. I'd recommend heading over to [UserVoice](https://officespdev.uservoice.com/) and creating a request. The more traction a request gains in UserVoice, the more likely we are to add it in a future release.

Thank you for the discussion. I'll close the issue on this repo and look forward to your UserVoice post.
