### ISSUE TITLE
Error code table help developers to write conditional statement

### ISSUE THREAD

**Issue by NT-D** [OfficeDev/office-js-docs-reference#413]
Hi  Office.js team,
This interface is really clear and I can understand definition, but let me share feedback for better developer experience. If the document provide error code table, developers can consider and write better conditional statements. Currently we don't have any info about what number is passed through `code` property. 

Fortunately and unfortunately, I've never seen error in my environment and hard to see what happen and to decide conditional statement. Would you please consider to provide error table like Microsoft Graph document?
https://docs.microsoft.com/en-us/graph/errors

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f99ea712-014b-8562-5a76-7ed4a409f11f
* Version Independent ID: e64fa016-f63f-69c9-2751-a3cacc11b1fe
* Content: [Office.Error interface - Office Add-ins](https://docs.microsoft.com/en-us/javascript/api/office/office.error?view=office-js#code)
* Content Source: [docs/docs-ref-autogen/office/office.error.yml](https://github.com/OfficeDev/office-js-docs-reference/blob/live/docs/docs-ref-autogen/office/office.error.yml)
* Product: **non-product-specific**
* Technology: **add-ins**
* GitHub Login: @o365devx
* Microsoft Alias: **o365devx**

**Comment by Rick-Kirkham** [comment]
Thanks for your interest in Office Add-ins. We have the error code table at: [JavaScript API for Office Error Codes](https://docs.microsoft.com/en-us/office/dev/add-ins/reference/javascript-api-for-office-error-codes). Please let us know if that doesn't meet your needs.

**Comment by NT-D** [comment]
Thank you very much @Rick-Kirkham for your quick reply. Yes, this is what I want to see! I'll write my code referring this table.

I think it may be nice for other developers to add the table link to [Office.Error interface page](https://docs.microsoft.com/en-us/javascript/api/office/office.error?view=office-js). For example, you can change `Properties` table like below, and I think this link help developers to know detail :)

Properties | -- 
------------ | -------------
code | Gets the numeric code of the error. For more error information, see [JavaScript API for Office Error Codes](https://docs.microsoft.com/en-us/office/dev/add-ins/reference/javascript-api-for-office-error-codes).
message | Gets the name of the error.
name | Gets a detailed description of the error.

*Because I can't make non-header table with markdown, I added `Properties` column. It's no meaning. just want to show adding link in the table
** I wanted to send PR, but can't find this document's .md file in GitHub. Therefore, Let me just send feedback.

**Comment by Rick-Kirkham** [comment]
Thanks. You have a good idea. I will make a work item for use to do this. When I've done that, I'll close this issue.
API reference pages, like this one, are generated from the source code. That's why there's no .md file for it.

**Comment by NT-D** [comment]
Thank you! Are make sense. Auto generation is good for APIs and.

**Comment by Rick-Kirkham** [comment]
OK. The fix is now in the published reference: https://docs.microsoft.com/en-us/javascript/api/office/office.error?view=office-js#code

So I'll close this issue. Thanks again for pointing out this very valuable improvement in the documentation.
