### ISSUE TITLE
Incorrect parameters in addOverlay sample

### ISSUE THREAD

**Issue by MichelLaplane** [OfficeDev/office-js-docs-reference#424]
There is an error in the sample. 
Instead of 
var overlayId=shape.view.addOverlay("Image", "Visio Online", "Center", "Center", 50, 50);
Tere must be

var overlayId=shape.view.addOverlay("Image", "Visio Online", "Center", "Middle",50,50);

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3b3f19e7-3957-257a-1f22-bb0e13720c42
* Version Independent ID: 90e7943a-72a7-e8df-7cbc-c51f257c37b2
* Content: [Visio.ShapeView class - Office Add-ins](https://docs.microsoft.com/en-us/javascript/api/visio/visio.shapeview?view=office-js)
* Content Source: [docs/docs-ref-autogen/visio/visio.shapeview.yml](https://github.com/OfficeDev/office-js-docs-reference/blob/live/docs/docs-ref-autogen/visio/visio.shapeview.yml)
* Product: **visio**
* Technology: **add-ins**
* GitHub Login: @o365devx
* Microsoft Alias: **o365devx**

**Comment by AlexJerabek** [comment]
Hi @MichelLaplane, 
Thanks for reporting this. I'll verify the information and submit a PR addressing this soon.

**Comment by AlexJerabek** [comment]
Hi @MichelLaplane, 
The suggested fix has been checked in. The live site should be updated in the next couple days. I'll close the issue. Thanks again for reporting this.
