### ISSUE TITLE
Mismatch in Title and description of page

### ISSUE THREAD

**Issue by rmillman** [OfficeDev/office-js-docs-reference#429]
Is this for the pivot table collection or for the fields collection for a pivot table?  The title and description don't match.Is this for the pivot table collection or for the fields collection for a pivot table?  The title and description don't match.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2e4db2db-2b15-e7cb-7ffd-e7705136ed8c
* Version Independent ID: 3d2550d1-67a4-b3ce-7e23-6165969e39ff
* Content: [Excel.PivotFieldCollection class - Office Add-ins](https://docs.microsoft.com/en-us/javascript/api/excel/excel.pivotfieldcollection?view=office-js#feedback)
* Content Source: [docs/docs-ref-autogen/excel/excel.pivotfieldcollection.yml](https://github.com/OfficeDev/office-js-docs-reference/blob/live/docs/docs-ref-autogen/excel/excel.pivotfieldcollection.yml)
* Product: **excel**
* Technology: **add-ins**
* GitHub Login: @o365devx
* Microsoft Alias: **o365devx**

**Comment by AlexJerabek** [comment]
Hi @rmillman, 
Thanks for reporting this. You're right that a PivotFieldCollection is not a collection of PivotTables. I'm going to work with engineering to get a better description of the PivotTable object model and update the docs accordingly..

**Comment by AlexJerabek** [comment]
Hi @rmillman, 
The fixes to the PivotTable documentation have been checked in (#432). They'll be merged into the master branch soon. Thanks again for reporting this issue. I'll close it for now, but feel free to reply to the thread with any additional comments.
