### ISSUE TITLE
Link to doc for return types

### ISSUE THREAD

**Issue by jakobpn** [OfficeDev/office-js-docs-reference#433]
Hi there, it would be awesome if this page had links to the documentation for the return types such as the Excel.WorksheetSingleClickedEventArgs type.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ecc449d8-02af-e5c1-9e6e-74fc9067ca62
* Version Independent ID: 6cc5351c-a26b-5d83-5b8b-df1b92ff3e3a
* Content: [Excel.Worksheet class - Office Add-ins](https://docs.microsoft.com/en-us/javascript/api/excel/excel.worksheet?view=office-js#onsingleclicked)
* Content Source: [docs/docs-ref-autogen/excel/excel.worksheet.yml](https://github.com/OfficeDev/office-js-docs-reference/blob/live/docs/docs-ref-autogen/excel/excel.worksheet.yml)
* Product: **excel**
* Technology: **add-ins**
* GitHub Login: @o365devx
* Microsoft Alias: **o365devx**

**Comment by AlexJerabek** [comment]
Hi @jakobpn, 
The lack of links in genericized types is a [known issue with our tooling chain] (https://github.com/Microsoft/web-build-tools/issues/867). In the meantime, I can help compensate by writing some sample code to showcase the return type's properties.

**Comment by jakobpn** [comment]
Glad to hear that it being tracked. I can find the return type in the table of contents on the left of the page, but a link to the doc would speed things up.

**Comment by AlexJerabek** [comment]
@jakobpn As an update, [this web-build-tools PR](https://github.com/microsoft/web-build-tools/pull/1337) will fix the linking issue. They still need to go through testing and approval, but I have verified the complex type linking will be fixed.

**Comment by wamaina** [comment]
@AlexJerabek, are there any updates on this?

**Comment by AlexJerabek** [comment]
@wamaina This is still blocked on https://github.com/microsoft/web-build-tools/pull/1337.

**Comment by AlexJerabek** [comment]
@jaokbpn This should be fixed by https://github.com/OfficeDev/office-js-docs-reference/pull/510. Those changes will make it to the live site soon. I'll close this issue now.
