### ISSUE TITLE
Remove "Preview" from TOC node for Custom Functions

### ISSUE THREAD

**Issue by kbrandl** [OfficeDev/office-js-docs-reference#444]
Since Custom Functions is no longer in Preview, `- Preview` should be removed from the API Reference TOC node that's currently labeled `Custom Functions - Preview`.

![image](https://user-images.githubusercontent.com/3019529/60833498-34c2bf80-a173-11e9-947d-b2baa44eb250.png)

**Comment by AlexJerabek** [comment]
Fixed with #447.
