### ISSUE TITLE
hostname values are incorrect

### ISSUE THREAD

**Issue by freerangeeggs** [OfficeDev/office-js-docs-reference#461]
The hostname field states that:
`A string that can be one of the following values: Outlook, Mac Outlook, OutlookIOS, or OutlookWebApp.`

This is not the case.
- When running Outlook on a Mac, the value returned is `Outlook`, not `Mac Outlook`. This is has been the case since 1.0
- Additionally, it can return OutlookAndroid.

I propose you change to:
`A string that can be one of the following values: Outlook, OutlookAndroid, OutlookIOS, or OutlookWebApp.`

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2d838795-4f5e-9903-383c-7680c247d683
* Version Independent ID: b823052b-5e15-cf10-6a22-45e79b3e49f3
* Content: [Office.Diagnostics interface - Office Add-ins](https://docs.microsoft.com/en-us/javascript/api/outlook_1_7/office.diagnostics?view=office-js)
* Content Source: [docs/docs-ref-autogen/outlook_1_7/office.diagnostics.yml](https://github.com/OfficeDev/office-js-docs-reference/blob/live/docs/docs-ref-autogen/outlook_1_7/office.diagnostics.yml)
* Product: **outlook**
* Technology: **add-ins**
* GitHub Login: @o365devx
* Microsoft Alias: **o365devx**

**Comment by AlexJerabek** [comment]
Hi @freerangeeggs,
Thanks for reporting this. I've tagged @ElizabethSamuel-MSFT, who will follow up with the fixes upstream in the reference documentation generation pipeline. Side-note, is #462 a duplicate issue?

**Comment by ElizabethSamuel-MSFT** [comment]
@freerangeeggs Thanks for raising this issue. I've created a PR and it should be merged soon.

**Comment by AlexJerabek** [comment]
Hi @freerangeeggs,
It's totally fine to raise the issue on a per page basis. It's always better to be thorough with documentation.
