### ISSUE TITLE
getSelectedRegExMatches() doesn't work in the Outlook 2013 desktop client

### ISSUE THREAD

**Issue by kakusharma** [OfficeDev/office-js-docs-reference#489]
Office.context.mailbox.item.getSelectedRegExMatches() returns null in Outlook 2013 desktop experience while returning an expected array of one match in the web client.
## Expected Behavior

Using contextual add-in, when I open the add-in in outlook 2013 desktop client, it should return the array of all the matched texts.

## Current Behavior

Instead of returning the list of the matched texts, its retunring me null in Outlook 2013, though is working fine on Outlook 365 (web). 

## Steps to Reproduce, or Live Example

1. Extension point in Manifest file: 
```
<ExtensionPoint xsi:type="DetectedEntity">
              <Label resid="AddIn.Title" />
              <SourceLocation resid="AddIn.WebApp" />
              <Rule xsi:type="RuleCollection" Mode="And">
                <Rule xsi:type="ItemIs" ItemType="Message" />
                <Rule xsi:type="ItemHasRegularExpressionMatch" PropertyName="BodyAsPlaintext" RegExName="BodyFilter" RegExValue="Click here to (Play|Poll|View)" Highlight="all" />
              </Rule>
</ExtensionPoint>
```
2. Debugged the issue with Outlook 2013 desktop client. The value returning was null, instead of the matching tests array

## Context

By opening the add-in with the text match, I am trying to load up a web page.

## Your Environment

* Platform [PC desktop, Mac, iOS, Office Online]: PC desktop
* Host [Excel, Word, PowerPoint, etc.]: Outlook 2013
* Office version number: 2013
* Operating System: Windows

**Comment by ElizabethSamuel-MSFT** [comment]
@kakusharma I've created pull requests to update the docs to note that contextual add-ins and DetectedEntity are available to clients that support requirement set 1.6 or later. Apologies for the confusion and let us know if we can update or clarify anything else related to this issue.

The changes should be merged and published soon (likely next week).

Thanks.

**Comment by ElizabethSamuel-MSFT** [comment]
@kakusharma These changes should now be live.

Thanks.
