### ISSUE TITLE
AttachHandler error

### ISSUE THREAD

**Issue by openmindgap** [OfficeDev/office-js-docs-reference#493]
"OSF is not defined"

Fix:
Visio.run(function(ctx)...
should be
Visio.run(session, function(ctx)...

as per this issue report https://github.com/OfficeDev/office-js-docs/issues/1375

Please make the documentation more verbose, for example where to call AddHandler()

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 337c4e45-a450-dbcf-71c2-3f72c4312c64
* Version Independent ID: c3907f0f-fb6a-3436-e194-4aef1dfff43a
* Content: [Visio.SelectionChangedEventArgs interface - Office Add-ins](https://docs.microsoft.com/en-us/javascript/api/visio/visio.selectionchangedeventargs?view=visio-js-1.1#feedback)
* Content Source: [docs/docs-ref-autogen/visio/visio/visio.selectionchangedeventargs.yml](https://github.com/OfficeDev/office-js-docs-reference/blob/live/docs/docs-ref-autogen/visio/visio/visio.selectionchangedeventargs.yml)
* Product: **visio**
* Technology: **add-ins**
* GitHub Login: @o365devx
* Microsoft Alias: **o365devx**

**Comment by AlexJerabek** [comment]
Hi @openmindgap,

I'll correct the error in the sample. I'll also investigate how to best improve the documentation. In the meantime, I'd recommend either asking about your Visio add-in's design on [StackOverflow](https://stackoverflow.com/questions/tagged/office-js)  using the "office-js" tag, looking at the eventing [documents](https://docs.microsoft.com/office/dev/add-ins/excel/excel-add-ins-events) and [samples](https://github.com/OfficeDev/office-js-snippets/tree/master/samples/excel/30-events) for Excel.

**Comment by AlexJerabek** [comment]
Hi @openmindgap,

I've corrected the sample code to use the `session` parameter. Those changes should be live in the documentation soon.

As for the larger sample on integrating the event handlers into your Visio add-in, we'll add that work to the documentation team's backlog. Off-hand, you should be able to add the handlers in your add-in's initialization logic. In [this sample](https://docs.microsoft.com/office/dev/add-ins/reference/overview/visio-javascript-reference-overview#get-started), that would be in the `initEmbeddedFrame` function. The community on [StackOverflow](https://stackoverflow.com/questions/tagged/office-js) should also be able to help you with the implementation details.

I'll go ahead and close this issue for now, as there's no further actions to take in this repo. Please respond to the thread if you disagree with the issue closure.
