### ISSUE TITLE
Error in code samples

### ISSUE THREAD

**Issue by Rick-Kirkham** [OfficeDev/office-js-docs-reference#504]
The code samples for the find and findOrNullObject methods have errors. The 2nd parameter just repeats the names of the three properties instead of assigning actually possible values. The line should look like this:
const foundRange = searchRange.findOrNullObject($("#searchText").text(), {
        completeMatch: false,
        matchCase: false,
        searchDirection: forward});

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 91eea38b-5448-965d-f938-c3d13db9dccf
* Version Independent ID: 09f81d36-d60d-3b72-467f-c9335c1e91d0
* Content: [Excel.Range class - Office Add-ins](https://docs.microsoft.com/en-us/javascript/api/excel/excel.range?view=excel-js-preview#find-text--criteria-)
* Content Source: [docs/docs-ref-autogen/excel/excel/excel.range.yml](https://github.com/OfficeDev/office-js-docs-reference/blob/live/docs/docs-ref-autogen/excel/excel/excel.range.yml)
* Product: **excel**
* Technology: **add-ins**
* GitHub Login: @o365devx
* Microsoft Alias: **o365devx**

**Comment by AlexJerabek** [comment]
Thanks @Rick-Kirkham. The upstream sample file uses duplicate names for the local and global variables. https://github.com/OfficeDev/office-js-snippets/pull/345 should fix this.

**Comment by AlexJerabek** [comment]
Fixed with #506. Closing the issue.

**Comment by neoblackcap** [comment]
The code sample for excel.Excel.Range.getOffsetRange methods has error. The later range.address should be "H3:J5" not "H3:K5"
