### ISSUE TITLE
CompleteMatch property description is missing crucial point

### ISSUE THREAD

**Issue by Rick-Kirkham** [OfficeDev/office-js-docs-reference#505]
The description of the completeMatch property should make clear that a partial match is a cell that *begins with the exact string that is passed as the search text*. So 'total rent charged' is a partial match of 'total rent'; but 'total unit rent' is not a partial match of 'total rent'. See this SO question for context: https://stackoverflow.com/questions/57776552/how-can-i-properly-implement-range-find-text-partial-match-search

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b57ab008-569e-a6c3-9fcd-e9798ebf33ad
* Version Independent ID: 8e108ad7-2b13-0401-aae1-bd24337d2f31
* Content: [Excel.SearchCriteria interface - Office Add-ins](https://docs.microsoft.com/en-us/javascript/api/excel/excel.searchcriteria?view=excel-js-preview)
* Content Source: [docs/docs-ref-autogen/excel/excel/excel.searchcriteria.yml](https://github.com/OfficeDev/office-js-docs-reference/blob/live/docs/docs-ref-autogen/excel/excel/excel.searchcriteria.yml)
* Product: **excel**
* Technology: **add-ins**
* GitHub Login: @o365devx
* Microsoft Alias: **o365devx**

**Comment by AlexJerabek** [comment]
@Rick-Kirkham. Thanks for raising this. I'll clarify the description. 

For the record, a partial match doesn't have to begin with the search text. 'unit' would partially match 'total unit rent'. The SO customer could possibly use 'rent' as their search parameter.

**Comment by AlexJerabek** [comment]
@Rick-Kirkham How does this sound?

"Specifies whether the match needs to be complete or partial. A complete match matches the entire contents of the cell. A partial match matches a substring within the content of the cell. Default is false (partial)."

**Comment by Rick-Kirkham** [comment]
@AlexJerabek That sounds fine. I recommend adding a couple of simple examples too.

**Comment by AlexJerabek** [comment]
Thanks @Rick-Kirkham. I've sumbitted a PR to Definitely Typed: https://github.com/DefinitelyTyped/DefinitelyTyped/pull/38137

**Comment by AlexJerabek** [comment]
This should be fixed by https://github.com/OfficeDev/office-js-docs-reference/pull/510. Closing the issue.
