### ISSUE TITLE
Missing numbering.xml in getOoxml()

### ISSUE THREAD

**Issue by MariamSamy0** [OfficeDev/office-js-docs-reference#508]
When using getOoxml() to get the document xml, the numbering.xml package is not included:

Word.run(function (context) {
var body = context.document.body;
var contentXML= body.getOoxml();

return context.sync().then(function () {
    console.log("Body OOXML contents: " + contentXML.value);
});  
})

The word/styles.xml, word/fontTable.xml, theme1.xml, etc. are included but without the numbering.xml I cann't recreate the number formats.!

**Comment by Rick-Kirkham** [comment]
We use the issues in this repo to track errors in the documentation. Please raise technical issues like this on StackOverflow. Be sure to tag your question `office-js`. Thanks.
