### ISSUE TITLE
Office.initialize() not available in excel on mac?

### ISSUE THREAD

**Issue by zakhan4** [OfficeDev/office-js-docs-reference#553]
Is this information correct which is given in the supported platforms for Office.initialize() on Excel Mac here: https://docs.microsoft.com/en-us/javascript/api/office?view=word-js-preview#office-initialize-reason-

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5530f30f-9d7b-a2e2-b30f-098556733c73
* Version Independent ID: 88f35bab-8f86-dd9b-66fa-43a554121a9b
* Content: [office package - Office Add-ins](https://docs.microsoft.com/en-us/javascript/api/office?view=word-js-preview#office-initialize-reason-)
* Content Source: [docs/docs-ref-autogen/office/office.yml](https://github.com/OfficeDev/office-js-docs-reference/blob/live/docs/docs-ref-autogen/office/office.yml)
* Product: **non-product-specific**
* Technology: **add-ins**
* GitHub Login: @o365devx
* Microsoft Alias: **o365devx**

**Comment by AlexJerabek** [comment]
Assigning @Rick-Kirkham to investigate.

**Comment by Rick-Kirkham** [comment]
Thanks for your interest in Office Add-ins. That Support details table is very old. I'm investigating whether it is still accurate.

**Comment by AlexJerabek** [comment]
@Rick-Kirkham  Was there any update on this investigation?

**Comment by Rick-Kirkham** [comment]
@AlexJerabek Still haven't heard from the relevant experts. I'll ping them again.

**Comment by Rick-Kirkham** [comment]
This was fixed with https://github.com/DefinitelyTyped/DefinitelyTyped/pull/44941. It should be in the published help in a few days.
