### ISSUE TITLE
Office.context.displayLanguage not available on Mac?

### ISSUE THREAD

**Issue by zakhan4** [OfficeDev/office-js-docs-reference#554]
Is this information correct which is given in the supported platforms for Office.context.displayLanguage on Excel Mac here: https://docs.microsoft.com/en-us/javascript/api/office/office.context?view=word-js-preview#displaylanguage

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c1424764-ecfa-4f54-7e20-a873e9f52698
* Version Independent ID: 3f369a22-39b1-06b1-faea-eac921097824
* Content: [Office.Context interface - Office Add-ins](https://docs.microsoft.com/en-us/javascript/api/office/office.context?view=word-js-preview#displaylanguage)
* Content Source: [docs/docs-ref-autogen/office/office/office.context.yml](https://github.com/OfficeDev/office-js-docs-reference/blob/live/docs/docs-ref-autogen/office/office/office.context.yml)
* Product: **non-product-specific**
* Technology: **add-ins**
* GitHub Login: @o365devx
* Microsoft Alias: **o365devx**

**Comment by Rick-Kirkham** [comment]
Thanks for your interest in Office Add-ins. That Support details table is very old. I'm investigating whether it is still accurate.

**Comment by Rick-Kirkham** [comment]
I'm treating this as part of issue https://github.com/OfficeDev/office-js-docs-reference/issues/553 , so I'll close this one.
