### ISSUE TITLE
Table.name documentation should include a more precise definition of allowable strings

### ISSUE THREAD

**Issue by wandyezj** [OfficeDev/office-js-docs-reference#555]
Table names;
- must be unique in the workbook
- must start with and _ or letter
- must __not__ include a space (or other unallowable character?)

It would be best to provide a regex that precisely describes what characters are allowed.

The error message is quite vague and it took quite a bit of experimentation to figure out why the API call was failing.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 89bd8292-dcf3-4a88-2db9-acdd0b1e32ee
* Version Independent ID: d540c400-d417-bb77-bbb0-606ae1921b06
* Content: [Excel.Table class - Office Add-ins](https://docs.microsoft.com/en-us/javascript/api/excel/excel.table?view=excel-js-preview)
* Content Source: [docs/docs-ref-autogen/excel/excel/excel.table.yml](https://github.com/OfficeDev/office-js-docs-reference/blob/live/docs/docs-ref-autogen/excel/excel/excel.table.yml)
* Product: **excel**
* Technology: **add-ins**
* GitHub Login: @o365devx
* Microsoft Alias: **o365devx**

**Comment by AlexJerabek** [comment]
Hi @wandyezj, 
I've created an [internal item](https://office.visualstudio.com/OC/_workitems/edit/3775916) to document the table name setting behavior. Thanks!

**Comment by AlexJerabek** [comment]
Upstream change: https://github.com/DefinitelyTyped/DefinitelyTyped/pull/40867

**Comment by AlexJerabek** [comment]
I missed updating the thread a couple weeks ago. This change is live in the docs.
