### ISSUE TITLE
Sample needs to also load color

### ISSUE THREAD

**Issue by KoenZomers** [OfficeDev/office-js-docs-reference#556]
The sample on this page outputing this string to the console: "Property values of the first content control:" lacks loading the color property which it uses to write to the console thereby throwing an exception. Just add loading the color property (so not font\color) to the code and it works well.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 43560bca-435b-4e18-f437-fafe26926cd2
* Version Independent ID: 0a843707-89d9-1738-5693-a6d4cdf0d008
* Content: [Word.ContentControlCollection class - Office Add-ins](https://docs.microsoft.com/en-us/javascript/api/word/word.contentcontrolcollection?view=word-js-preview)
* Content Source: [docs/docs-ref-autogen/word/word/word.contentcontrolcollection.yml](https://github.com/OfficeDev/office-js-docs-reference/blob/live/docs/docs-ref-autogen/word/word/word.contentcontrolcollection.yml)
* Product: **word**
* Technology: **add-ins**
* GitHub Login: @o365devx
* Microsoft Alias: **o365devx**

**Comment by AlexJerabek** [comment]
Thanks for reporting this @KoenZomers. I'll fix the sample to properly load the `color` property.
