### ISSUE TITLE
Snippet for MessageRead.internetHeaders is present, but that property isn't

### ISSUE THREAD

**Issue by AlexJerabek** [OfficeDev/office-js-docs-reference#560]
## Article URL
https://docs.microsoft.com/en-us/javascript/api/outlook/office.messageread?view=outlook-js-preview

## Issue
There's the a snippet for `MessageRead.internetHeaders` but no `MessageRead.internetHeaders`. Either the snippet is pointing to the wrong location or the property should be in the type definitions.

**Comment by ElizabethSamuel-MSFT** [comment]
@AlexJerabek Where is the snippet?

**Comment by AlexJerabek** [comment]
@ElizabethSamuel-MSFT docs/code-snippets/outlook-snippets.yaml

**Comment by ElizabethSamuel-MSFT** [comment]
@AlexJerabek Thanks for pointing this out. MessageRead no longer supports the internetHeaders property and getAllInternetHeadersAsync method replaced it. I'll remove this snippet.
