### ISSUE TITLE
O should be capitalized in office.context.ui.messageParent 

### ISSUE THREAD

**Issue by lxvii-github** [OfficeDev/office-js-docs-reference#569]
Clearly it is a typo

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: df1fde12-982a-2f60-54ca-375968a29f33
* Version Independent ID: 7ed56398-e6be-f624-f76d-8982c36fa81a
* Content: [Office.UI interface - Office Add-ins](https://docs.microsoft.com/en-us/javascript/api/office/office.ui?view=word-js-preview#feedback)
* Content Source: [docs/docs-ref-autogen/office/office/office.ui.yml](https://github.com/OfficeDev/office-js-docs-reference/blob/live/docs/docs-ref-autogen/office/office/office.ui.yml)
* Product: **non-product-specific**
* Technology: **add-ins**
* GitHub Login: @o365devx
* Microsoft Alias: **o365devx**

**Comment by ElizabethSamuel-MSFT** [comment]
@lxvii-github Thanks for pointing this out. We'll get this updated.

Thanks.

**Comment by ElizabethSamuel-MSFT** [comment]
Upstream change in PR https://github.com/DefinitelyTyped/DefinitelyTyped/pull/40637. Once that's merged, updates should flow into this repo (office-js-docs-reference) soon after that.

**Comment by ElizabethSamuel-MSFT** [comment]
@lxvii-github This has been fixed in PR https://github.com/OfficeDev/office-js-docs-reference/pull/570. The changes should be published soon. Thanks again for raising this issue.

**Comment by ElizabethSamuel-MSFT** [comment]
@lxvii-github The fix should be live now so I'll go ahead and close this issue now.

Thanks.
