### ISSUE TITLE
Error in code samples

### ISSUE THREAD

**Issue by neoblackcap** [OfficeDev/office-js-docs-reference#572]
The code sample for excel.Excel.Range.getOffsetRange methods has error. The later range.address should be "H3:J5" not "H3:K5"

---
#### 文档详细信息

⚠ *请勿编辑此部分。 docs.microsoft.com ➟ GitHub 问题链接必须具有此部分。*

* ID: 91eea38b-5448-965d-f938-c3d13db9dccf
* Version Independent ID: 09f81d36-d60d-3b72-467f-c9335c1e91d0
* Content: [Excel.Range class - Office Add-ins](https://docs.microsoft.com/zh-cn/javascript/api/excel/excel.range?view=excel-js-preview#getoffsetrange-rowoffset--columnoffset-)
* Content Source: [docs/docs-ref-autogen/excel/excel/excel.range.yml](https://github.com/OfficeDev/office-js-docs-reference/blob/live/docs/docs-ref-autogen/excel/excel/excel.range.yml)
* Product: **excel**
* Technology: **add-ins**
* GitHub Login: @o365devx
* Microsoft Alias: **o365devx**

**Comment by AlexJerabek** [comment]
Thanks for reporting this @neoblackcap. I'll look into the sample and make the appropriate changes.
