### ISSUE TITLE
should be an option for the color of the highlighted content. 

### ISSUE THREAD

**Issue by beingsagir** [OfficeDev/office-js-docs-reference#580]
i am not talking abt changint the color of the content but the color of selection. which is always grey.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4601bd49-ceb7-7081-517a-716236f5f9df
* Version Independent ID: cbeeca05-b501-3be5-c7e7-b7825aae8e57
* Content: [Word.SelectionMode enum - Office Add-ins](https://docs.microsoft.com/en-us/javascript/api/word/word.selectionmode?view=word-js-preview#feedback)
* Content Source: [docs/docs-ref-autogen/word/word/word.selectionmode.yml](https://github.com/OfficeDev/office-js-docs-reference/blob/live/docs/docs-ref-autogen/word/word/word.selectionmode.yml)
* Product: **word**
* Technology: **add-ins**
* GitHub Login: @o365devx
* Microsoft Alias: **o365devx**

**Comment by AlexJerabek** [comment]
Hi @beingsagir 

Thank you for your interest in Office Add-ins and your desire to see the platform expand. I'd recommend posting this feature request on [UserVoice](https://officespdev.uservoice.com/). That way, the community can upvote it and help us prioritize our future releases. 

I'm going to close this issue, as this repo is for the Office Add-ins reference documentation and issues with that content. Feel free to comment on this thread with the link to your UserVoice request to help increase visibility.
