### ISSUE TITLE
Should Outlook.SourceProperty be listed under MailboxEnums?

### ISSUE THREAD

**Issue by AlexJerabek** [OfficeDev/office-js-docs-reference#589]
This enum is under the base package, not MailboxEnums. Is that correct?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f571c68c-83ca-6281-4292-7701ddcccf40
* Version Independent ID: eee8ec7d-7515-ab97-c228-c1b01390c30f
* Content: [Office.SourceProperty enum - Office Add-ins](https://docs.microsoft.com/en-us/javascript/api/outlook/office.sourceproperty?view=outlook-js-preview#feedback)
* Content Source: [docs/docs-ref-autogen/outlook/outlook/office.sourceproperty.yml](https://github.com/OfficeDev/office-js-docs-reference/blob/live/docs/docs-ref-autogen/outlook/outlook/office.sourceproperty.yml)
* Product: **outlook**
* Technology: **add-ins**
* GitHub Login: @o365devx
* Microsoft Alias: **o365devx**

**Comment by ElizabethSamuel-MSFT** [comment]
@AlexJerabek Thanks for raising this issue. The documentation has been updated and the fix should be published soon.

Thanks.
