### ISSUE TITLE
isSetSupported has unspecified names.

### ISSUE THREAD

**Issue by wandyezj** [OfficeDev/office-js-docs-reference#603]
What names and versions are available?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5ca7e2a8-0ed0-80a1-15e6-7dda0d7616b9
* Version Independent ID: b2ed2c73-bfbe-7b82-2ffe-687db9e9a538
* Content: [OfficeRuntime.ApiInformation interface - Office Add-ins](https://docs.microsoft.com/en-us/javascript/api/office-runtime/officeruntime.apiinformation?view=excel-js-preview#feedback)
* Content Source: [docs/docs-ref-autogen/excel/office-runtime/officeruntime.apiinformation.yml](https://github.com/OfficeDev/office-js-docs-reference/blob/live/docs/docs-ref-autogen/excel/office-runtime/officeruntime.apiinformation.yml)
* Product: **non-product-specific**
* Technology: **add-ins**
* GitHub Login: @o365devx
* Microsoft Alias: **o365devx**

**Comment by AlexJerabek** [comment]
Hi @wandyezj, 
Requirement sets are listed on the [Office versions and requirement sets](https://docs.microsoft.com/office/dev/add-ins/develop/office-versions-and-requirement-sets).
