### ISSUE TITLE
Is OfficeRuntime.Storage only available for custom functions?

### ISSUE THREAD

**Issue by wandyezj** [OfficeDev/office-js-docs-reference#604]
I see that that API Set is CustomFunctionsRuntime 1.1, is this API only available for Excel and Custom Functions?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e8b9b4ae-c0e2-6ca5-53b1-5fe4a6901dbb
* Version Independent ID: 7a691d06-b135-c724-db66-25af1341d7a1
* Content: [OfficeRuntime.Storage interface - Office Add-ins](https://docs.microsoft.com/en-us/javascript/api/office-runtime/officeruntime.storage?view=excel-js-preview)
* Content Source: [docs/docs-ref-autogen/excel/office-runtime/officeruntime.storage.yml](https://github.com/OfficeDev/office-js-docs-reference/blob/live/docs/docs-ref-autogen/excel/office-runtime/officeruntime.storage.yml)
* Product: **non-product-specific**
* Technology: **add-ins**
* GitHub Login: @o365devx
* Microsoft Alias: **o365devx**

**Comment by AlexJerabek** [comment]
Hi @wandyezj 
Yes. Please see [Custom Functions requirement sets](https://docs.microsoft.com/office/dev/add-ins/excel/custom-functions-requirement-sets) for details.
