### ISSUE TITLE
Embed Excel Example

### ISSUE THREAD

**Issue by Andrew-AnalysisPlace** [OfficeDev/office-js-docs-reference#605]
If it is possible, please provide an example of how to embed an Excel workbook and then control it via Office.js. I can only find Visio examples (https://docs.microsoft.com/en-us/office/dev/add-ins/reference/overview/visio-javascript-reference-overview). Or if Excel is not supported, please indicate what hosts are (or will likely be) supported.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a9fca5cf-7971-3c18-c6ac-e59a9f2167a4
* Version Independent ID: 62b996d4-32f1-6c0b-1715-00b1be2a0f89
* Content: [OfficeExtension.EmbeddedSession class - Office Add-ins](https://docs.microsoft.com/en-us/javascript/api/office/officeextension.embeddedsession?view=excel-js-preview#feedback)
* Content Source: [docs/docs-ref-autogen/office/office/officeextension.embeddedsession.yml](https://github.com/OfficeDev/office-js-docs-reference/blob/live/docs/docs-ref-autogen/office/office/officeextension.embeddedsession.yml)
* Product: **non-product-specific**
* Technology: **add-ins**
* GitHub Login: @o365devx
* Microsoft Alias: **o365devx**

**Comment by AlexJerabek** [comment]
Hi @Andrew-AnalysisPlace, 

Currently, the embed scenario that’s described in the [Visio JavaScript API overview]( https://docs.microsoft.com/office/dev/add-ins/reference/overview/visio-javascript-reference-overview) article is only supported for Visio. I am not aware of any plans to expand this feature to other hosts, such as Excel, in the near future. I’d suggest that you post this feature request to the [Office Developer UserVoice]( https://officespdev.uservoice.com) site. The product team uses UserVoice to prioritize and plan future enhancements to the Office Add-ins platform.

I'll close this issue, as there's no actions to be taken with the documentation. Please respond to the thread or raise a new issue if you have further questions.
