### ISSUE TITLE
Type definition of RecipientsChangedEventArgs is wrong

### ISSUE THREAD

**Issue by amiram** [OfficeDev/office-js-docs-reference#607]
## Expected Behavior
When you get the RecipientsChanged event in outlook, the object looks like:
```
interface RecipientsChangedEventArgs {
    changedRecipientFields: {
        to: boolean;
        cc: boolean;
        bcc: boolean;
    }
}
```
## Current Behavior
In the ts definition file, the RecipientsChangedEventArgs looks like:
```
interface RecipientsChangedEventArgs {
     changedRecipientsFields: {
        optionalAttendees: boolean; 
        requiredAttendees: boolean; 
        resources: boolean;
     }
}
```

I can make a pull request to fix the ts file if you'd like me to.

## Your Environment

* Platform [PC desktop, Mac, iOS, Office Online]: PC Desktop
* Host [Excel, Word, PowerPoint, etc.]: Outlook
* Office version number: 365 monthly
* Operating System: Win10

**Comment by AlexJerabek** [comment]
This has been addressed in the documentation. The fix has been checked in to the master branch all will be made live in the coming days.

I'll close the issue, but please respond if there are further concerns. Thanks!
