### ISSUE TITLE
Excel.range.getImage() on mac

### ISSUE THREAD

**Issue by janisdd** [OfficeDev/office-js-docs-reference#631]
So far I've enjoyed the docs and usage of office js. 
However, I tried using this function `range.getImage()` on a mac (excel 16.34) and it's not working properly. There exists already an issue here https://github.com/OfficeDev/office-js/issues/235.

I would suggest that there should exists some kind of reference to this issue in the docs as this function cannot be used properly on some platforms (at least mac).

I've looked through some files (.yml) and found that some functions have a `Support details` in the `remarks` section that could be used for that?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 91eea38b-5448-965d-f938-c3d13db9dccf
* Version Independent ID: 09f81d36-d60d-3b72-467f-c9335c1e91d0
* Content: [Excel.Range class - Office Add-ins](https://docs.microsoft.com/en-us/javascript/api/excel/excel.range?view=excel-js-preview)
* Content Source: [docs/docs-ref-autogen/excel/excel/excel.range.yml](https://github.com/OfficeDev/office-js-docs-reference/blob/live/docs/docs-ref-autogen/excel/excel/excel.range.yml)
* Product: **excel**
* Technology: **add-ins**
* GitHub Login: @o365devx
* Microsoft Alias: **o365devx**

**Comment by AlexJerabek** [comment]
Hi @janisdd, 
Thank you for reporting this documentation gap. I'll add a note about the issue with `Range.getImage` on Mac in [DefinitelyTyped](https://github.com/DefinitelyTyped/DefinitelyTyped/), which is the source of truth for the Excel JavaScript documentation.

**Comment by AlexJerabek** [comment]
Upstream change: https://github.com/DefinitelyTyped/DefinitelyTyped/pull/42361

**Comment by AlexJerabek** [comment]
Thanks again for reporting this @janisdd. The documentation changes should be merged into the live branch and displayed on the docs site shortly. Please let us know if you spot any other issues.
