### ISSUE TITLE
Examples request for SharedProperties interface

### ISSUE THREAD

**Issue by Levure** [OfficeDev/office-js-docs-reference#637]
Hello the team !

I can't find any of the listed properties (of SharedProperties interface) in `Office.context.mailbox.item`, I must miss something. Can you, please, add some examples ?

I already checked that my add-in uses the Outlook Javascript API 1.8 :
`Office.context.requirements.isSetSupported('Mailbox', '1.8')` returns true

Can you also provide an example to show how we can check if a mailbox item is in my own mailbox or is in a SharedFolder ?

Many thanks in advance !
Regards,

---
#### Détails du document

⚠ *Ne pas modifier cette section. C’est obligatoire pour docs.microsoft.com ➟ Liaison des problèmes GitHub.*

* ID: de460e6f-21a3-7ae3-8be5-80f5314d1a15
* Version Independent ID: 2d6120e6-b783-c1e4-5d0c-a12ee0b42d58
* Content: [Office.SharedProperties interface - Office Add-ins](https://docs.microsoft.com/fr-fr/javascript/api/outlook/office.sharedproperties?view=outlook-js-1.8)
* Content Source: [docs/docs-ref-autogen/outlook_1_8/outlook/office.sharedproperties.yml](https://github.com/OfficeDev/office-js-docs-reference/blob/live/docs/docs-ref-autogen/outlook_1_8/outlook/office.sharedproperties.yml)
* Product: **outlook**
* Technology: **add-ins**
* GitHub Login: @o365devx
* Microsoft Alias: **o365devx**

**Comment by AlexJerabek** [comment]
Hi @Levure, 
Thank you for the sample request. I'll tag @ElizabethSamuel-MSFT to add the appropriate code samples.

**Comment by Levure** [comment]
I don't know how I found it, but I finally found one code sample on https://docs.microsoft.com/en-us/javascript/api/outlook/office.messageread?view=outlook-js-preview#getsharedpropertiesasync-options--callback-

May I suggest to add a link to that page on https://docs.microsoft.com/en-us/javascript/api/outlook/office.sharedproperties?view=outlook-js-1.8 ?

Regards,

**Comment by ElizabethSamuel-MSFT** [comment]
@Levure I'm glad you found a code sample. The [article on delegate access](https://docs.microsoft.com/office/dev/add-ins/outlook/delegate-access) may also be helpful.

Thanks for the suggestion to add code samples to the SharedProperties object.

**Comment by ElizabethSamuel-MSFT** [comment]
@Levure We've updated the documentation and the fix should be published soon (most likely today).

Thanks.
