### ISSUE TITLE
Any way of using Word APIs for Powerpoint add in?

### ISSUE THREAD

**Issue by safwatalikhan** [OfficeDev/office-js-docs-reference#644]
The powerpoint api is very limited and the documentation suggests to use common api for ppt add ins. But is there a way I can use Word API in a powerpoint add in? There are many common functionalities, such as: alignment, indentation modification that is available in Word API but not in common. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5530f30f-9d7b-a2e2-b30f-098556733c73
* Version Independent ID: 88f35bab-8f86-dd9b-66fa-43a554121a9b
* Content: [office package - Office Add-ins](https://docs.microsoft.com/en-us/javascript/api/office?view=common-js)
* Content Source: [docs/docs-ref-autogen/office/office.yml](https://github.com/OfficeDev/office-js-docs-reference/blob/live/docs/docs-ref-autogen/office/office.yml)
* Product: **non-product-specific**
* Technology: **add-ins**
* GitHub Login: @o365devx
* Microsoft Alias: **o365devx**

**Comment by AlexJerabek** [comment]
Hi @safwatalikhan, 

Thank you for your question. The Word APIs are specific to Word and cannot be used in any other host. You can read about the differences between the Host-specific APIs and the Common APIs [here](https://docs.microsoft.com/office/dev/add-ins/develop/understanding-the-javascript-api-for-office?view=excel-js-preview#api-models).

I'd recommend going to UserVoice and voting for [this PowerPoint API suggestion](https://officespdev.uservoice.com/forums/224641-feature-requests-and-feedback/suggestions/33200554-powerpoint-api). Community input helps us prioritize new feature work.

I'm going to close this issue, as there's no actionable item we can take in the reference documentation.
