### ISSUE TITLE
Detail what should be used for secure storage instead of just what shouldn't

### ISSUE THREAD

**Issue by gavingmiller** [OfficeDev/office-js-docs-reference#712]
Your documentation reads as follows:

> While the Outlook Add-in API limits access to these settings to only the add-in that created them, these settings should not be considered secure storage. They can be accessed by Exchange Web Services or Extended MAPI. They should not be used to store sensitive information such as user credentials or security tokens.

What would be really helpful is if you specified *what should* be used for secure storage if roamingSettings isn't the correct interface.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f95ff716-788a-639a-32ae-b0e90b467424
* Version Independent ID: a5b370a0-ec65-7e19-4748-20d3235eacda
* Content: [Office.RoamingSettings interface - Office Add-ins](https://docs.microsoft.com/en-us/javascript/api/outlook/office.roamingsettings?view=outlook-js-1.5)
* Content Source: [docs/docs-ref-autogen/outlook_1_5/outlook/office.roamingsettings.yml](https://github.com/OfficeDev/office-js-docs-reference/blob/live/docs/docs-ref-autogen/outlook_1_5/outlook/office.roamingsettings.yml)
* Product: **outlook**
* Technology: **add-ins**
* GitHub Login: @o365devx
* Microsoft Alias: **o365devx**

**Comment by ElizabethSamuel-MSFT** [comment]
@gavingmiller Thanks for your question.

@exextoc Any guidance?

Thanks.

**Comment by exextoc** [comment]
@gavingmiller What is the scenario for which you wish to store secure values?

A common scenario is authentication, and several authentication options are [described here](https://docs.microsoft.com/en-us/office/dev/add-ins/outlook/authentication).

**Comment by gavingmiller** [comment]
I'm looking to store an authentication token retrieved via OAuth2. Clio's (company I develop the add-on for) add-on connects and authenticates back to our service via the OAuth2 workflow. Specifically we use the `Authorization Code` grant type. I'm looking to store the token retrieved from Clio in a secure fashion. Because the `roamingSettings` isn't the correct place, I'm not sure what is. 😕 

The authentication documentation you're pointing to has the `getUserIdentityTokenAsync` but doesn't have a setter associated with it. So I either don't understand how that endpoint is meant to work to store our token, or I'm not setting up authentication correctly. 

Let me know if you need more info on how we're trying to do this in case we're looking at this incorrectly. Thanks!

**Comment by exextoc** [comment]
[getUserIdentityTokenAsync ](https://docs.microsoft.com/en-us/javascript/api/outlook/office.mailbox?view=outlook-js-preview#getuseridentitytokenasync-callback--usercontext-) retrieves a valid token identifying the user and the Office Add-in. One the token is obtained, it can be validated and mapped to a user in your backend. Documentation for this can be found [here](https://docs.microsoft.com/en-us/office/dev/add-ins/outlook/authenticate-a-user-with-an-identity-token#map-the-token-to-a-user-in-your-backend).

**Comment by ElizabethSamuel-MSFT** [comment]
@exextoc Thanks for your response.

@gavingmiller It seems like your questions have been answered so I'll close this issue now. However, if that's not the case, comment on this issue and we can reopen it.

Thanks.
