### ISSUE TITLE
Tokens obtained via the getCallbackTokenAsync methods will not allow you to make delegate calls to EWS.

### ISSUE THREAD

**Issue by davyarris** [OfficeDev/office-js-docs-reference#724]
Hi There,

Having spent so much time going back and forth on this issue I feel like it would be a good idea to outline under the getCallbackTokenAsync methods that the token returned are not fully functional for EWS in that any attempt to access a delegated resource (such as a calendar or inbox) will fail.
This would not be such a surprise if there weren't articles out there such as https://docs.microsoft.com/en-us/exchange/client-developer/exchange-web-services/delegate-access-and-ews-in-exchange 
and
https://docs.microsoft.com/en-us/exchange/client-developer/exchange-web-services/how-to-access-email-as-a-delegate-by-using-ews-in-exchange#get-update-or-delete-email-items-as-a-delegate-by-using-ews
which goes to great lengths outlining how delegate access is possible via EWS but fails to mention anything about access from Outlook Add-ins.
The only way I was able to identify that this wasn't possible was to try it. It was then I found the answers buried deep in a number of forums.
This disconnect has been the source of much pain for me and I believe many others.

Cheers

Dave

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 74a475fa-6d35-07f2-c261-08b070f99c9a
* Version Independent ID: fe7e0914-4be1-1b8c-d173-6a3329caf82e
* Content: [Office.Mailbox interface - Office Add-ins](https://docs.microsoft.com/en-us/javascript/api/outlook/office.mailbox?view=outlook-js-preview)
* Content Source: [docs/docs-ref-autogen/outlook/outlook/office.mailbox.yml](https://github.com/OfficeDev/office-js-docs-reference/blob/live/docs/docs-ref-autogen/outlook/outlook/office.mailbox.yml)
* Product: **outlook**
* Technology: **add-ins**
* GitHub Login: @o365devx
* Microsoft Alias: **o365devx**

**Comment by ElizabethSamuel-MSFT** [comment]
@davyarris Sorry that you faced these issues while using this API and we appreciate your raising this issue. Can you share the configurations where you tried this (e.g., Windows, Mac, browser)?

Thanks.

**Comment by ElizabethSamuel-MSFT** [comment]
@exextoc Can you provide your take on this? Does this apply across all clients?

Thanks.

**Comment by ElizabethSamuel-MSFT** [comment]
@davyarris We've started by clarifying in the delegate access article the interaction with EWS and REST. We're still investigating this to determine further updates.

**Comment by ElizabethSamuel-MSFT** [comment]
@davyarris We're updating the documentation on getCallbackTokenAsync to point to guidance in the delegate access article. Those changes should be published soon so closing this issue.

If you face further issues with this, let us know and we can reactivate this issue.

Thanks.
