### ISSUE TITLE
EventHandlerResult.remove should mention need to include context

### ISSUE THREAD

**Issue by fds-ssg** [OfficeDev/office-js-docs-reference#730]
The remove method fails silently unless you follow the advice given on a different page unrelated to working with events:

>Removing event handlers
>
>Event handlers must be removed using the same RequestContext in which they were added. If you need your add-in to remove an event handler while running, you'll need to store the context object used to add the handler.
https://docs.microsoft.com/en-us/office/dev/add-ins/develop/common-coding-issues#removing-event-handlers

Would it be possible to include this valuable info anywhere that a remove method exists?  If it had been here, it would have saved me quite a few hours of troubleshooting.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ef1ee6c5-17e5-f1b9-5b76-9ae2ed564ddc
* Version Independent ID: 6f09c2b8-4537-27ab-9701-5eed4008df5b
* Content: [OfficeExtension.EventHandlers class - Office Add-ins](https://docs.microsoft.com/en-us/javascript/api/office/officeextension.eventhandlers?view=word-js-preview)
* Content Source: [docs/docs-ref-autogen/office/office/officeextension.eventhandlers.yml](https://github.com/OfficeDev/office-js-docs-reference/blob/live/docs/docs-ref-autogen/office/office/officeextension.eventhandlers.yml)
* Product: **non-product-specific**
* Technology: **add-ins**
* GitHub Login: @o365devx
* Microsoft Alias: **o365devx**

**Comment by AlexJerabek** [comment]
Hi @fds-ssg, 
I'm sorry to hear about your struggles with removing event handlers. We'll get that link in the `EventHandler` documentation and work on improving the experience.

**Comment by fds-ssg** [comment]
Thanks @AlexJerabek , it was very helpful that the note about event handler context was documented to begin with, and will be even more helpful I think to include it in other relevant locations.

**Comment by AlexJerabek** [comment]
@fds-ssg I've added a link to the behavior note from the `EventHandler.remove` method. The changes will be moved to the live branch in the next couple days. If you have any other suggestions for how to improve the discoverability of the documentation, please let me know. Thanks!
