### ISSUE TITLE
What does `namespaceMapping` refer to?

### ISSUE THREAD

**Issue by algomaster99** [OfficeDev/office-js-docs-reference#738]
I had one doubt in an API. Since this API is in preview version, I couldn't find resources but what exactly are `namespaceMappings` here - https://docs.microsoft.com/en-us/javascript/api/word/word.customxmlpart?view=word-js-preview#query-xpath--namespacemappings-?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 20b7edd6-b666-2837-9ce0-509611dcf783
* Version Independent ID: 86c0a6db-65a9-2f41-9f9c-b856529d598e
* Content: [Word.CustomXmlPart class - Office Add-ins](https://docs.microsoft.com/en-us/javascript/api/word/word.customxmlpart?view=word-js-preview#query-xpath--namespacemappings-)
* Content Source: [docs/docs-ref-autogen/word/word/word.customxmlpart.yml](https://github.com/OfficeDev/office-js-docs-reference/blob/live/docs/docs-ref-autogen/word/word/word.customxmlpart.yml)
* Product: **word**
* Technology: **add-ins**
* GitHub Login: @o365devx
* Microsoft Alias: **o365devx**

**Comment by Rick-Kirkham** [comment]
@jeremy-msft 
The Word.CustomXmlPart object has some methods that take a parameter called `namespaceMapping`. The doc does not really explain what this parameter does. Also, the doc says that the type of the parameter is `any` but that is almost certainly wrong. It must be some type more specific than that, like maybe string or array of strings. Could you provide a seed description of what this parameter does and its type? I can then update the doc.

**Comment by Rick-Kirkham** [comment]
@JuaneloJuanelo 
Looks like this should have been assigned to you (temporarily).

**Comment by algomaster99** [comment]
I asked the same question on StackOverflow. I think I have received an answer which works for me. Here is the link - https://stackoverflow.com/a/62777329/11751642
If you need me to submit a PR for that, let me know.

**Comment by Rick-Kirkham** [comment]
See https://www.typescriptlang.org/docs/handbook/advanced-types.html#index-types-and-index-signatures also for the signature of the new interface.

**Comment by Rick-Kirkham** [comment]
The source file for the documentation of the methods that have a `namespaceMapping` parameter has been changed. It may take a couple of weeks before the corrected description is in the public reference documentation. It may take longer before the data type of the parameter is changed from `any` to something more specific.
