### ISSUE TITLE
Lack of documentation for Common API Office.File function

### ISSUE THREAD

**Issue by naterush** [OfficeDev/office-js-docs-reference#739]
[Enter feedback here]

---
#### Document Details
I'm looking to use the Office.File function in Excel 2013; however, I cannot tell which versions of Excel specifically this function works on.

The [Common API Requirement](https://docs.microsoft.com/en-us/office/dev/add-ins/reference/requirement-sets/office-add-in-requirement-sets) sets do not mention this interface specifically, and it is also not mentioned in the Office.File description page. 

Some documentation here would be super helpful -- thanks!

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 19725696-ef74-1668-5a3e-8bc2bfef81d8
* Version Independent ID: 53436d1d-c281-edfe-d128-6609e62600a1
* Content: [Office.File interface - Office Add-ins](https://docs.microsoft.com/en-us/javascript/api/office/office.file?view=common-js)
* Content Source: [docs/docs-ref-autogen/office/office/office.file.yml](https://github.com/OfficeDev/office-js-docs-reference/blob/live/docs/docs-ref-autogen/office/office/office.file.yml)
* Product: **non-product-specific**
* Technology: **add-ins**
* GitHub Login: @o365devx
* Microsoft Alias: **o365devx**

**Comment by ElizabethSamuel-MSFT** [comment]
@naterush Thanks for asking about this. There is a [File requirement set](https://docs.microsoft.com/office/dev/add-ins/reference/requirement-sets/office-add-in-requirement-sets#file) which indicates support for `File.closeAsync` and `File.getSliceAsync`. That should mean the File object is also supported by the Office hosts listed in that section.

Also, in the [Excel section of the Add-ins availability](https://docs.microsoft.com/office/dev/add-ins/overview/office-add-in-availability#excel) page, the File requirement set should be supported by the 2013 version on Windows.

I'll close this for now. However, if you still have questions about this, let us know and we can reopen this issue.

Thanks.

**Comment by naterush** [comment]
Great, thank you so much!
