### ISSUE TITLE
Please describe the meaning of SelectionMode Enums in more detail

### ISSUE THREAD

**Issue by calbrecht** [OfficeDev/office-js-docs-reference#744]
The current state of doc is not helpful at all.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4601bd49-ceb7-7081-517a-716236f5f9df
* Version Independent ID: cbeeca05-b501-3be5-c7e7-b7825aae8e57
* Content: [Word.SelectionMode enum - Office Add-ins](https://docs.microsoft.com/en-us/javascript/api/word/word.selectionmode?view=word-js-preview)
* Content Source: [docs/docs-ref-autogen/word/word/word.selectionmode.yml](https://github.com/OfficeDev/office-js-docs-reference/blob/live/docs/docs-ref-autogen/word/word/word.selectionmode.yml)
* Product: **word**
* Technology: **add-ins**
* GitHub Login: @o365devx
* Microsoft Alias: **o365devx**

**Comment by AlexJerabek** [comment]
Hi @calbrecht, 
Thanks for reporting this. I'll work with the product team to get helpful descriptions on the page.

**Comment by AlexJerabek** [comment]
Hi @calbrecht,

I've updated the documentation, and the source-of-truth in DefinitelyTyped (that powers both these documents and IntelliSense). The changes should be merged to the live branch soon.

Thanks again for raising this issue and your interest in Office Add-ins. If you have any other questions, please let us know.

**Comment by calbrecht** [comment]
@AlexJerabek thank you for the quick responses and getting the docs updated 👍
