### ISSUE TITLE
Missing signature for handler:function

### ISSUE THREAD

**Issue by timothyhoffmann** [OfficeDev/office-js-docs-reference#753]
[Enter feedback here]
What is the signature of the handler function for DialogMessageReceived and DialogEventReceived:
addEventHandler(eventType: Office.EventType, handler: Function): void;

e.g. is the Function receiving a String, an Office.XXX type, etc?   This is used for TypeScript implementations.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 78feb8dc-736e-4f5f-0941-23532db2cae6
* Version Independent ID: ad69c160-6db4-bafc-f839-6ec4b2dc7264
* Content: [Office.Dialog interface - Office Add-ins](https://docs.microsoft.com/en-us/javascript/api/office/office.dialog?view=word-js-preview)
* Content Source: [docs/docs-ref-autogen/office/office/office.dialog.yml](https://github.com/OfficeDev/office-js-docs-reference/blob/live/docs/docs-ref-autogen/office/office/office.dialog.yml)
* Product: **non-product-specific**
* Technology: **add-ins**
* GitHub Login: @o365devx
* Microsoft Alias: **o365devx**

**Comment by ElizabethSamuel-MSFT** [comment]
@timothyhoffmann Thanks for asking about this.

@Rick-Kirkham Can you take a look?

Thanks.

**Comment by Rick-Kirkham** [comment]
@timothyhoffmann The following is the updated reference, copied from the Markdown source file. This should be in the published docs in a few days. 

 /**
         * Registers an event handler. The two supported events are:
         *
         * - DialogMessageReceived. Triggered when the dialog box sends a message to its parent.
         *
         * - DialogEventReceived. Triggered when the dialog box has been closed or otherwise unloaded.
         * 
         * @param eventType Must be either DialogMessageReceived or DialogEventReceived.
         * @param handler A function which accepts either an object with a `message` property, if eventType is DialogMessageReceived, or an object with an `error` property, if eventType is DialogEventReceived.
         */
        addEventHandler(eventType: Office.EventType, handler: (args: {message: string | boolean} | {error: number}) => void): void;
