### ISSUE TITLE
How is Excel.SettingCollection different from Office.Settings interface?

### ISSUE THREAD

**Issue by wh1t3cAt1k** [OfficeDev/office-js-docs-reference#769]
Do they write to the same location?

What are the differences between the two approaches, and which is preferred in which case?

Can these settings be accessed from VBA?

**Comment by AlexJerabek** [comment]
Hi @wh1t3cAt1k, 

Thank you for the question. I'm going to confirm with the product team, but I do believe these write to the same location and functionality work the same. Our general guidance is that if there is an application-specific version of an API, to use that version instead of the Common API. In this case, you should prefer Excel.SettingCollection over Office.Settings. This lets your add-in have a consistent model for interacting with the workbook.

These settings can be accessed through VBA, as they are part of the workbook.

**Comment by wh1t3cAt1k** [comment]
@AlexJerabek thank you so much! 

I cannot stress enough how it is important for me to access this through VBA, too, as I would like to migrate my legacy product to this approach, too, to avoid having a backwards compatibility layer.

Do you know of anyone who can give any guidance on how to do this?

**Comment by AlexJerabek** [comment]
I've started an internal thread with @lumine2008 and @catchingyu to answer the VBA question. We'll get back to you soon.

**Comment by wh1t3cAt1k** [comment]
Thanks @AlexJerabek 👌👌👌

**Comment by wh1t3cAt1k** [comment]
Hi Alex! Just to follow up, has the team reached any conclusion on how
Office.js add-in settings can be accessed from the VBA?
I studied the VBA object model and have not found a way, however you
mentioned in this thread that this was possible.

Thank you!

**Comment by AlexJerabek** [comment]
Hi @wh1t3cAt1k,
I'll ping our team and get them to respond on this thread. Thanks for your patience.

**Comment by lumine2008** [comment]
Hi @wh1t3cAt1k , 

Yes, As Alex mentioned that these write to the same location, so you can access the setting saved by Office. Settings via Excel.SettingCollection, but a small difference on usage. for example, office.settings.add will not save setting to document automatically , it need call saveAsync() explicitly. Excel.Settings will save to document automatically when adding. 

But we suggest that you use Excel.SettingCollection over Office.Settings. Excel.SettingCollection belongs.

**Comment by wh1t3cAt1k** [comment]
Hi @lumine2008 ! 

Thank you for the answer. Would you be able to confirm that I can access the same setting collection through VBA or is it impossible?

**Comment by lumine2008** [comment]
I cannot confirm this question as I am not the owner of VBA. But based on the definition, it doesn't seem it should be accessed by VBA add-ins. 
![image](https://user-images.githubusercontent.com/26398035/91968360-20625e80-ed47-11ea-9371-77f6a73bb645.png)
if you would like to have access from VBA and JS, I would suggest that you could use workbook.customProperty. it can access by VBA and JS

**Comment by AlexJerabek** [comment]
Hi @wh1t3cAt1k, 

I believe your original question has been answered. I'm going to close the issue, but please respond back if I'm mistaken. Thanks!
