### ISSUE TITLE
I cannot see `messageChild` as a method in `Office.Dialog` interface, but I can still seem to use it if I keep the dialog object as `any`

### ISSUE THREAD

**Issue by astak15** [OfficeDev/office-js-docs-reference#770]
In my @types/office-js library, the interface `Office.Dialog` has three methods: `addeventHandler`, `close`, and `sendMessage `(which says it is for internal usage only). I do not see the interface messageChild (but I'm still able to use the method if I specify the dialog object as `any`.

This is how the Office.Dialog object looks like:

`interface Dialog {
        /**
         * Called from a parent page to close the corresponding dialog box. 
         */
        close(): void;
        /**
         * Registers an event handler. The two supported events are:
         *
         * - DialogMessageReceived. Triggered when the dialog box sends a message to its parent.
         *
         * - DialogEventReceived. Triggered when the dialog box has been closed or otherwise unloaded.
         * 
         * @param eventType Must be either DialogMessageReceived or DialogEventReceived.
         * @param handler A function which accepts either an object with a `message` property, if eventType is DialogMessageReceived, or an object with an `error` property, if eventType is DialogEventReceived.
         */
        addEventHandler(eventType: Office.EventType, handler: (args: {message: string | boolean} | {error: number}) => void): void;
        /**
         * FOR INTERNAL USE ONLY. DO NOT CALL IN YOUR CODE.
         */
        sendMessage(name: string): void;
    }`

Please look into this issue.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 78feb8dc-736e-4f5f-0941-23532db2cae6
* Version Independent ID: ad69c160-6db4-bafc-f839-6ec4b2dc7264
* Content: [Office.Dialog interface - Office Add-ins](https://docs.microsoft.com/en-us/javascript/api/office/office.dialog?view=word-js-preview#messagechild-message-)
* Content Source: [docs/docs-ref-autogen/office/office/office.dialog.yml](https://github.com/OfficeDev/office-js-docs-reference/blob/live/docs/docs-ref-autogen/office/office/office.dialog.yml)
* Product: **non-product-specific**
* Technology: **add-ins**
* GitHub Login: @o365devx
* Microsoft Alias: **o365devx**

**Comment by AlexJerabek** [comment]
Thanks for reporting this @astak15. 

@Rick-Kirkham, can you please investigate this?

**Comment by Rick-Kirkham** [comment]
This is expected. The `messageChild` method is still in preview, so it is in the office-js-preview library, not the office-js library. If you want the method to show up in intellisense and be strongly typed, you need to load office-js-preview instead of office-js in your add-in. We expect this API to release very shortly. About the time that it does, it will be copied to office-js.
