### ISSUE TITLE
The reference articles for the *OrNullObject methods and properties should link to the explanation of how they work

### ISSUE THREAD

**Issue by AltitudeApps** [OfficeDev/office-js-docs-reference#771]
Firstly, it should be clarified that `getItemOrNullObject` never actually returns a null, as someone programming in vanilla javascript might expect.

Secondly, it should be mentioned that the information about whether or not the item which gets returned by the function has the `.isNullObject` property set to `true` needs to call `.load('isNullObject'); await ctx.sync()` before the information that the object actually satisfies the predicate `obj.isNullObject === true` is actually available in the current context.  

more discussion here:   https://github.com/OfficeDev/office-js/issues/195#issuecomment-680228432

(this topic would also apply to any other function in the API with might operate in a similar fashion; that is, any function which would require the user to do the `.load() / .sync()` dance in order get access to the information whether or not the function call operated as desired/envisioned.  I am only aware of this function so far.)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: bbcf4665-62f5-1ee3-2d18-75bb1313bab5
* Version Independent ID: b00fa1ed-f87d-928a-c231-dc8c7aa6dc26
* Content: [Excel.WorksheetCollection class - Office Add-ins](https://docs.microsoft.com/en-us/javascript/api/excel/excel.worksheetcollection?view=excel-js-1.11)
* Content Source: [docs/docs-ref-autogen/excel_1_11/excel/excel.worksheetcollection.yml](https://github.com/OfficeDev/office-js-docs-reference/blob/live/docs/docs-ref-autogen/excel_1_11/excel/excel.worksheetcollection.yml)
* Product: **excel**
* Technology: **add-ins**
* GitHub Login: @o365devx
* Microsoft Alias: **o365devx**

**Comment by Rick-Kirkham** [comment]
Actually, the reference articles for *OrNullObject methods and properties should just link to our explanation of how they work, which is here: [*OrNullObject](https://docs.microsoft.com/en-us/office/dev/add-ins/excel/excel-add-ins-advanced-concepts?view=excel-js-1.11#ornullobject-methods)

But the current reference articles, and the article I linked to above, actually say something false. These methods/properties to not ever return a null object. If the entity does not exist in the document, then they return an object whose `isNullObject` property has been set to `true`. 

Also, I believe that the `isNullObject` property is loaded by default, so an explicit loading of it is not required.

**Comment by AltitudeApps** [comment]
Thanks for responding so quickly.

Yup, you are totally right...  I commented out my `.load('isNullObject')`; and checked to see that `.isNullObject` was actually available subsequent to my call to `await ctx.sync()`  

> Actually, the reference articles for *OrNullObject methods and properties should just link to our explanation of how they work, which is here: [*OrNullObject](https://docs.microsoft.com/en-us/office/dev/add-ins/excel/excel-add-ins-advanced-concepts?view=excel-js-1.11#ornullobject-methods)

I agree, a link to that information would have been quite helpful.  

Would it be out of line to suggest that the example code in that item might be improved thusly?

```
return context.sync()
  .then(function() {

    // no need to call .load('isNullObject') ,
    // this is done implicitly and automatically...
    // ... but remember, it is not available until 
    // *after* the call to context.sync() has completed

    if (dataSheet.isNullObject) {
        // Create the sheet
    }

    dataSheet.position = 1;
    //...
  })
```
I think it should call out the fact that it is doing something that is different - but not completely different, in that you still need to call `ctx.sync()`.

I also think that that  [*OrNullObject](https://docs.microsoft.com/en-us/office/dev/add-ins/excel/excel-add-ins-advanced-concepts?view=excel-js-1.11#ornullobject-methods)  topic should include some discussion about what a "null object" actually is...   When I `console.log()` one of those pre-sync objects, I see an object with the same properties that I see when logging the same type of object after a call to `ctx.sync()`.  In other words, it doesn't look very "null" at first glance.  It is an object of the correct type, but most of the properties other than things like `._scalarPropertyNames` have values like '<Permission denied>', or objects containing fields with null values.   It isn't at all clear what I'm looking at, unless I know in advance.

That topic says:
> An *OrNullObject method will return a null object (not the JavaScript null) 

So, what exactly is a "null object"?  It is slightly helpful, in that it explicitly warns the user that it isn't talking about a javascript null, but it does nothing to prepare the reader that what it is actually talking about is an object with all of the expected properties, but that almost none of the properties have useful values.

I was staring right at one (a "null object") in my console log, but would not have connected what I was looking at with the words "null object".   So adding a paragraph which discusses what is meant by the phrase "null object" would be quite helpful.

I will alter the title of this issue to reflect the idea that the all the `*OrNullObject` style methods should link to the topic: 
 [*OrNullObject](https://docs.microsoft.com/en-us/office/dev/add-ins/excel/excel-add-ins-advanced-concepts?view=excel-js-1.11#ornullobject-methods)

**Comment by Rick-Kirkham** [comment]
The improvements to [*OrNullObjects](https://docs.microsoft.com/en-us/office/dev/add-ins/develop/application-specific-api-model#ornullobject-methods-and-properties) are in review and should publish in a few days. Improvements to the reference topics for the various *OrNullObject properties and methods is underway.

**Comment by AltitudeApps** [comment]
ok, great!

Could you tell me which branch these changes are happening on?  I updated my repo from upstream, but I can't find anything that is relevant to this concern.

Also:  I am imagining that there should be updates happening over in DefinitelyTyped, since that's where the text originates from.  I was looking into setting up that toolchain to see if I could create a set of pull requests, involving the repos in question, but then I saw your comment that said things were already in the works.

Is there a branch over there I can track?

**Comment by Rick-Kirkham** [comment]
The conceptual docs are in a different repo. The PR for that change is here: [https://github.com/OfficeDev/office-js-docs-pr/pull/2132/files](https://github.com/OfficeDev/office-js-docs-pr/pull/2132/files)

Changes to the reference docs are not actually made in this repo. Changes made to the Excel-specific APIs, like this one, are made in source files that are not public and eventually, through a series of tools, they are injected into the TypeScript definition file on DefinitelyTyped. That process is underway, but I don't expect the changes to reach DefinitelyTyped for at least a couple of weeks. But I can tell you what the change will be. It will be applied to all the *OrNullObject methods and properties in Excel. They will all say something like

> If there are no matches, this function will return an object with its `isNullObject` property set to `true`. For further information, see {LINK TO CONCEPTUAL TOPIC WILL BE HERE}.

**Comment by AltitudeApps** [comment]
I'm loving it.  This is perfect.
```
[!NOTE]
The `*OrNullObject` variations do not ever return the JavaScript value `null`. They return ordinary Office proxy objects.
If the the entity that the object represents does not exist then the `isNullObject` property of the object is set to `true`.
Do not test the returned object for nullity or falsity. It is never `null`, `false`, or `undefined`.
```

Yes, I was aware of the  [OfficeDev/office-js-docs-pr](https://github.com/OfficeDev/office-js-docs-pr)  repo; but I was trying to trace back where the function signatures and such came from, so the DefinitelyTyped repo became my focus.

I really like this wording:
> If there are no matches, this function will return an object with its isNullObject property set to true. For further information, see {LINK TO CONCEPTUAL TOPIC WILL BE HERE}.

However, I'd rather see the &nbsp; _"The `*OrNullObject` variations do not ever return the JavaScript value `null`. ..."_ &nbsp; text included directly in the source.  Information like this belongs in a comment.  I propose that there should be an object added to the office-js API whose only purpose is to contain a dummy example of an `*OrNullObject` method, whose only two purposes are to:
1.  Contain the _"...`*OrNullObject` variations do not ever..."_ text in the doc comment block,
2.  Return an exemplar "null object", with the `isNullObject` property set to `true`, (obviously), and a prominently named property called "explainThisToMe", which simply evaluates to the same text.

Then simply refer to this exemplar object in the doc comments of each method.  

There still remain times when I'm not continuously connected to a network, and running across a hyperlink while reading a non-HTML document is frustrating, especially when I'm reading code, and I expect explanatory expositive text to just be right there in the comments I'm already reading.  I mean, I'm already reading a comment...  the text is right there.   _Just tell me._

In fact, the article published at the proposed hyperlink should be generated from the doc comment block of the dummy exemplar object, just like all the documentation for all the methods and properties is being generated...

Just an idea.  No idea if it'd even be feasible.

**Comment by AltitudeApps** [comment]
> However, I'd rather see the   _"The `*OrNullObject` variations do not ever return the JavaScript value `null`. ..."_   text included directly in the source.

Of course, as I woke up, I realized that after having asked for an external link to the information, and been graciously granted such, I immediately modified my request such that I wasn't asking for a link anymore.  Ha.

**Comment by ElizabethSamuel-MSFT** [comment]
Closing this as the related PR has been merged.

**Comment by Rick-Kirkham** [comment]
@ElizabethSamuel-MSFT This is actually a 2 part item. The conceptual topics were fixed, but @alison-mk also is going to add links to the conceptual from the relevant reference topics. Is it OK if I reopen this for that reason?

**Comment by ElizabethSamuel-MSFT** [comment]
I didn't realize that. Sorry about that. I'll reopen it.

**Comment by alison-mk** [comment]
Update: I've made the requested changes to the reference docs, so the update is now in a PR internally and will be live soon! I'll update this issue when the changes are live.

**Comment by ElizabethSamuel-MSFT** [comment]
@alison-mk Are these changes live now? Can this issue be closed?

**Comment by alison-mk** [comment]
@ElizabethSamuel-MSFT No, the updates are still in the pipeline. I would like to leave this issue open until they are live.

**Comment by alison-mk** [comment]
Closing this issue as the update has been pushed to the preview API set (ex: [worksheetOrNullObject](https://docs.microsoft.com/en-us/javascript/api/excel/excel.nameditem?view=excel-js-preview#worksheetOrNullObject)) and will be pushed to the public API set in a future release. Thanks again for taking the time to contribute feedback!
