### ISSUE TITLE
Would be great to have JS examples of how to get this information. 

### ISSUE THREAD

**Issue by jakobpn** [OfficeDev/office-js-docs-reference#809]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2f739e0b-0574-7403-ea92-e0b1033e7bd2
* Version Independent ID: 8922891f-5d83-281f-53ab-3d1c83fd4a0f
* Content: [Office.ContextInformation interface - Office Add-ins](https://docs.microsoft.com/en-us/javascript/api/office/office.contextinformation?view=excel-js-preview)
* Content Source: [docs/docs-ref-autogen/office/office/office.contextinformation.yml](https://github.com/OfficeDev/office-js-docs-reference/blob/live/docs/docs-ref-autogen/office/office/office.contextinformation.yml)
* Product: **non-product-specific**
* Technology: **add-ins**
* GitHub Login: @o365devx
* Microsoft Alias: **o365devx**

**Comment by ElizabethSamuel-MSFT** [comment]
@jakobpn Thanks for asking about this. The docs should be updated with these samples when we publish next week.

Do take a look at the associated PR and give us your feedback, if any.

Thanks.
