### ISSUE TITLE
it is not documented that prependAsync behaves differently between Web and Desktop Outlook

### ISSUE THREAD

**Issue by LokiMidgard** [OfficeDev/office-js-docs-reference#827]
I have written an Add-In that uses `prependAsync` to add some text (html divs with background and border). And this works well in the Web version. However the Desktop Outlook messes the text up. Replacing almost everything with paragraphs and spans.

~~This should mentioned in the `SetAsync` method but not prepand.~~  
This is mentioned in the `SetAsync` method but not in prepand.

Also the documentation state 

>The client may modify the value passed to setAsync in order to make it render efficiently with its rendering engine.

Reading this I would think that changes would not change apearience of the text much. But at least divs with background color do not work.

```html
<div bgcolor='#f8f8f8' style='background: #f8f8f8; padding: 1em;margin-top: 1em;'>
<p><b>Die folgenden Anhänge können direkt heruntergeladen werden.</b>
</p>
<div><a href='{url}'>{name}</a></div>
</div>
```
gets to that:
```html
<div style="margin-top:12.0pt">
<p style="background:#F8F8F8"><b><span lang="DE" style="color:black">Some Text.</span></b><span lang="DE"></span></p>
<div>
<p class="x_MsoNormal" style="background:#F8F8F8"><span style="color:black"><a href="{url}" target="_blank">{name}</a></span></p>
</div>
</div>
```

Instead of having a block in grey I got two blocks around two different paragraphs. `<ul>` also does not work correktly.

It would be nice if it would be better documented what is supported and what not. Especially since this seems to be dependend on the Client.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 11e5f17d-2a4b-6aa5-0846-836e78e004a7
* Version Independent ID: 347c34b6-0586-9ce5-2c84-ae010c27b276
* Content: [Office.Body interface - Office Add-ins](https://docs.microsoft.com/en-us/javascript/api/outlook/office.body?view=outlook-js-1.9#prependasync-data--options--callback-)
* Content Source: [docs/docs-ref-autogen/outlook_1_9/outlook/office.body.yml](https://github.com/OfficeDev/office-js-docs-reference/blob/live/docs/docs-ref-autogen/outlook_1_9/outlook/office.body.yml)
* Product: **outlook**
* Technology: **add-ins**
* GitHub Login: @o365devx
* Microsoft Alias: **o365devx**

**Comment by AlexJerabek** [comment]
Thanks for reporting this @LokiMidgard. 

@ElizabethSamuel-MSFT, can you please investigate?

**Comment by ElizabethSamuel-MSFT** [comment]
@exextoc Can you take a look? Thx.

**Comment by exextoc** [comment]
Bug 1768727<https://o365exchange.visualstudio.com/O365%20Core/_workitems/edit/1768727>: [OfficeDev/office-js-docs-reference] it is not documented that prependAsync behaves differently between Web and Desktop Outlook (#827)
________________________________

**Comment by exextoc** [comment]
Could you share the Outlook build number you are testing this on?

**Comment by LokiMidgard** [comment]
@exextoc `Outlook 2016 MSO 16.0.13328.20262 64-bit`

**Comment by ElizabethSamuel-MSFT** [comment]
@LokiMidgard We'll update the documentation with a similar message as the setAsync API.

Thanks.

**Comment by ElizabethSamuel-MSFT** [comment]
@LokiMidgard The reference docs should be updated with this change later this week.

Thanks.
