### ISSUE TITLE
How can I insert a slide with insertSlidesFromBase64(base64File, options) into the current presentation?

### ISSUE THREAD

**Issue by alexfibr** [OfficeDev/office-js-docs-reference#833]
Hi,

I am experimenting with the JavaScript APIs in beta/preview for a MS PowerPoint Add-in. What I want to achieve is to insert a new slide from a base64-encoded .pttx file into the current document.

I would expect that this is possible with the insertSlidesFromBase64(base64File, options) method, which is documented here: PowerPoint API doc

I have included https://appsforoffice.microsoft.com/lib/beta/hosted/office.js in the Add-in

I am working on Mac OS 10.15.7

I have updated PowerPoint to the newest version in the Beta Channel. The PowerPoint Version is 16.44 (20111100).

Now, I am not quite sure if the beta API Methods are actually available in my environment. The bigger issue I am facing is that I don't know on which object I can call this method. I think the method should be available somewhere in the context of the current document/presentation?!?

I think a very simple example of how I can insert a "base64EncodedPptx" with `insertSlidesFromBase64("base64EncodedPptx")`
would probably clarify how this works.

Regards, Alex
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: de9f748c-ccbe-c242-07d8-2cc6e91e2658
* Version Independent ID: 8821a017-b462-d76b-3022-8d3ba34e8f32
* Content: [PowerPoint.Presentation class - Office Add-ins](https://docs.microsoft.com/en-us/javascript/api/powerpoint/powerpoint.presentation?view=powerpoint-js-preview)
* Content Source: [docs/docs-ref-autogen/powerpoint/powerpoint/powerpoint.presentation.yml](https://github.com/OfficeDev/office-js-docs-reference/blob/live/docs/docs-ref-autogen/powerpoint/powerpoint/powerpoint.presentation.yml)
* Product: **powerpoint**
* Technology: **add-ins**
* GitHub Login: @o365devx
* Microsoft Alias: **o365devx**

**Comment by AlexJerabek** [comment]
Hi @alexfibr, 

Thanks for the sample request. We're in the process of putting together a set of documentation to better explain the upcoming PowerPoint APIs and their object model. @Rick-Kirkham is leading this effort.  I'll assign him this issue to follow-up with a timeline and a specific response to slide insertion question.

As for Mac availability, preview APIs are not guaranteed to have cross-platform support. While I believe the API in question is (or will soon be) available to you, I'd recommend testing in PowerPoint for the web as well. That'll be the first platform to fully support the upcoming PowerPointApi 1.2 requirement set.

**Comment by alexfibr** [comment]
Thank you for the info. Looking forward to your update in the docs.

**Comment by Rick-Kirkham** [comment]
This is now documented here: [Insert slides into presentation](https://docs.microsoft.com/en-us/office/dev/add-ins/powerpoint/insert-slides-into-presentation)
