### ISSUE TITLE
Bug in documentation for getRange(rangeLocationString)

### ISSUE THREAD

**Issue by pb-jeff-oneill** [OfficeDev/office-js-docs-reference#864]
The documentation for `getRange(rangeLocationString)` lists "Before" as a valid option, but it is not a valid option.  I spent hours trying to figure out why my code wasn't working.  :(

Please also describe what the options mean in greater detail.

- What is the difference between End and After?
- What is the difference between Whole and Content?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 578c5e3f-8dd7-2e92-3cdc-21c5a378fba7
* Version Independent ID: 366375be-7700-ecc4-0718-9ef9fbd4871b
* Content: [Word.Range class - Office Add-ins](https://docs.microsoft.com/en-us/javascript/api/word/word.range?view=word-js-preview#getRange_rangeLocation_)
* Content Source: [docs/docs-ref-autogen/word/word/word.range.yml](https://github.com/OfficeDev/office-js-docs-reference/blob/live/docs/docs-ref-autogen/word/word/word.range.yml)
* Product: **word**
* Technology: **add-ins**
* GitHub Login: @o365devx
* Microsoft Alias: **o365devx**

**Comment by lindalu-MSFT** [comment]
Hi Alison and Elizabeth, not sure who the Word Doc person is. Can you look into this and see if we can quickly clarify the docs? Thanks, lindalu

**Comment by AlexJerabek** [comment]
Hi @pb-jeff-oneill, 

Thanks for pointing out this issue. I'm sorry to hear about your frustration.

It looks like the description doesn't list "Before" as a valid option, but the type definition includes it. This appears to be a recurring problem in the APIs, as all string-based overloads of enum-taking APIs list out every enum, despite any actual limitations. Our reference documentation is generated from these type definition files, and even if we change that to correct the mistake you've highlighted, the Intellisense/TS compilation experience will still show "Before". 

I'll tag @sumurthy and @jayrathi to investigate fixing the underlying type definition file. In the meantime, would the documentation be less confusing if the string-overload version didn't exist? Something like this:

![image](https://user-images.githubusercontent.com/38896772/102834227-4e2beb80-43a8-11eb-80e3-45facb57a9ca.png)

**Comment by AlexJerabek** [comment]
> What is the difference between End and After?
> What is the difference between Whole and Content?

I made a little [Script Lab](https://docs.microsoft.com/office/dev/add-ins/overview/explore-with-script-lab) snippet to help show these distinctions: https://gist.github.com/AlexJerabek/5d0acdc7cc1433ef92b022781cb3e9bf

Basically, the takeway from the [RangeLocation page(https://docs.microsoft.com/en-us/javascript/api/word/word.rangelocation?view=word-js-preview) is that "Whole" and "After" include the paragraph break character, whereas "Content" and "End" don't. This is easier to see with the snippet if you turn on "Show All" in Word:
![image](https://user-images.githubusercontent.com/38896772/102835277-1ecaae00-43ab-11eb-8bd5-0eac6fcd378e.png)

**Comment by lindalu-MSFT** [comment]
Thank you @AlexJerabek for the prompt response! Sadly, I can't add this info to the topic because it's autogen'd. Is there another way we can publish this info to our customers?
