### ISSUE TITLE
Wrong description of ItemType

### ISSUE THREAD

**Issue by clavx** [OfficeDev/office-js-docs-reference#866]
This statement "meeting request, meeting response, or meeting cancellation" should be in Appointment.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1ec870cc-bfc3-842c-f2a9-2ef1bcbbf2d7
* Version Independent ID: 91cf53e4-dfae-bc2e-648a-86a4d8831cc7
* Content: [Office.MailboxEnums.ItemType enum - Office Add-ins](https://docs.microsoft.com/en-us/javascript/api/outlook/office.mailboxenums.itemtype?view=outlook-js-preview)
* Content Source: [docs/docs-ref-autogen/outlook/outlook/office.mailboxenums.itemtype.yml](https://github.com/OfficeDev/office-js-docs-reference/blob/live/docs/docs-ref-autogen/outlook/outlook/office.mailboxenums.itemtype.yml)
* Product: **outlook**
* Technology: **add-ins**
* GitHub Login: @o365devx
* Microsoft Alias: **o365devx**

**Comment by AlexJerabek** [comment]
Thanks for raising this issue @clavx. 

@ElizabethSamuel-MSFT, can you please update the documentation as needed?

**Comment by ElizabethSamuel-MSFT** [comment]
@clavx Thanks for raising this issue. However, the documentation is correct. I confirmed that meeting requests, meeting responses, and meeting cancellations are message types.

If you run code like the following on any of these items, "message" should be the type.
```
console.log(`Item type: ${Office.context.mailbox.item.itemType}`);
// Sample output:- Item type: message
```

I'll go ahead and close this now but if you're getting a different response for any of these items, do share more info like Outlook build, client/platform, etc. and we can reopen this issue.

Thanks.

**Comment by clavx** [comment]
Sorry for the late reply.

In Outlook for Windows, I mistakenly thought that it should be included in the Appointment because it is shown as follows.

![win32_meeting01](https://user-images.githubusercontent.com/58804032/142376124-1d58aee0-402c-43b8-8968-5ca61df14770.png)

I recognize that "meeting request" also indicates the following:

![win32_meeting02](https://user-images.githubusercontent.com/58804032/142376143-cd30e4ab-fca3-4d70-8379-3d1cdbb4d3ff.png)

Thanks.

**Comment by ElizabethSamuel-MSFT** [comment]
@clavx Thanks for your response. If you're in calendar context, then meetings/appointments should be appointment type. However, meeting requests, meetings responses, and meeting cancellations are usually part of your messages and you won't find them in your calendar. As you may know, meeting requests and meeting cancellations are messages from the meeting's organizer (usually not created in the current mailbox), and meeting responses are messages from attendees for meetings you organized.

Hope this helps clear things up. Let us know if you have more questions about this.

Thanks.

**Comment by clavx** [comment]
@ElizabethSamuel-MSFT  Thank you for your prompt reply.

> As you may know, meeting requests and meeting cancellations are messages from the meeting's organizer (usually not created in the current mailbox), and meeting responses are messages from attendees for meetings you organized.

I'm sorry, but I'm confused about the interpretation of "meeting request".

I found the following document.

https://support.microsoft.com/en-us/office/schedule-a-meeting-with-other-people-5c9877bc-ab91-4a7c-99fb-b0b68d7ea94f

Hmmm...

I would appreciate it if you could tell me if the following interpretation is correct.

---

> An email, meeting request, meeting response, or meeting cancellation.

The description is about the mail in the attendee's mailbox.

- The "meeting request" is sent by the organizer and is as follows

In organizer's mailbox
![organizer_request](https://user-images.githubusercontent.com/58804032/142591400-96eac249-3b1e-43b7-b744-d3f5cc952bba.png)

![organizer_request_sent](https://user-images.githubusercontent.com/58804032/142591393-55ccbe3b-0ff4-4619-9df0-d881d7cb29ae.png)

In attendee's mailbox
![attendees_received](https://user-images.githubusercontent.com/58804032/142591456-dd3f753b-8f10-49ec-9af0-91030b4fa493.png)

- The "meeting cancellation" is sent by the organizer and is as follows

In organizer's mailbox
![organizer_cancel](https://user-images.githubusercontent.com/58804032/142591379-05c4e4a3-fa08-4a52-a604-3cf19d628c81.png)

![organizer_cancel_sent](https://user-images.githubusercontent.com/58804032/142592089-52bb2514-19ef-426c-a4c0-beb8338671bf.png)

In attendee's mailbox
![attendees_canceled](https://user-images.githubusercontent.com/58804032/142591421-44f6c3f6-2fe8-4a72-afe2-1deb056704df.png)

- The "meeting response" is sent by the attendee and is as follows

In attendee's mailbox

![attendees_received_accepted_01](https://user-images.githubusercontent.com/58804032/142596121-05a67a78-fdf4-43df-bb79-5a846ed82056.png)

![attendees_received_accepted_02](https://user-images.githubusercontent.com/58804032/142591448-fe3f69f4-4d2f-4a86-812c-8f36a2b315fc.png)

### Others

If you accept the meeting request, the item will be moved to the Deleted Items folder.

In organizer's mailbox (meeting cancelled)
![organizer_cancel_delete_sched](https://user-images.githubusercontent.com/58804032/142591364-c4e04a42-49c7-42e5-ac9d-fb6ef375b3ba.png)

In attendee's mailbox (meeting accepted)
![attendees_received_accepted_03](https://user-images.githubusercontent.com/58804032/142591430-fa06401f-516a-40fb-9e55-96fb53bdf4d3.png)

deleted meeting (cancel accepted)
![attendees_canceled_delete_sched](https://user-images.githubusercontent.com/58804032/142591411-b3bfcbb8-f2b4-43f4-a066-eb5c6c761fe4.png)

Thanks.

**Comment by clavx** [comment]
@ElizabethSamuel-MSFT Sorry, I finally understand.

> If you're **in calendar context**, then meetings/appointments should be appointment type. However, meeting requests, meetings responses, and meeting cancellations are usually part of your messages and you won't find them **in your calendar**.

The difference in where the item is displayed after it is created is the key.
I was focusing only on the words and got confused.

Thank you very much for your detailed explanation!

**Comment by ElizabethSamuel-MSFT** [comment]
@clavx You're welcome! :)
