### ISSUE TITLE
overwriteIfStale is not helpful without an example

### ISSUE THREAD

**Issue by wh1t3cAt1k** [OfficeDev/office-js-docs-reference#875]
The options description mentions an `overwriteIfStale` option, but it is difficult to understand its purpose and mechanics without a more detailed example.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 350844cd-9cfd-bb95-c937-4eabe70e425d
* Version Independent ID: 12ec4657-cb1e-ad43-a092-06ac66f0faa8
* Content: [Office.SaveSettingsOptions interface - Office Add-ins](https://docs.microsoft.com/en-us/javascript/api/office/office.savesettingsoptions?view=excel-js-preview)
* Content Source: [docs/docs-ref-autogen/office/office/office.savesettingsoptions.yml](https://github.com/OfficeDev/office-js-docs-reference/blob/live/docs/docs-ref-autogen/office/office/office.savesettingsoptions.yml)
* Product: **non-product-specific**
* Technology: **add-ins**
* GitHub Login: @o365devx
* Microsoft Alias: **o365devx**

**Comment by AlexJerabek** [comment]
Hi @wh1t3cAt1k, 

Thank you for the question. @MandytMSFT, could you provide some information about the `overwriteIfStale` property?

Also, @wh1t3cAt1k, what Office application are you developing for? If you're using Excel, we recommend using the [Excel-specific version of the Settings API](https://docs.microsoft.com/en-us/javascript/api/excel/excel.setting?view=excel-js-preview). You can learn more about how to use that API in [this article](https://docs.microsoft.com/en-us/office/dev/add-ins/excel/excel-add-ins-workbooks#access-document-settings)

**Comment by wh1t3cAt1k** [comment]
I am writing an Excel add-in indeed. Just was experimenting with an
alternative API and noticed I could not understand this flag, so I still
think it would be good to clarify - unlikely I am the last to ask...

**Comment by AlexJerabek** [comment]
Thanks @wh1t3cAt1k. According to the product team, `overwriteIfStale` is depreciated and it's use is not advised. I need to confirm a couple things, but I'll update the documentation to reflect the current guidance.

**Comment by AlexJerabek** [comment]
The documentation has been updated to reflect the depreciated property. I'll close the issue now.
