### ISSUE TITLE
Height description has the word width

### ISSUE THREAD

**Issue by OfficeAddins** [OfficeDev/office-js-docs-reference#888]
Under the property "Height" you have the word "width".
Is it possible to include a specific height for example "300px" instead of just a percentage ?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: fc786795-1b1f-3661-5a68-b4e1aa8b4976
* Version Independent ID: 97e021a5-b316-1514-5f95-ba3eef24c960
* Content: [Office.DialogOptions interface - Office Add-ins](https://docs.microsoft.com/en-us/javascript/api/office/office.dialogoptions?view=excel-js-preview)
* Content Source: [docs/docs-ref-autogen/office/office/office.dialogoptions.yml](https://github.com/OfficeDev/office-js-docs-reference/blob/live/docs/docs-ref-autogen/office/office/office.dialogoptions.yml)
* Product: **non-product-specific**
* Technology: **add-ins**
* GitHub Login: @o365devx
* Microsoft Alias: **o365devx**

**Comment by AlexJerabek** [comment]
Thanks for reporting this @OfficeAddins. 

@Rick-Kirkham, can you please take a look?

**Comment by Rick-Kirkham** [comment]
@OfficeAddins I'll fix the documentation. To answer your question, you have to use percentages, not pixels.
