### ISSUE TITLE
Outlook js api: ability to select/highlight text

### ISSUE THREAD

**Issue by ndvbd** [OfficeDev/office-js-docs-reference#892]
Is there a way to highlight or select a text (in the body) like in Google Docs API?
This is a very important ability for add-ins, and I can't find it in the documentation.

**Comment by AlexJerabek** [comment]
Hi @ndvbd, 

Thanks for raising this feature need. I noticed you already found the related [UserVoice entry](https://officespdev.uservoice.com/forums/224641-feature-requests-and-feedback/suggestions/38912296-api-to-move-cursor-text-selection-for-outlook-of), but for the sake of other viewers of this thread, please upvote that UserVoice request to help prioritize this feature.

While I don't believe this functionality exists in Outlook Add-ins today, let me tag @exextoc to weigh-in on potential workarounds.

**Comment by ndvbd** [comment]
It is opened there since 2019, and nobody responded

**Comment by exextoc** [comment]
We review and consider feature requests on user-voice when we go through our planning process. The more votes/attention a request receives, the higher its chances of being implemented.
