### ISSUE TITLE
Add link to Coercion Type Requirements

### ISSUE THREAD

**Issue by theboyknowsclass** [OfficeDev/office-js-docs-reference#894]
[Enter feedback here]

It would be good to add a link to the requirements here as well as on the SetSelectedDataAsync 
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 724a7e75-65a1-20d4-c402-90972a89f388
* Version Independent ID: eeab4111-f39d-7025-9831-52f7abd4405d
* Content: [Office.CoercionType enum - Office Add-ins](https://docs.microsoft.com/en-us/javascript/api/office/office.coerciontype?view=excel-js-preview)
* Content Source: [docs/docs-ref-autogen/office/office/office.coerciontype.yml](https://github.com/OfficeDev/office-js-docs-reference/blob/live/docs/docs-ref-autogen/office/office/office.coerciontype.yml)
* Product: **non-product-specific**
* Technology: **add-ins**
* GitHub Login: @o365devx
* Microsoft Alias: **o365devx**

**Comment by AlexJerabek** [comment]
Thanks for the suggestion, @theboyknowsclass. 

I'll look into making this requirement set information more accessible.

**Comment by AlexJerabek** [comment]
This issue has been addressed by #897. Those updates should reach the live branch soon. I'll close the issue now, but please let me know if there's more to be done.
