### ISSUE TITLE
Mistaken description of AddinCommands.source.id

### ISSUE THREAD

**Issue by Rick-Kirkham** [OfficeDev/office-js-docs-reference#919]
The second clause "and is the unique ID of your Office Add-in as a GUID" is wrong and should be deleted. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 62fbbb9b-7c92-4e9a-c6f2-6af51c7dad50
* Version Independent ID: 967199c4-582e-8d17-a16a-4d6526824548
* Content: [Office.AddinCommands.Source interface - Office Add-ins](https://docs.microsoft.com/en-us/javascript/api/office/office.addincommands.source?view=common-js)
* Content Source: [docs/docs-ref-autogen/office/office/office.addincommands.source.yml](https://github.com/OfficeDev/office-js-docs-reference/blob/live/docs/docs-ref-autogen/office/office/office.addincommands.source.yml)
* Product: **non-product-specific**
* Technology: **add-ins**
* GitHub Login: @o365devx
* Microsoft Alias: **o365devx**

**Comment by AlexJerabek** [comment]
I'll make the necessary upstream changes in DefinitelyTyped and tag you in the PR,

**Comment by AlexJerabek** [comment]
This was fixed with https://github.com/OfficeDev/office-js-docs-reference/pull/920.
