### ISSUE TITLE
Need to clarify where the code goes

### ISSUE THREAD

**Issue by Rick-Kirkham** [OfficeDev/office-js-docs-reference#932]
This Stack issue has a good point. The article should be clear early where the API might be called. It should also have a snippet that shows the API in use, possibly taken from the sample https://github.com/OfficeDev/PnP-OfficeAddins/blob/3ce0e1b74152dbbe8306a091696bc4455c04c0a1/Samples/excel-shared-runtime-scenario/utilities/office-apis-helpers.ts

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 59c7d64c-07df-0b53-da1b-f9d23e41a894
* Version Independent ID: c7152cc0-9158-eb38-406c-209f240f3c91
* Content: [Office.Addin interface - Office Add-ins](https://docs.microsoft.com/en-us/javascript/api/office/office.addin?view=excel-js-preview)
* Content Source: [docs/docs-ref-autogen/office/office/office.addin.yml](https://github.com/OfficeDev/office-js-docs-reference/blob/live/docs/docs-ref-autogen/office/office/office.addin.yml)
* Product: **non-product-specific**
* Technology: **add-ins**
* GitHub Login: @o365devx
* Microsoft Alias: **o365devx**

**Comment by AlexJerabek** [comment]
@Rick-Kirkham, can you please provide a link to the Stack issue in question?

**Comment by Rick-Kirkham** [comment]
My bad. It's this one: https://stackoverflow.com/questions/66977857/how-to-use-office-startupbehavior-load-inside-a-taskpane-add-in

**Comment by davidchesnut** [comment]
@Rick-Kirkham I created this PR to move the section higher. Can you please review? Thanks!
https://github.com/OfficeDev/office-js-docs-pr/pull/2946
