### ISSUE TITLE
Typo in property description

### ISSUE THREAD

**Issue by Rick-Kirkham** [OfficeDev/office-js-docs-reference#958]
This is passed on from Onur Onder: 
The description for the property **dashStyle** has the sentence "See Excel.ShapeLineStyle for details." This should be "See Excel.ShapeLineDashStyle for details."

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: cac9593e-cdbb-4064-306f-f85c5d572853
* Version Independent ID: 4a115b97-f917-8ecf-3e1d-d28d88d1f45c
* Content: [Excel.ShapeLineFormat class - Office Add-ins](https://docs.microsoft.com/en-us/javascript/api/excel/excel.shapelineformat?view=excel-js-preview)
* Content Source: [docs/docs-ref-autogen/excel/excel/excel.shapelineformat.yml](https://github.com/OfficeDev/office-js-docs-reference/blob/live/docs/docs-ref-autogen/excel/excel/excel.shapelineformat.yml)
* Product: **excel**
* Technology: **add-ins**
* GitHub Login: @o365devx
* Microsoft Alias: **o365devx**

**Comment by alison-mk** [comment]
Thanks! I've recorded this issue internally and will make the change to the reference docs source during my next round of updates.
