### ISSUE TITLE
Office js outlook, how to check if email is incoming or outgoing

### ISSUE THREAD

**Issue by spoman007** [OfficeDev/office-js-docs-reference#970]
I am creating a outlook plugin with taskpane. I am using office js to access the email.

I want to know if current email is incoming or outgoing in the plugin. Is there a way in office js that can help me with this?

I tried checking all the properties but could not find anything obvious.

Thanks!!

**Comment by peronald** [comment]
Thank you for this question. To better assist you, we suggest you go to [Microsoft Q&A](https://docs.microsoft.com/en-us/answers/questions/topics/single/192525.html) and see if your question has already been asked or ask a new question with the office-js-dev tag. This will allow both the community to help, and allow us to ensure the community can see our answer. When added, please let us know and we will follow up there. 
Thanks, 
Microsoft 365 Developer Platform team.

**Comment by ElizabethSamuel-MSFT** [comment]
@exextoc Any suggestions for this situation?

Thanks.

**Comment by exextoc** [comment]
Can you please clarify what you mean by the "current email is incoming or outgoing"? Can you describe your scenario?

**Comment by spoman007** [comment]
@exextoc I am using a outlook plugin and opening a taskpane.
I need to add different behaviour to taskpane depending on if the current email for which the taskpane is opened belongs to inbox or sent items.

`const [messageType, setMessageType] = useState(
    Office.context.mailbox.officeAppContext._docUrl.indexOf('sentitems') > -1
      ? 'Outgoing'
      : 'Incoming'
  );`
  
I tried using this but this only works in web but does not work in native outlook client.

**Comment by exextoc** [comment]
To clarify, the ask here is to get the folder in which the item belongs to (Parent folder)? This is currently not available with the JS API. You can consider using REST or EWS API to retrieve parent folder id.  https://docs.microsoft.com/en-us/office/dev/add-ins/outlook/use-rest-api

**Comment by exextoc** [comment]
It could be helpful for us if you can expand a bit on the requirement or taskpane behaviour difference you want to achieve with the information of whether the user is opening and reading from inbox vs sent items.
