### ISSUE TITLE
Create a new task in Project from Add-In

### ISSUE THREAD

**Issue by klugj24** [OfficeDev/office-js-docs-reference#971]
Is there any way to create a new task from an add-in in Project? I can only figure out how to modify existing tasks using the task GUID, however I cannot figure out how to create one. Any help would be greatly appreciated.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5530f30f-9d7b-a2e2-b30f-098556733c73
* Version Independent ID: 88f35bab-8f86-dd9b-66fa-43a554121a9b
* Content: [office package - Office Add-ins](https://docs.microsoft.com/en-us/javascript/api/office?view=excel-js-preview)
* Content Source: [docs/docs-ref-autogen/office/office.yml](https://github.com/OfficeDev/office-js-docs-reference/blob/live/docs/docs-ref-autogen/office/office.yml)
* Product: **non-product-specific**
* Technology: **add-ins**
* GitHub Login: @o365devx
* Microsoft Alias: **o365devx**

**Comment by AlexJerabek** [comment]
Hi @klugj24,

Thanks for raising this issue. As of today, you can only edit tasks through the JS APIs with an existing task ID. If this is a feature you need, please request it over on the [M365 Developer Platform Tech Community](https://techcommunity.microsoft.com/t5/microsoft-365-developer-platform/idb-p/Microsoft365DeveloperPlatform). There, other developers can upvote ideas, letting us prioritize according the to community needs.

I did find some information on using REST or CSOM to create new tasks in Project: https://techcommunity.microsoft.com/t5/project-support-blog/project-online-csom-and-rest-samples-showing-task-indent-and/ba-p/361899
Hopefully, that path can help fulfill your needs.

I'm going to close this issue, since there's nothing actionable we can do in the JS API documentation.

**Comment by klugj24** [comment]
Thank you for the quick response @AlexJerabek,

So, just to clarify - Microsoft wants us to build Office add-ins, or migrate our current VSTO add-ins to this new format as this is the only was we can get our add-in listed on the Microsoft App Store.  We are building these mostly for the MS Project Client, and only about 10% of our customers use Project Online.

Are you saying that Office Add-ins for Microsoft Project only support edit operations? Our scenario is to download project data from another cloud-based project management system and create the project in MS Project so that MS Project users can view and edit the project data in MS Project and then save the changes into the third-party project management system. We currently have a VSTO-based add-in that does this, but we'd like to be listed on the MS App store, and eventually work with Project online.

Besides just throwing our idea at Microsoft 365 Developer Platform Ideas site, is there somebody specific we can talk to about this?  It seems like Microsoft Project always gets the shaft when it comes to integration and I don't trust the ideas site to gain traction very quickly.

**Comment by AlexJerabek** [comment]
Hi @klugj24,
I'm reaching out to the product team for a connection or more detailed response.

To answer your main question, yes, only edit operations are supported in the JS library. It sounds like, based on your scenario, your best option is to remain with your VSTO solution. I understand your frustration and acknowledge that the JS platform has been focused primarily on Excel and Outlook over the last couple years. I will continue to try and find the best platform for you to share your scenario and needs directly with the Project team.

**Comment by klugj24** [comment]
Thank you @AlexJerabek, 

Please let me know how to get in touch with the project team ASAP!

**Comment by BeReasonable** [comment]
Hi @klugj24, 
Are you familiar with the new [Project for the web](https://support.microsoft.com/en-us/office/get-started-with-project-for-the-web-50bf3e29-0f0d-4b7a-9d2c-7c78389b67ad)? 

Much of our time has been spent building out that new product and investing in the tools needed by our customers and partners to extend it. This includes investing in support for native Power Platform tools such as Power Apps as well as the [APIs needed to manage tasks](https://docs.microsoft.com/en-us/dynamics365/project-operations/project-management/schedule-api-preview#error-handling). [Dataverse includes an odata](https://docs.microsoft.com/en-us/powerapps/developer/data-platform/webapi/overview) endpoint that can be used to work with our new service.
