### ISSUE TITLE
OnActivated Events should return Chart/Shape name

### ISSUE THREAD

**Issue by natejcho** [OfficeDev/office-js-docs-reference#980]
When queueing ChartCollection class, it is queued by name ie getItem(name). Yet the ChartActivatedEventArgs only returns a chartId. If I want more info about an activated chart, the event args are useless then, there should be a name property added to the chartactivatedeventargs so that more info about the activated chart can be accessed. This isn't limited to just the chart class either, it should have this paradigm for all chart/table/shape classes

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5501a74b-ea1e-39b0-bede-4995de760098
* Version Independent ID: 94e8480c-a624-dfb3-c2e4-f2e011338a41
* Content: [Excel.ChartActivatedEventArgs interface - Office Add-ins](https://docs.microsoft.com/en-us/javascript/api/excel/excel.chartactivatedeventargs?view=excel-js-preview)
* Content Source: [docs/docs-ref-autogen/excel/excel/excel.chartactivatedeventargs.yml](https://github.com/OfficeDev/office-js-docs-reference/blob/live/docs/docs-ref-autogen/excel/excel/excel.chartactivatedeventargs.yml)
* Product: **excel**
* Technology: **add-ins**
* GitHub Login: @o365devx
* Microsoft Alias: **o365devx**

**Comment by AlexJerabek** [comment]
Hi @natejcho, 

Thanks for reporting this. You can use the returned chart ID in the `ChartCollection.getItem` method. It should work just like the name. Please let us know if that's not the case.

Assigning @alison-mk to help verify and update the documentation accordingly.

**Comment by alison-mk** [comment]
Hi @natejcho, thanks for submitting an issue. I will update the [Chart.onActivated code sample](https://docs.microsoft.com/javascript/api/excel/excel.chart#onActivated) to clarify how to use the chart ID to retrieve data related to the activated chart. The updated code sample will have a pattern like this: 

` Excel.run(function (context){
    // Retrieve the worksheet.
    var sheet = context.workbook.worksheets.getItem("Sample");

    // Retrieve the activated chart by ID and load the name of the chart. 
    var activeChart = sheet.charts.getItem(event.chartId);
    activeChart.load(["name"]);

    return context.sync().then(function () {
      // Print out the active chart's data.
      console.log(`A chart was activated. ID: ${event.chartId}. Chart name: ${activeChart.name}.`);
      return context.sync();
    });
});`

Let us know if you have any additional questions.

Cheers, 
Alison
