### ISSUE TITLE
Can you provide examples for this page?

### ISSUE THREAD

**Issue by Mayu945** [OfficeDev/office-js-docs-reference#985]
[Enter feedback here]
Can you provide examples for this page?
How to access this property?

Take this link as an example
https://docs.microsoft.com/en-us/javascript/api/office/office.context?view=powerpoint-js-preview#license

// The following line of code access the item object of the JavaScript API for Office.
var item = Office.context.mailbox.item;

Thanks.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 267bfc06-f144-8b0b-249c-7ab9fc6e113e
* Version Independent ID: 36c12322-ac98-c9e2-5c63-ee983374a041
* Content: [Office.Control interface - Office Add-ins](https://docs.microsoft.com/en-us/javascript/api/office/office.control?view=powerpoint-js-preview)
* Content Source: [docs/docs-ref-autogen/office/office/office.control.yml](https://github.com/OfficeDev/office-js-docs-reference/blob/live/docs/docs-ref-autogen/office/office/office.control.yml)
* Product: **non-product-specific**
* Technology: **add-ins**
* GitHub Login: @o365devx
* Microsoft Alias: **o365devx**

**Comment by AlexJerabek** [comment]
Hi @Mayu945,

Thanks for the feedback. @Rick-Kirkham, can you please investigate adding some sample code that shows the object model for the [Control](https://docs.microsoft.com/en-us/javascript/api/office/office.control?view=powerpoint-js-preview) object?

**Comment by Rick-Kirkham** [comment]
The context of using this  interface is somewhat complex. I will add to the topic a link to the following article which includes several code samples.

 [Enable and disable Add-in Commands](https://docs.microsoft.com/en-us/office/dev/add-ins/design/disable-add-in-commands)
