### ISSUE TITLE
Unclear on how a unique 'add-in' is determined

### ISSUE THREAD

**Issue by theboyknowsclass** [OfficeDev/office-js-docs-reference#991]
in the docs it's stated as  -> "The settings created by using the methods of the Settings object are saved per add-in and per document. That is, they are available only to the add-in that created them, and only from the document in which they are saved."

How is this determined?  e.g. i the same manifest for the addin used in both Excel Desktop (windows) and Online.  However if i create a document in one platform, it is not guaranteed that the document settings can be read in Desktop.  

Is this intentional behavior?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9ce6d927-7da9-9b76-0010-3310f13f227c
* Version Independent ID: 42264a03-18a1-b0da-40ea-323a96584b6f
* Content: [Office.Settings interface - Office Add-ins](https://docs.microsoft.com/en-us/javascript/api/office/office.settings?view=excel-js-preview)
* Content Source: [docs/docs-ref-autogen/office/office/office.settings.yml](https://github.com/OfficeDev/office-js-docs-reference/blob/live/docs/docs-ref-autogen/office/office/office.settings.yml)
* Product: **non-product-specific**
* Technology: **add-ins**
* GitHub Login: @o365devx
* Microsoft Alias: **o365devx**

**Comment by AlexJerabek** [comment]
Thanks for the question @theboyknowsclass.

@Rick-Kirkham, can you please provide clarification?

**Comment by Rick-Kirkham** [comment]
@theboyknowsclass What is the source of your statement that  "if i create a document in one platform, it is not guaranteed that the document settings can be read in Desktop"?

**Comment by theboyknowsclass** [comment]
hi @Rick-Kirkham @AlexJerabek  thanks for the quick response (as always)

we have an add-in where we use the same manifest file on online and windows desktop - i'm testing in Work currently, but have seen the same behaviour in Excel and Powerpoint

when i create a document and add metadata using the settings API in the online version.  this does not appear in the desktop version.

this seems to be related to the specific desktop version as my colleagues on the latest build do not see it - i am using 2103, they are on 2105.

was there any bugs fixed in this period affecting this?

**Comment by Rick-Kirkham** [comment]
@theboyknowsclass  Yes. There were bug fixes. One of them was connected with this issue [1585](https://github.com/OfficeDev/office-js/issues/1585) in the office-js repo. I suspect that you are seeing a variation of this same bug. So, the fix for you is to update to 2105 or later. 

At any rate, since it is not happening on recent versions and the documentation seems to be correct, I'll close this for now. You can still add comments and request that it be reopened.
